Repository refined-github/refined-github, pull requests merged in 2018-05, with the labels that each got.

#1309 Fix some recent errors
  source/background.js
  source/features/add-scoped-search-on-user-profile.js
  source/features/add-your-repositories-link-to-profile-dropdown.js
  source/features/close-out-of-view-modals.js
  source/features/improve-shortcut-help.js
  source/features/linkify-urls-in-code.js
  source/features/mark-unread.js
Labels: bug

#1298 Fix keyboard shortcuts on comment fields
  source/features/add-keyboard-shortcuts-to-comment-fields.js
Labels: bug

#1311 📌Sticky Issues Header
  readme.md
  source/content.css
Labels: enhancement, needs readme update

#1167 Add hotkeys on Pull Request tabs
  readme.md
  source/content.js
  source/features/add-pull-request-hotkey.js
Labels: enhancement

#1328 Support non-semver versions
  package.json
  source/features/add-branch-buttons.js
  source/libs/compare-versions.js
  test/compare-versions.js
Labels: bug

#1326 Specify a title for upload attachments button
  source/features/upload-button.js
Labels: enhancement

#1332 Hide "used" buttons in notifications
  source/features/open-all-notifications.js
Labels: enhancement

#1333 Hide the "Review Summary" header
  source/content.css
Labels: enhancement

#1255 Create a release shortcut
  readme.md
  source/content.js
  source/features/add-create-release-shortcut.js
  source/features/add-releases-tab.js
  source/libs/page-detect.js
  test/page-detect.js
Labels: enhancement

#1335 Linkify code blocks in comments
  source/features/linkify-urls-in-code.js
Labels: bug

#1330 Drop a few dashboard-related changes
  readme.md
  source/background.js
  source/content.css
  source/content.js
  source/features/auto-load-more-news.js
  source/features/move-account-switcher-to-sidebar.js
Labels: bug

#1306 Lock review buttons after clicking
  source/features/add-quick-review-buttons.js
Labels: enhancement

#1241 Restore file-list highlight when using keyboard navigation
  source/content.css
  source/content.js
  source/features/hide-navigation-hover-highlight.js
Labels: change request, enhancement

#1344 Restore file copy feature
  source/features/copy-file-path.js
  source/features/copy-file.js
Labels: bug

#1346 Extract tiny-version-compare
  package.json
  source/features/add-branch-buttons.js
  source/libs/compare-versions.js
  test/compare-versions.js
Labels: bug

#1348 Drop broken user-scoped search
  readme.md
  source/content.js
  source/features/add-scoped-search-on-user-profile.js
Labels: bug, change request
