Repository refined-github/refined-github, pull requests merged in 2018-04, with the labels that each got.

#1240 Add hotkey to open selected notification in new tab
  readme.md
  source/content.js
  source/features/add-selection-in-new-tab.js
Labels: needs readme update

#1231 Privately remind users not to leave :+1: and :-1: as comments
  package.json
  source/content.css
Labels: cleanup

#1271 Use native reponav dropdown if available
  source/content.css
  source/features/more-dropdown.js
  source/libs/icons.js
Labels: enhancement, enterprise
