Repository refined-github/refined-github, pull requests merged in 2018-03, with the labels that each got.

#1117 Add `Commented` button in the main issues search tab
  readme.md
  source/content.css
  source/content.js
  source/features/add-commented-menu-item.js
  source/features/add-yours-menu-item.js
Labels: enhancement, needs readme update

#1115 Add link to default branch
  readme.md
  source/features/add-branch-buttons.js
  source/libs/icons.js
  source/libs/page-detect.js
Labels: enhancement

#1131 Buttons code cleanup
  source/content.css
  source/features/add-branch-buttons.js
  source/features/copy-file-path.js
  source/features/copy-file.js
  source/features/open-all-notifications.js
  source/libs/group-buttons.js
  source/libs/utils.js
Labels: cleanup, meta

#1107 Improve shortcut help
  readme.md
  source/content.css
  source/content.js
  source/features/add-diff-view-without-whitespace-option.js
  source/features/add-keyboard-shortcuts-to-comment-fields.js
  source/features/add-profile-hotkey.js
  source/features/add-releases-tab.js
  source/features/add-trending-menu-item.js
  source/features/improve-shortcut-help.js
  source/libs/page-detect.js
  test/page-detect.js
Labels: enhancement, needs readme update

#1014 Close out of view modals
  readme.md
  source/content.js
  source/features/close-out-of-view-modals.js
  source/features/more-dropdown.js
Labels: enhancement

#1133 Show latest tag in `latest release button`
  source/features/add-branch-buttons.js
Labels: enhancement, under discussion

#1136 Open updates prompt on install
  readme.md
  source/background.js
Labels: meta

#1042 Enable toggleAllThingsWithAlt on all commits
  readme.md
  source/content.js
  source/features/toggle-all-things-with-alt.js
Labels: enhancement

#1134 Highlight closing PRs in open issues and PRs
  readme.md
  source/content.css
  source/content.js
  source/features/highlight-closing-prs-in-open-issues.js
Labels: enhancement

#1145 Don't shorten links in code — again
  source/features/linkify-urls-in-code.js
Labels: bug

#1151 GifHub is non-functional abandonware
  readme.md
Labels: do not merge yet

#1148 Fix `userWasNotified` flag not being set
  source/background.js
Labels: Please! ♥, bug, firefox, meta

#1165 Highlight linked issue comment
  readme.md
  source/content.css
Labels: enhancement

#1104 Add GitHub Follow to the related extensions list
  readme.md
Labels: meta

#1178 Meta: enableFeature improvements
  source/content.js
  source/features/linkify-branch-refs.js
  source/libs/utils.js
Labels: meta

#1180 Fix user full names with accents
  source/content.css
Labels: bug

#1177 Meta: stop marking ajaxedPagesHandler as complex
  source/content.js
Labels: meta

#1183 Drop "dark modal backdrop"
  source/content.css
Labels: bug

#1204 Fix full name on GHE that requires auth
  source/features/show-names.js
Labels: bug, enterprise

#1149 Hide inactive deployments
  readme.md
  source/content.css
  source/content.js
  source/features/hide-inactive-deployments.js
Labels: enhancement

#1182 Highlight linked review comment
  source/content.css
Labels: enhancement

#1200 Extend status labels for PRs too
  source/background.js
  source/content.css
  source/content.js
  source/features/extend-status-labels.js
Labels: enhancement

#1168 Fix default branch buttons in some cases
  source/features/add-branch-buttons.js
Labels: bug

#1201 Fix adding patch and diff links to commit pages
  source/features/add-patch-diff-links.js
Labels: bug

#1156 Fix out-of-view modal closing on certain modals
  source/features/close-out-of-view-modals.js
Labels: bug

#1207 Fix adding toggle files button on repo root
  source/content.css
  source/features/add-toggle-files-button.js
Labels: bug

#1215 Support pulls/?user= URLs in sort-issues-by-update-time
  source/features/sort-issues-by-update-time.js
Labels: bug

#1175 Add global history.back handler
  source/content.js
  source/features/add-branch-buttons.js
  source/features/add-ci-link.js
  source/features/add-commented-menu-item.js
  source/features/add-diff-view-without-whitespace-option.js
  source/features/add-download-folder-button.js
  source/features/add-filter-comments-by-you.js
  source/features/add-gists-link-to-profile.js
  source/features/add-patch-diff-links.js
  source/features/add-quick-review-buttons.js
  source/features/add-releases-tab.js
  source/features/add-toggle-files-button.js
  source/features/add-yours-menu-item.js
  source/features/copy-on-y.js
  source/features/extend-status-labels.js
  source/features/highlight-closing-prs-in-open-issues.js
  source/features/make-discussion-sidebar-sticky.js
  source/features/mark-merge-commits-in-list.js
  source/features/more-dropdown.js
  source/features/open-all-notifications.js
  source/features/show-recently-pushed-branches.js
  source/features/upload-button.js
  source/features/wait-for-build.js
  source/libs/utils.js
Labels: meta

#1188 Display possibly related issues on the 'New Issue' page
  package.json
  source/content.css
  source/content.js
  source/features/display-issue-suggestions.js
  source/libs/api.js
  test/searchable-words.js
Labels: enhancement

#1216 Meta: Condense options
  package.json
  source/options.css
  source/options.html
  source/options.js
Labels: meta

#1140 WIP: Follow README style guide
  contributing.md
  readme.md
Labels: meta

#1232 Detect "Label" issue list as issue list
  source/content.js
  source/features/open-all-selected.js
  source/libs/page-detect.js
  test/page-detect.js
Labels: bug
