Repository refined-github/refined-github, pull requests merged in 2018-12, with the labels that each got.

#1532 Add way to exclude filters with a shortcut
  readme.md
  source/content.js
  source/features/add-filter-not-reviewed-by-you.js
  source/features/exclude-filter-shortcut.js
  source/features/sort-issues-by-update-time.js
  source/libs/icons.js
Labels: enhancement

#1648 Update discussion-sidebar z-index
  source/content.css
  source/features/make-discussion-sidebar-sticky.js
Labels: bug

#1650 Only mark relevant notifications as read
  source/features/mark-unread.js
Labels: bug

#1657 Drop `hide-issue-list-autocomplete`
  readme.md
  source/background.js
  source/content.js
  source/features/hide-issue-list-autocomplete.js
Labels: cleanup

#1659 Handle conversation updates for 5 old features
  source/content.js
  source/features/add-delete-fork-link.js
  source/features/add-time-machine-links-to-comments.js
  source/features/extend-status-labels.js
  source/features/op-labels.js
  source/features/show-names.js
Labels: bug

#1656 Fix mark unread bugs
  source/content.js
  source/features/mark-unread.js
  source/libs/synchronous-storage.js
Labels: bug

#1669 Move `show-names` to API v4
  source/features/show-names.js
  source/libs/utils.js
Labels: bug, enhancement

#1666 Fix latest tag link
  source/features/add-branch-buttons.js
  source/libs/utils.js
Labels: bug

#1678 Avoid long regexes in page-detect.js
  source/libs/page-detect.js
Labels: cleanup

#1612 Add "star/unstar repo" hotkey
  readme.md
  source/content.js
  source/features/add-star-repo-hotkey.js
Labels: enhancement

#1679 Improve API error handling
  source/features/add-branch-buttons.js
  source/features/show-names.js
  source/features/user-profile-follower-badge.js
  source/libs/api.js
Labels: bug, cleanup
