Repository refined-github/refined-github, pull requests merged in 2018-11, with the labels that each got.

#1402 Open all issues without selecting them
  source/background.js
  source/content.js
  source/features/add-commented-menu-item.js
  source/features/add-yours-menu-item.js
  source/features/batch-open-issues.js
  source/features/open-all-selected.js
  source/libs/page-detect.js
  test/page-detect.js
Labels: enhancement

#1624 Drop Markdown feature entirely
  package.json
  source/content.js
  source/features/copy-markdown.js
  test/copy-markdown.js
Labels: change request

#1638 Fix errors on repo search pages
  source/libs/page-detect.js
  test/page-detect.js
Labels: bug

#1623 Widen issue search when focused
  readme.md
  source/content.css
Labels: enhancement

#1640 Reaction avatars bug fixes
  package.json
  source/content.css
  source/features/reactions-avatars.js
  source/libs/events.js
  source/libs/on-new-comments.js
Labels: bug
