Repository refined-github/refined-github, pull requests merged in 2018-07, with the labels that each got.

#1339 Hide Releases tab if there are no releases
  source/features/add-releases-tab.js
Labels: enhancement

#1389 Copy Prev/Next buttons to bottom of commit page
  readme.md
  source/content.js
  source/features/prev-next-commit-buttons.js
Labels: enhancement, under discussion

#1418 Don't affect the auto-complete in the comment box
  source/features/add-keyboard-shortcuts-to-comment-fields.js
Labels: bug

#1360 Add link to swap branches on Compare
  readme.md
  source/content.js
  source/features/add-swap-branches-on-compare.js
Labels: enhancement, needs readme update

#1429 Linkify commit SHA on PR commit page
  readme.md
  source/content.js
  source/features/linkify-commit-sha.js
Labels: enhancement

#1428 Hide comments in fewer clicks
  readme.md
  source/content.js
  source/features/hide-comments-faster.js
  source/libs/events.js
Labels: enhancement
