Repository refined-github/refined-github, pull requests merged in 2019-02, with the labels that each got.

#1750 Move to TypeScript
  package-lock.json
  package.json
  source/background.ts
  source/content.ts
  source/features/add-co-authored-by.tsx
  source/features/branch-buttons.tsx
  source/features/bypass-checks.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/commented-menu-item.tsx
  source/features/comments-time-machine-links.tsx
  source/features/copy-file.tsx
  source/features/delete-fork-link.tsx
  source/features/extend-diff-expander.tsx
  source/features/fix-squash-and-merge-message.tsx
  source/features/fix-squash-and-merge-title.tsx
  source/features/focus-confirmation-buttons.tsx
  source/features/hide-comments-faster.tsx
  source/features/hide-empty-meta.tsx
  source/features/hide-own-stars.tsx
  source/features/hide-useless-comments.tsx
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/features/linkify-branch-refs.tsx
  source/features/make-discussion-sidebar-sticky.tsx
  source/features/mark-private-orgs.tsx
  source/features/mark-unread.tsx
  source/features/open-all-notifications.tsx
  source/features/preserve-whitespace-option-in-nav.tsx
  source/features/pull-request-hotkey.tsx
  source/features/quick-review-buttons.tsx
  source/features/selection-in-new-tab.tsx
  source/features/set-default-repositories-type-to-sources.tsx
  source/features/show-names.tsx
  source/features/show-recently-pushed-branches-on-more-pages.tsx
  source/features/sort-issues-by-update-time.tsx
  source/features/sort-milestones-by-closest-due-date.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/wait-for-build.tsx
  source/features/yours-menu-item.tsx
  source/globals.d.ts
  source/libs/api.ts
  source/libs/cache.ts
  source/libs/dom-utils.ts
  source/libs/domify.ts
  source/libs/features.tsx
  source/libs/get-default-branch.ts
  source/libs/get-text-nodes.ts
  source/libs/group-buttons.tsx
  source/libs/icons.js
  source/libs/indent-textarea.ts
  source/libs/on-new-comments.ts
  source/libs/page-detect.js
  source/libs/pr-ci-status.ts
  source/libs/simplified-element-observer.ts
  source/libs/utils.ts
  source/options.ts
  test/fixtures/globals.js
  test/page-detect.ts
  test/utils.ts
Labels: meta

#1753 Extend "ArrowUp to edit last comment"
  source/features/comment-fields-keyboard-shortcuts.tsx
Labels: enhancement

#1768 Simplify dom-chef usage
  contributing.md
  package-lock.json
  package.json
  source/features/batch-open-issues.tsx
  source/features/branch-buttons.tsx
  source/features/commented-menu-item.tsx
  source/features/comments-time-machine-links.tsx
  source/features/copy-file.tsx
  source/features/delete-fork-link.tsx
  source/features/diff-view-without-whitespace-option.tsx
  source/features/download-folder-button.tsx
  source/features/embed-gist-inline.tsx
  source/features/exclude-filter-shortcut.tsx
  source/features/extend-status-labels.tsx
  source/features/filter-comments-by-you.tsx
  source/features/hide-comments-faster.tsx
  source/features/hide-useless-comments.tsx
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/features/improve-shortcut-help.tsx
  source/features/jump-to-bottom-link.tsx
  source/features/linkify-branch-refs.tsx
  source/features/linkify-commit-sha.tsx
  source/features/mark-unread.tsx
  source/features/more-dropdown.tsx
  source/features/move-marketplace-link-to-profile-dropdown.tsx
  source/features/op-labels.tsx
  source/features/open-all-notifications.tsx
  source/features/patch-diff-links.tsx
  source/features/pr-branches.tsx
  source/features/profile-gists-link.tsx
  source/features/quick-review-buttons.tsx
  source/features/reactions-avatars.tsx
  source/features/releases-tab.tsx
  source/features/remove-projects-tab.tsx
  source/features/show-followers-you-know.tsx
  source/features/show-names.tsx
  source/features/show-recently-pushed-branches-on-more-pages.tsx
  source/features/show-user-top-repositories.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/toggle-files-button.tsx
  source/features/trending-menu-item.tsx
  source/features/upload-button.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-profile-follower-badge.tsx
  source/features/wait-for-build.tsx
  source/features/yours-menu-item.tsx
  source/libs/features.tsx
  source/libs/group-buttons.tsx
  source/libs/icons.tsx
Labels: meta

#1755 Preview hidden comments
  readme.md
  source/content.css
  source/content.ts
  source/features/preview-hidden-comments.tsx
  source/libs/on-new-comments.ts
Labels: enhancement

#1738 Split PRs and issues in the top search
  readme.md
  source/content.css
  source/content.ts
  source/features/split-issue-pr-search-results.tsx
Labels: enhancement

#1779 Meta: generate the JS files even when TS errors
  webpack.config.js
Labels: meta

#1777 Refresh the options view
  source/background.ts
  source/manifest.json
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#1758 Warn users when they attempt to create a PR from default branch
  readme.md
  source/content.ts
  source/features/warn-pr-from-master.tsx
Labels: enhancement, under discussion

#1772 Fix `preserve-whitespace-option-in-nav` and refactor with URLSearchParams
  source/features/diff-view-without-whitespace-option.tsx
  source/features/preserve-whitespace-option-in-nav.tsx
  source/features/sort-issues-by-update-time.tsx
  source/features/sort-milestones-by-closest-due-date.tsx
Labels: bug

#1763 Shrink tab padding when 7+ tabs exist on Profile
  source/content.css
Labels: bug

#1651 Update squash-and-merge title when PR title changes
  source/features/fix-squash-and-merge-title.tsx
Labels: enhancement

#1788 Hide the project tab in profiles and orgs
  readme.md
  source/features/remove-projects-tab.tsx
  source/libs/page-detect.ts
  test/page-detect.ts
Labels: bug, enhancement

#1789 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/new_feature.md
Labels: meta

#1782 Highlight own issues and PRs
  readme.md
  source/content.ts
  source/features/highlight-own-issues-and-prs.tsx
Labels: enhancement

#1781 Find a user’s most recently updated repositories in their profile
  readme.md
  source/features/show-user-top-repositories.tsx
Labels: bug, enhancement

#1803 Hide unnecessary webpack stats
  package-lock.json
  package.json
  webpack.config.js
Labels: meta

#1800 Restore `close-out-of-view-modals` feature
  source/features/close-out-of-view-modals.tsx
Labels: bug

#1770 Show warning when user attempts to disable PR edits
  readme.md
  source/content.ts
  source/features/warning-for-disallow-edits.tsx
Labels: enhancement, needs readme update
