Repository refined-github/refined-github, pull requests merged in 2019-05, with the labels that each got.

#2002 Use and improve `fetch-dom`
  source/features/bypass-checks.tsx
  source/features/ci-link.tsx
  source/features/show-followers-you-know.tsx
  source/features/view-markdown-source.tsx
  source/libs/fetch-dom.ts
Labels: meta

#1997 Avoid duplicate releases
  .travis.yml
  package.json
Labels: meta

#1932 Add `default-to-rich-diff` feature
  .github/CODEOWNERS
  readme.md
  source/content.ts
  source/features/default-to-rich-diff.tsx
Labels: enhancement

#2000 Add `link-to-file-in-file-history` feature
  .github/CODEOWNERS
  readme.md
  source/content.ts
  source/features/link-to-file-in-file-history.tsx
Labels: enhancement

#2011 Add `clean-sidebar` feature
  readme.md
  source/content.ts
  source/features/clean-sidebar.css
  source/features/clean-sidebar.tsx
  source/features/hide-tips.css
Labels: enhancement

#1998 Add `tag-changelog-link` feature
  .github/CODEOWNERS
  package-lock.json
  package.json
  readme.md
  source/content.ts
  source/features/tag-changelog-link.tsx
  source/libs/page-detect.ts
  source/libs/utils.ts
  test/page-detect.ts
  test/utils.ts
Labels: enhancement

#2012 In discussions, always link the "Closed" label to the closing event
  source/features/extend-status-labels.tsx
Labels: enhancement

#1928 Apply `set-default-repositories-type-to-sources` to organizations too
  readme.md
  source/features/set-default-repositories-type-to-sources.tsx
Labels: enhancement

#2025 Hide `link-to-file-in-file-history` where not needed
  source/features/link-to-file-in-file-history.tsx
Labels: bug

#2029 Meta: Make issue templates more scannable
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: meta

#2038 Fix `hide-empty-meta`
  source/features/hide-empty-meta.tsx
Labels: bug

#2023 Fix `wait-for-build`
  source/features/wait-for-build.tsx
  source/libs/pr-ci-status.ts
Labels: bug

#1950 Add `update-pr-from-base-branch` feature
  readme.md
  source/content.ts
  source/features/update-pr-from-base-branch.tsx
  source/features/user-profile-follower-badge.tsx
  source/libs/api.ts
  source/libs/icons.tsx
  source/libs/simplified-element-observer.ts
Labels: enhancement

#2019 Reliable merge box handlers
  package-lock.json
  package.json
  source/features/add-co-authored-by.tsx
  source/features/fit-textareas.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/wait-for-build.tsx
  source/libs/on-pr-merge-panel-open.ts
Labels: bug, cleanup, meta

#2036 Remove `scroll-to-top-on-collapse` feature
  source/background.ts
  source/content.ts
  source/features/scroll-to-top-on-collapse.tsx
Labels: cleanup

#2028 Add `open-issue-to-latest-comment` feature
  .github/CODEOWNERS
  readme.md
  source/content.ts
  source/features/open-issue-to-latest-comment.tsx
Labels: enhancement

#2053 Add `sort-issues-by-update-time` to `filter-comments-by-you`
  source/content.ts
Labels: bug

#2061 Fix console errors
  source/libs/fetch-dom.ts
  source/libs/page-detect.ts
  test/page-detect.ts
Labels: bug

#2062 Improve clickability of reaction buttons in Firefox
  source/features/reactions-avatars.tsx
Labels: bug, firefox

#2068 Drop `upload-button` feature and restore hiding of upload bar
  source/background.ts
  source/content.css
  source/content.ts
  source/features/clean-rich-text-editor.css
  source/features/upload-button.tsx
Labels: bug

#1989 Add `indented-code-wrapping` feature
  .github/CODEOWNERS
  source/content.ts
  source/features/indented-code-wrapping.css
  source/features/indented-code-wrapping.tsx
  source/features/raw-file-link.tsx
  source/libs/on-pr-file-load.tsx
Labels: enhancement

#2075 Fix formatting in `pull_request_template.md`
  .github/pull_request_template.md
Labels: meta

#2086 Show drag and drop area on release page
  source/features/clean-rich-text-editor.css
Labels: bug

#2066 Restore and extend url linkifier
  package-lock.json
  package.json
  source/features/linkify-issues-in-titles.tsx
  source/features/linkify-urls-in-code.tsx
  source/libs/page-detect.ts
Labels: bug

#1780 Meta: disable features with a click in the options
  contributing.md
  package-lock.json
  source/background.ts
  source/features/collapsible-content-button.tsx
  source/features/download-folder-button.tsx
  source/features/extend-status-labels.tsx
  source/features/fit-textareas.tsx
  source/features/parse-backticks.tsx
  source/features/raw-file-link.tsx
  source/features/recently-pushed-branches-enhancements.tsx
  source/features/releases-tab.tsx
  source/features/shorten-links.tsx
  source/features/show-user-top-repositories.tsx
  source/features/sync-pr-commit-title.tsx
  source/globals.d.ts
  source/libs/api.ts
  source/libs/features.tsx
  source/libs/get-text-nodes.ts
  source/libs/linkify-text-nodes.ts
  source/libs/parse-backticks.tsx
  source/manifest.json
  source/options-storage.ts
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#2067 Show only GH Enterprise notifications on GH Enterprise
  source/features/mark-unread.tsx
Labels: bug
