Repository refined-github/refined-github, pull requests merged in 2019-11, with the labels that each got.

#2310 Add `conflict-marker` feature
  readme.md
  source/content.ts
  source/features/conflict-marker.tsx
  source/libs/page-detect.ts
Labels: enhancement

#2511 Add explanatory tooltips to `global-discussion-list-filters`
  source/features/global-discussion-list-filters.tsx
Labels: enhancement

#2470 Hide the correct editor buttons on the New Issue page
  source/features/clean-rich-text-editor.css
Labels: bug

#2505 Add `html-preview-link` feature
  readme.md
  source/content.ts
  source/features/html-preview-link.tsx
  source/libs/utils.ts
Labels: enhancement

#2484 Add draft PR filter in `pr-filters`
  .github/CODEOWNERS
  readme.md
  source/content.css
  source/content.ts
  source/features/filter-pr-by-build-status.tsx
  source/features/pr-filters.tsx
  source/options-storage.ts
Labels: enhancement

#2516 Move disabled features to the top of the list (Options page)
  source/options.tsx
Labels: meta

#2512 Tests all URLs in `page-detect` against each other
  source/libs/page-detect.ts
  test/page-detect.ts
Labels: meta

#2519 Allow PR merge-only bots in `dim-bots`
  source/features/dim-bots.tsx
Labels: bug

#2514 Meta: Add feature option search
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#2528 Use API to fetch releases count in `releases-tab`
  source/features/releases-tab.tsx
Labels: enhancement

#2525 Fix `update-pr-from-base-branch` feature
  source/features/update-pr-from-base-branch.tsx
  source/features/user-profile-follower-badge.tsx
  source/libs/api.ts
Labels: bug

#2540 Cleanup `html-preview-link` feature page detection
  source/features/html-preview-link.tsx
  source/libs/utils.ts
Labels: bug

#2524 Split testing jobs in GitHub Actions
  .github/workflows/test.yml
Labels: meta

#2529 Add `fix-view-file-link-in-pr` feature
  readme.md
  source/content.ts
  source/features/fix-view-file-link-in-pr.tsx
  source/features/raw-file-link.tsx
Labels: enhancement, needs readme update

#2513 Add `linkify-labels-on-dashboard` feature
  readme.md
  source/content.ts
  source/features/linkify-labels-on-dashboard.tsx
Labels: enhancement

#2544 Add `linkify-user-location` feature
  readme.md
  source/content.ts
  source/features/linkify-user-location.tsx
Labels: enhancement

#2553 Restore CLI instructions for checking out PRs
  source/features/clean-mergeability-box.css
Labels: change request

#2559 Avoid duplicate view switcher in `faster-pr-diff-options`
  source/features/faster-pr-diff-options.tsx
Labels: bug

#2560 Add `repo-age` feature
  readme.md
  source/content.ts
  source/features/repo-age.tsx
  source/features/repo-stats-spacing.css
  source/globals.d.ts
  source/libs/icons.tsx
  source/libs/time-ago.tsx
Labels: enhancement

#2551 Add `emphasize-draft-pr-label` feature
  source/content.ts
  source/features/emphasize-draft-pr-label.css
Labels: enhancement

#2549 Add `user-local-time` feature
  readme.md
  source/content.ts
  source/features/user-local-time.tsx
  source/globals.d.ts
  source/libs/api.ts
Labels: enhancement

#2545 Update `mem` to fix its types
  package-lock.json
  package.json
  source/features/hidden-review-comments-indicator.tsx
  source/globals.d.ts
  source/libs/api.ts
  source/libs/fetch-dom.ts
Labels: meta
