Repository refined-github/refined-github, pull requests merged in 2019-04, with the labels that each got.

#1933 Don't clutter the global search bar in the global Pull Requests page
  source/features/sort-issues-by-update-time.tsx
  source/libs/dom-utils.ts
Labels: bug

#1926 Various fixes for `global-discussion-list-filters` feature
  source/features/global-discussion-list-filters.tsx
Labels: bug

#1939 Add `edit-files-faster` feature
  readme.md
  source/content.css
  source/content.ts
  source/features/edit-files-faster.tsx
  source/libs/features.tsx
  source/libs/on-file-list-update.ts
Labels: enhancement

#1904 Add dropdown to filter PR by build status success, failure and pending
  readme.md
  source/content.css
  source/content.ts
  source/features/filter-pr-by-build-status.tsx
  source/libs/icons.tsx
Labels: enhancement

#1942 Fix `pr-branches` and `remove-projects-tab` features
  source/features/branch-buttons.tsx
  source/features/pr-branches.tsx
  source/features/remove-projects-tab.tsx
Labels: bug

#1863 Add timemachine links to all repo links
  readme.md
  source/content.css
  source/features/comments-time-machine-links.tsx
  source/libs/icons.tsx
Labels: enhancement

#1947 Meta: Remove most TypeScript `any` types
  source/features/add-co-authored-by.tsx
  source/features/follow-file-renames.tsx
  source/features/reactions-avatars.tsx
  source/globals.d.ts
  source/resolve-conflicts.ts
Labels: meta

#1948 Drop some TypeScript type assertions
  source/features/copy-file.tsx
  source/features/esc-to-deselect-line.tsx
  source/features/hide-own-stars.tsx
  source/features/hide-useless-comments.tsx
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/features/mark-unread.tsx
  source/features/open-all-notifications.tsx
  source/features/scroll-to-top-on-collapse.tsx
  source/features/upload-button.tsx
  source/features/wait-for-build.tsx
  source/libs/utils.ts
Labels: meta

#1896 Add `tags-dropdown` feature
  readme.md
  source/content.css
  source/content.ts
  source/features/tags-dropdown.tsx
  source/globals.d.ts
  source/libs/icons.tsx
Labels: enhancement

#1929 Add `remove-checks-tab` feature
  readme.md
  source/content.ts
  source/features/remove-checks-tab.tsx
Labels: enhancement

#1952 Loosen commit message length limits
  source/content.css
Labels: under discussion

#1909 Fix recently-pushed-branches once and for all
  readme.md
  source/background.ts
  source/content.css
  source/content.ts
  source/features/recently-pushed-branches-enhancements.tsx
Labels: bug, enhancement

#1960 Replace `fix-squash-and-merge` with `sync-pr-commit-title`
  package-lock.json
  package.json
  readme.md
  source/background.ts
  source/content.ts
  source/features/fix-squash-and-merge-title.tsx
  source/features/sync-pr-commit-title.tsx
  source/globals.d.ts
Labels: enhancement

#1955 Allow marking draft PRs as unread
  source/content.css
  source/features/mark-unread.tsx
Labels: bug

#1930 web-ext integration
  contributing.md
  package.json
Labels: meta

#1924 Add `raw-file-link` feature
  readme.md
  source/content.ts
  source/features/raw-file-link.tsx
Labels: enhancement

#1962 TypeScript Cleanup - Bye, bye TODOs
  package-lock.json
  package.json
  source/features/follow-file-renames.tsx
  source/features/improve-shortcut-help.tsx
  source/globals.d.ts
  source/libs/get-default-branch.ts
Labels: meta

#1983 Meta: split CSS by feature
  package-lock.json
  package.json
  source/content.css
  source/content.ts
  source/features/hide-watch-and-fork-count.css
  source/features/hide-watch-and-fork-count.tsx
  source/features/scrollable-code-and-blockquote.css
  source/manifest.json
  source/options.html
  webpack.config.js
Labels: meta

#1966 Hide duplicate "Edit comment" item in dropdown
  source/features/comments-time-machine-links.tsx
  source/features/edit-comments-faster.tsx
Labels: bug

#1976 Publish a git tag for every Refined GitHub release
  .travis.yml
  package.json
Labels: meta

#1980 Add `hide-disabled-milestone-sorter` feature
  readme.md
  source/content.ts
  source/features/hide-disabled-milestone-sorter.tsx
Labels: enhancement
