Repository refined-github/refined-github, pull requests merged in 2019-01, with the labels that each got.

#1696 Improve error logging
  source/libs/utils.js
Labels: meta

#1698 Drop infinite-scroll feature on user profile
  readme.md
  source/content.js
  source/features/infinite-scroll.js
Labels: bug

#1700 Enable `batch-open-issues` on global /pulls and /issues pages
  source/features/batch-open-issues.js
Labels: bug

#1711 Always keep projects tab when current user is repo owner
  source/features/remove-projects-tab.js
Labels: bug

#1715 Improve dropdown expansion animation
  source/content.css
Labels: enhancement

#1712 Fix top position for sticky discussion-sidebar
  source/content.css
  source/features/make-discussion-sidebar-sticky.js
Labels: bug

#1693 Bypass the checks tab for all PR validation types
  readme.md
  source/background.js
  source/content.js
  source/features/bypass-checks.js
Labels: enhancement

#1720 Drop `add` from feature names
  source/background.js
  source/content.js
  source/features/branch-buttons.js
  source/features/ci-link.js
  source/features/comment-fields-keyboard-shortcuts.js
  source/features/commented-menu-item.js
  source/features/comments-time-machine-links.js
  source/features/create-release-shortcut.js
  source/features/delete-fork-link.js
  source/features/diff-view-without-whitespace-option.js
  source/features/download-folder-button.js
  source/features/emojis-title.js
  source/features/filter-comments-by-you.js
  source/features/jump-to-bottom-link.js
  source/features/milestone-navigation.js
  source/features/patch-diff-links.js
  source/features/profile-gists-link.js
  source/features/profile-hotkey.js
  source/features/pull-request-hotkey.js
  source/features/quick-review-buttons.js
  source/features/releases-tab.js
  source/features/selection-in-new-tab.js
  source/features/star-repo-hotkey.js
  source/features/swap-branches-on-compare.js
  source/features/toggle-files-button.js
  source/features/trending-menu-item.js
  source/features/yours-menu-item.js
Labels: meta

#1725 Drop unused code
  source/libs/utils.js
Labels: meta

#1717 Fix hide-own-stars for new responsive dashbord
  source/features/hide-own-stars.js
Labels: bug

#1641 Show significant branches on PRs list
  package.json
  readme.md
  source/content.js
  source/features/pr-branches.js
  source/libs/page-detect.js
  test/page-detect.js
Labels: enhancement

#1737 Move some functions into and out of utils.js
  source/features/branch-buttons.tsx
  source/features/ci-link.tsx
  source/features/comments-time-machine-links.tsx
  source/features/delete-fork-link.tsx
  source/features/extend-status-labels.tsx
  source/features/filter-comments-by-you.tsx
  source/features/hide-own-stars.tsx
  source/features/linkify-branch-refs.tsx
  source/features/linkify-commit-sha.tsx
  source/features/linkify-urls-in-code.tsx
  source/features/mark-unread.tsx
  source/features/milestone-navigation.tsx
  source/features/more-dropdown.tsx
  source/features/pr-branches.tsx
  source/features/profile-gists-link.tsx
  source/features/releases-tab.tsx
  source/features/remove-projects-tab.tsx
  source/features/remove-upload-files-button.tsx
  source/features/show-followers-you-know.tsx
  source/features/show-recently-pushed-branches-on-more-pages.tsx
  source/features/show-user-top-repositories.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/trending-menu-item.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-profile-follower-badge.tsx
  source/libs/dom-utils.js
  source/libs/features.tsx
  source/libs/get-default-branch.js
  source/libs/group-buttons.js
  source/libs/page-detect.js
  source/libs/utils.js
  test/page-detect.js
  test/utils.js
Labels: meta
