Repository refined-github/refined-github, pull requests merged in 2019-12, with the labels that each got.

#2584 Disable `linkify-user-location` on own editable profile
  source/features/linkify-user-location.tsx
Labels: bug

#2583 Fix `resolve-conflict` feature
  source/resolve-conflicts.ts
Labels: bug

#2578 Simplify cache usage (as a memoized function)
  package-lock.json
  package.json
  source/features/clean-issue-filters.tsx
  source/features/list-prs-for-file.tsx
  source/features/releases-tab.tsx
  source/features/user-local-time.tsx
  source/libs/get-default-branch.ts
Labels: meta

#2585 Improve spacing in discussion lists and avoid jump
  source/content.css
  source/features/conflict-marker.css
  source/features/conflict-marker.tsx
  source/features/pr-branches.tsx
Labels: enhancement

#2595 Add support for namespaced branches to`fix-view-file-link-in-pr`
  source/features/fix-view-file-link-in-pr.tsx
Labels: bug

#2592 Bump dependencies
  package-lock.json
  package.json
  source/libs/api.ts
Labels: bug

#2587 Improve PR detection in all discussion lists
  source/features/conflict-marker.tsx
  source/features/dim-bots.tsx
  source/features/pr-branches.tsx
  source/libs/page-detect.ts
Labels: bug, enhancement

#2539 Fix console error caused by `embed-gist-via-iframe`
  source/features/embed-gist-via-iframe.tsx
  source/libs/page-detect.ts
Labels: bug

#2599 Meta: Reduce Option types by moving its generation to webpack
  package.json
  source/globals.d.ts
  source/options-storage.ts
  webpack.config.ts
Labels: meta

#2600 Meta: Minor improvements thanks to new JS operators
  package-lock.json
  package.json
  source/features/faster-pr-diff-options.tsx
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/libs/features.tsx
  source/libs/get-default-branch.ts
  source/options.html
  source/options.tsx
  webpack.config.ts
Labels: meta

#2605 Avoid FOUC on some features
  source/features/forked-to.tsx
  source/features/mark-unread.tsx
  source/features/more-dropdown.tsx
  source/features/releases-tab.tsx
  source/features/sticky-discussion-sidebar.tsx
  source/libs/features.tsx
Labels: meta, under discussion

#2607 `repo-age` improvements
  package-lock.json
  package.json
  source/features/repo-age.tsx
  source/libs/time-ago.tsx
Labels: enhancement

#2556 Add `quick-mention` feature
  readme.md
  source/content.ts
  source/features/quick-mention.css
  source/features/quick-mention.tsx
  source/libs/icons.tsx
Labels: enhancement, under discussion

#2610 Use `@primer/octicons` package instead of curating icons.tsx
  octicon-svg-loader.ts
  package-lock.json
  package.json
  source/features/add-tag-to-commits.tsx
  source/features/branch-buttons.tsx
  source/features/collapsible-content-button.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conflict-marker.tsx
  source/features/edit-comments-faster.tsx
  source/features/edit-files-faster.tsx
  source/features/edit-readme.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/forked-to.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/highest-rated-comment.tsx
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/features/link-to-file-in-file-history.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-private-orgs.tsx
  source/features/mark-unread.tsx
  source/features/minimize-upload-bar.tsx
  source/features/more-dropdown.tsx
  source/features/open-all-notifications.tsx
  source/features/pr-branches.tsx
  source/features/pr-filters.tsx
  source/features/quick-mention.tsx
  source/features/release-download-count.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-dropdown.tsx
  source/features/toggle-files-button.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/user-local-time.tsx
  source/features/view-markdown-source.tsx
  source/features/wait-for-build.tsx
  source/globals.d.ts
  source/libs/icons.tsx
  tsconfig.json
  webpack.config.ts
Labels: meta

#2598 Fix `z-index` bug caused by `sticky-discussion-sidebar`
  source/features/sticky-discussion-sidebar.css
Labels: bug

#2620 Make `quick-mention` button ever-so-slightly more visible
  source/features/quick-mention.css
Labels: change request

#2629 Restore `update-pr-from-base-branch` in Draft PRs
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#2627 Enable `shift-tab` to unindent comment fields
  package-lock.json
  package.json
  readme.md
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/tab-to-indent.tsx
  source/features/view-markdown-source.tsx
  source/libs/blur-field-accessibly.ts
  source/options.tsx
Labels: enhancement

#2626 Small meta changes
  package-lock.json
  package.json
  source/features/add-co-authored-by.tsx
  source/features/add-tag-to-commits.tsx
  source/features/batch-open-issues.tsx
  source/features/ci-link.tsx
  source/features/clean-issue-filters.tsx
  source/features/cycle-lists-with-keyboard-shortcuts.tsx
  source/features/embed-gist-inline.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/forked-to.tsx
  source/features/hidden-review-comments-indicator.css
  source/features/hide-useless-comments.tsx
  source/features/highest-rated-comment.tsx
  source/features/limit-commit-title-length.tsx
  source/features/linkify-branch-references.tsx
  source/features/linkify-labels-on-dashboard.tsx
  source/features/linkify-user-location.tsx
  source/features/mark-private-orgs.tsx
  source/features/open-all-notifications.tsx
  source/features/pr-branches.tsx
  source/features/pr-filters.tsx
  source/features/quick-mention.css
  source/features/reactions-avatars.tsx
  source/features/release-download-count.tsx
  source/features/revert-file.tsx
  source/features/sort-issues-by-update-time.tsx
  source/features/toggle-everything-with-alt.tsx
  source/features/update-pr-from-base-branch.tsx
  source/libs/dom-formatters.ts
  source/libs/fetch-dom.ts
  source/libs/on-updatable-content-update.ts
  source/libs/page-detect.ts
  source/libs/post-form.ts
  source/libs/utils.ts
  test/utils.ts
Labels: meta

#2636 Include user handle in `quick-mention`’s tooltip
  source/features/quick-mention.tsx
Labels: enhancement

#2628 Restore `view-markdown-source` buttons
  source/features/view-markdown-source.tsx
Labels: bug

#2640 Meta: Add lockfile security check to CI
  .github/workflows/test.yml
Labels: meta
