Repository refined-github/refined-github, pull requests merged in 2019-08, with the labels that each got.

#2282 Drop `delete-fork-button` feature
  source/content.ts
  source/features/delete-fork-button.css
Labels: under discussion

#2292 Fix console error in `show-names`
  source/features/show-names.tsx
  source/libs/features.tsx
Labels: bug

#2294 Fix `sticky-discussion-sidebar`
  readme.md
  source/content.ts
  source/features/make-discussion-sidebar-sticky.css
  source/features/sticky-discussion-sidebar.css
  source/features/sticky-discussion-sidebar.tsx
  source/options-storage.ts
Labels: bug

#2295 Restore `sticky-discussion-list-toolbar` feature
  readme.md
  source/content.ts
  source/features/sticky-discussion-list-toolbar.css
Labels: bug

#2146 Add `minimize-user-comments` feature
  package-lock.json
  package.json
  readme.md
  source/content.ts
  source/features/minimize-user-comments.tsx
  source/globals.d.ts
  source/libs/anchor-scroll.ts
  source/options-storage.ts
  source/options.css
  source/options.html
  source/options.tsx
Labels: enhancement

#2297 Fix `minimize-user-comments`
  source/features/minimize-user-comments.tsx
Labels: bug

#2293 Add per-domain options (and GitHub token)
  package-lock.json
  package.json
  source/options-storage.ts
  source/options.tsx
Labels: enterprise

#2301 Add `hide-zero-packages` feature
  readme.md
  source/content.ts
  source/features/hide-zero-packages.tsx
Labels: enhancement

#2307 Fix default branch in private repo
  source/libs/utils.ts
Labels: bug

#2302 Meta: Make `__featuresList__` & `__featuresInfo__` dynamic
  webpack.config.ts
Labels: meta

#2315 Fix branch button alignment
  source/features/branch-buttons.css
  source/features/branch-buttons.tsx
Labels: bug

#2314 Fix `sticky-discussion-sidebar`
  source/features/sticky-discussion-sidebar.css
  source/features/sticky-discussion-sidebar.tsx
Labels: bug

#1774 Show checkmark where already enabled + let the user disable it
  package-lock.json
  package.json
  source/background.ts
Labels: enterprise, meta

#2182 Add `revert-file` feature
  readme.md
  source/content.ts
  source/features/raw-file-link.tsx
  source/features/revert-file.tsx
  source/globals.d.ts
  source/libs/api.ts
  source/libs/post-form.ts
Labels: enhancement

#2319 Add PR Monitor to related projects
  readme.md
Labels: meta

#2324 Avoid adding a duplicate “Update Branch” button
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#2337 Fix `warning-for-disallow-edits`
  source/features/warning-for-disallow-edits.tsx
Labels: bug

#2270 Show counts when dropdowns are open in `hide-watch-and-fork-count`
  source/features/hide-watch-and-fork-count.css
Labels: enhancement, under discussion

#2340 Fix sidebar issues caused by `sticky-discussion-sidebar`
  source/features/sticky-discussion-sidebar.css
Labels: bug

#2341 Fix `sync-pr-commit-title` to update the PR title
  source/features/sync-pr-commit-title.tsx
Labels: bug

#2336 Fix `mark-unread` button injection
  source/features/mark-unread.tsx
  source/libs/on-updatable-content-update.ts
Labels: bug

#2320 Add `hidden-review-comments-indicator` feature
  readme.md
  source/content.ts
  source/features/hidden-review-comments-indicator.css
  source/features/hidden-review-comments-indicator.tsx
  source/globals.d.ts
  source/libs/icons.tsx
Labels: enhancement

#2344 Fix `clean-sidebar` on sidebar updates
  source/features/clean-sidebar.tsx
Labels: bug

#2343 Fix `batch-open-issues` on glboal discussion list
  source/features/batch-open-issues.tsx
Labels: bug

#2332 Fix header alignment on Releases and Tags pages
  .github/CODEOWNERS
  source/features/widen-search-field.css
Labels: bug

#2375 Hide unnecessary tip on comment field
  readme.md
  source/content.ts
  source/features/clean-rich-text-editor.css
  source/features/clean-rich-text-editor.ts
Labels: enhancement

#2391 Update dependencies and lint
  package-lock.json
  package.json
  size-plugin.json
  source/background.ts
  source/features/follow-file-renames.tsx
  source/features/forked-to.tsx
  source/features/hide-useless-comments.tsx
  source/features/link-to-file-in-file-history.tsx
  source/features/linkify-urls-in-code.tsx
  source/features/minimize-upload-bar.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/revert-file.tsx
  source/features/show-names.tsx
  source/features/sticky-discussion-sidebar.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/tags-dropdown.tsx
  source/features/view-markdown-source.tsx
  source/globals.d.ts
  source/libs/features.tsx
  source/libs/get-default-branch.ts
  source/libs/get-text-nodes.ts
  source/libs/on-new-comments.ts
  source/libs/post-form.ts
  source/options-storage.ts
  source/options.tsx
  webpack.config.ts
Labels: meta
