Repository refined-github/refined-github, pull requests merged in 2019-03, with the labels that each got.

#1809 Restore toolbar button-hiding feature
  package.json
  readme.md
  source/content.css
Labels: bug

#1804 Add collapsible content button
  readme.md
  source/content.ts
  source/features/collapsible-content-button.tsx
  source/libs/icons.tsx
Labels: enhancement

#1756 Remove unused permission
  source/manifest.json
Labels: meta

#1834 Replace `delegate` with `delegate-it`
  package-lock.json
  package.json
  source/features/add-co-authored-by.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/collapsible-content-button.tsx
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/extend-diff-expander.tsx
  source/features/hide-comments-faster.tsx
  source/features/mark-unread.tsx
  source/features/scroll-to-top-on-collapse.tsx
  source/features/toggle-files-button.tsx
  source/features/upload-button.tsx
  source/features/wait-for-build.tsx
Labels: meta

#1833 Reduce issue/PR filter button padding when batch-open-issues is active
  source/content.css
Labels: bug

#1835 Meta: Restore error reporting in build
  webpack.config.js
Labels: meta

#1823 Cleanup CSS (first 200 lines)
  package.json
  source/content.css
Labels: cleanup

#1820 Drop counters for Watch and Forks
  readme.md
  source/content.css
Labels: enhancement

#1146 Make tall code blocks scrollable
  readme.md
  source/content.css
Labels: enhancement

#1839 Fix console errors for a few features
  source/features/comments-time-machine-links.tsx
  source/features/warning-for-disallow-edits.tsx
  source/libs/page-detect.ts
Labels: bug

#1837 Fix 404 pages detection and support
  source/features/useful-not-found-page.tsx
  source/libs/page-detect.ts
  test/page-detect.ts
Labels: bug

#1832 Also show closing commit in issue header
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/libs/icons.tsx
Labels: enhancement

#1824 Update dashboard style
  source/content.css
Labels: cleanup

#1853 Meta: Simplify `select` global declaration
  source/content.ts
Labels: meta

#1854 Update `trending-menu-item`
  source/features/trending-menu-item.tsx
Labels: bug

#1860 Change dashboard style again
  readme.md
  source/content.css
Labels: cleanup, enhancement

#1851 Always show `Delete fork` button
  readme.md
  source/content.css
Labels: enhancement

#1858 Let users disable `hide-watch-and-fork-count`
  source/content.css
  source/content.ts
  source/features/hide-watch-and-fork-count.tsx
Labels: enhancement

#1861 Make `hide-useless-newsfeed-events` more reliable
  source/content.css
  source/features/hide-useless-newsfeed-events.tsx
Labels: bug

#1876 Restore `branch-buttons` feature
  source/content.css
  source/features/branch-buttons.tsx
Labels: bug

#1877 Restore `copy-file` feature
  source/features/copy-file.tsx
Labels: bug

#1874 Meta: Run tests in parallel
  package.json
Labels: meta

#1879 Drop `jump-to-bottom` feature
  readme.md
  source/content.css
  source/content.ts
  source/features/jump-to-bottom-link.tsx
Labels: cleanup

#1880 Add `edit-comments-faster` feature
  readme.md
  source/content.ts
  source/features/edit-comments-faster.tsx
Labels: enhancement

#1878 Add `esc-to-deselect-line` feature
  readme.md
  source/content.ts
  source/features/esc-to-deselect-line.tsx
Labels: enhancement

#1883 Cleanup and small fixes
  package-lock.json
  package.json
  readme.md
  source/background.ts
  source/content.css
  source/content.ts
  source/features/batch-open-issues.tsx
  source/features/collapsible-content-button.tsx
  source/features/commented-menu-item.tsx
  source/features/comments-time-machine-links.tsx
  source/features/edit-comments-faster.tsx
  source/features/embed-gist-inline.tsx
  source/features/extend-diff-expander.tsx
  source/features/filter-comments-by-you.tsx
  source/features/fix-squash-and-merge-message.tsx
  source/features/fix-squash-and-merge-title.tsx
  source/features/global-discussion-list-filters.tsx
  source/features/hide-comments-faster.tsx
  source/features/hide-issue-list-autocomplete.tsx
  source/features/hide-readme-header.tsx
  source/features/highlight-closing-prs-in-open-issues.tsx
  source/features/highlight-own-issues-and-prs.tsx
  source/features/make-discussion-sidebar-sticky.tsx
  source/features/mark-unread.tsx
  source/features/preview-hidden-comments.tsx
  source/features/reactions-avatars.tsx
  source/features/show-names.tsx
  source/features/show-recently-pushed-branches-on-more-pages.tsx
  source/features/upload-button.tsx
  source/features/wait-for-build.tsx
  source/features/yours-menu-item.tsx
  source/libs/page-detect.ts
  test/page-detect.ts
Labels: bug, cleanup

#1873 Add `view-markdown-source` feature
  readme.md
  source/content.css
  source/content.ts
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/view-markdown-source.tsx
  source/libs/fetch-dom.ts
  source/libs/icons.tsx
Labels: enhancement

#1872 Add `parse-backticks` feature
  readme.md
  source/content.ts
  source/features/parse-backticks.tsx
Labels: enhancement

#1871 Expand text areas without limits
  package.json
  readme.md
  source/content.css
  source/content.ts
  source/features/fit-textareas.tsx
Labels: enhancement

#1825 Add Commits and Branches links to More dropdown
  readme.md
  source/content.css
  source/features/more-dropdown.tsx
  source/libs/icons.tsx
Labels: enhancement

#1866 Add feature `remove-diff-signs`
  readme.md
  source/content.css
  source/content.ts
  source/features/remove-diff-signs.tsx
Labels: enhancement

#1870 Add feature `follow-file-renames`
  readme.md
  source/content.ts
  source/features/follow-file-renames.tsx
Labels: enhancement

#1882 Resolve conflicts in a click
  package-lock.json
  package.json
  readme.md
  source/content.css
  source/content.ts
  source/features/resolve-conflicts.tsx
  source/libs/page-detect.ts
  source/manifest.json
  source/resolve-conflicts.ts
  webpack.config.js
Labels: enhancement
