Repository refined-github/refined-github, pull requests merged in 2020-12, with the labels that each got.

#3787 Meta: Update Sourcegraph Readme link
  readme.md
Labels: meta

#3801 Fix a couple of issues with GitHub Dark mode
  source/features/clean-dashboard.css
  source/features/reactions-avatars.css
Labels: bug

#3794 Fix `new-repo-disable-projects-and-wiki` feature
  source/github-helpers/api.ts
Labels: bug

#3796 Fix `more-dropdown`
  source/features/more-dropdown.tsx
Labels: bug

#3815 Allow `clean-pinned-issues` to be disabled
  source/features/clean-pinned-issues.css
  source/features/clean-pinned-issues.tsx
  source/refined-github.ts
Labels: enhancement

#3812 Fix `parse-backticks` in PR commit list and Compare page
  source/features/parse-backticks.tsx
Labels: bug

#3795 Expand `quick-fork-deletion` to empty repos
  readme.md
  source/features/quick-repo-deletion.css
  source/features/quick-repo-deletion.tsx
  source/refined-github.ts
Labels: enhancement

#3828 `table-input` can be closed by clicking anywhere else
  source/features/table-input.tsx
Labels: bug

#3797 Enable `pr-easy-toggle-files` on every commit page
  readme.md
  source/features/easy-toggle-files.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: enhancement

#3826 Meta: Standardize registration of CSS-only features
  source/features/align-issue-labels.tsx
  source/features/clean-dashboard.ts
  source/features/clean-pinned-issues.css
  source/features/clean-pinned-issues.tsx
  source/features/hide-useless-newsfeed-events.css
  source/features/hide-useless-newsfeed-events.tsx
  source/features/hide-watch-and-fork-count.tsx
  source/features/index.tsx
  source/features/minimize-upload-bar.tsx
  source/features/monospace-textareas.tsx
  source/features/remove-diff-signs.tsx
  source/refined-github.ts
Labels: meta

#3806 Further improvements to Dark mode
  source/features/clean-dashboard.css
  source/features/conflict-marker.css
  source/features/emphasize-draft-pr-label.css
  source/features/highlight-collaborators-and-own-conversations.css
  source/features/parse-backticks.css
  source/features/reactions-avatars.css
  source/features/resolve-conflicts.css
  source/features/show-whitespace.css
  source/features/split-issue-pr-search-results.css
  source/features/table-input.css
  source/refined-github.css
Labels: bug

#3835 Fix missing upload button in `minimize-upload-bar`
  source/features/minimize-upload-bar.css
Labels: bug

#3827 Improve detection in `hide-useless-comments`
  source/features/hide-useless-comments.tsx
  source/helpers/useless-comments.ts
  test/helpers.ts
Labels: enhancement

#3840 Fix `more-dropdown`
  source/features/more-dropdown.tsx
Labels: bug

#3810 Meta: Fix readme typos
  readme.md
Labels: meta

#3833 Fix `sync-pr-commit-title` to work with GitHub's auto-merge
  source/features/sync-pr-commit-title.tsx
Labels: bug

#3749 Fully restore `set-default-repositories-type-to-sources`
  source/features/deprioritize-marketplace-link.tsx
  source/features/set-default-repositories-type-to-sources.tsx
  source/github-events/on-profile-dropdown-load.ts
Labels: bug

#3783 Add `clean-repo-sidebar` feature
  readme.md
  source/features/clean-conversation-sidebar.css
  source/features/clean-conversation-sidebar.tsx
  source/features/clean-repo-sidebar.css
  source/features/clean-repo-sidebar.tsx
  source/features/hide-empty-meta.tsx
  source/features/hide-zero-packages.tsx
  source/features/releases-tab.tsx
  source/features/toggle-files-button.css
  source/refined-github.ts
Labels: enhancement

#3850 Update dependencies
  package-lock.json
  package.json
  source/features/global-conversation-list-filters.tsx
  source/features/hide-zero-packages.tsx
  source/features/list-prs-for-file.tsx
  source/features/release-download-count.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/github-helpers/api.ts
  tsconfig.json
  webpack.config.ts
Labels: meta

#3849 Meta: Update `element-ready`
  package-lock.json
  package.json
  source/features/batch-open-conversations.tsx
  source/features/bugs-tab.tsx
  source/features/clean-conversation-filters.tsx
  source/features/clean-repo-sidebar.tsx
  source/features/comments-time-machine-links.tsx
  source/features/deprioritize-marketplace-link.tsx
  source/features/extend-conversation-status-filters.tsx
  source/features/forked-to.tsx
  source/features/index.tsx
  source/features/more-dropdown.tsx
  source/features/pr-commit-lines-changed.tsx
  source/features/profile-gists-link.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/trending-menu-item.tsx
  source/features/unwrap-useless-dropdowns.tsx
  source/features/useful-not-found-page.tsx
Labels: bug, meta

#3844 Fix console errors
  source/features/comments-time-machine-links.tsx
  source/features/linkify-code.tsx
  source/features/repo-wide-file-finder.tsx
  source/features/sticky-sidebar.tsx
  source/github-helpers/dom-formatters.ts
Labels: bug

#3851 Prevent soft line-wrap caused by `show-whitespace`
  source/features/show-whitespace.css
Labels: bug

#3856 Fix profile timeline bug caused by `stop-pjax-loading-with-esc`
  source/features/stop-pjax-loading-with-esc.tsx
Labels: bug
