Repository refined-github/refined-github, pull requests merged in 2020-05, with the labels that each got.

#3047 Restore `open-all-notifications` feature
  readme.md
  source/features/open-all-notifications.css
  source/features/open-all-notifications.tsx
Labels: enhancement

#3048 Add `linkify-notification-repository-header` feature
  readme.md
  source/features/linkify-notification-repository-header.tsx
  source/refined-github.ts
Labels: enhancement

#3036 Add `stop-redirecting-in-notification-bar` feature
  readme.md
  source/features/stop-redirecting-in-notification-bar.tsx
  source/refined-github.ts
Labels: enhancement

#3050 Add `unwrap-useless-dropdowns` feature
  readme.md
  source/features/unwrap-useless-dropdowns.tsx
  source/libs/page-detect.ts
  source/refined-github.ts
Labels: enhancement

#3053 Highlight debugging tools when side-loaded
  package.json
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#3051 Add `clean-notifications` feature
  source/features/clean-notifications.css
  source/refined-github.ts
Labels: enhancement

#3054 Fix console error in `hide-disabled-milestone-sorter`
  source/features/hide-disabled-milestone-sorter.tsx
Labels: bug

#3056 Fix console errors in `clean-issue-filters`
  source/features/clean-issue-filters.tsx
Labels: bug

#3059 Make `batch-open-issues` faster
  source/features/batch-open-issues.tsx
Labels: enhancement

#3057 Make `pr-filters` faster
  source/features/pr-filters.tsx
Labels: enhancement

#3070 Update `highest-rated-comment` style to match a Discussion "Answer"
  source/features/highest-rated-comment.css
  source/features/highest-rated-comment.tsx
  source/globals.d.ts
Labels: enhancement

#3060 Extract `webext-options-sync-per-domain` module
  package-lock.json
  package.json
  source/options-storage.ts
  source/options.tsx
Labels: help wanted, meta

#3077 Improve Reviewers hiding in `clean-sidebar`
  source/features/clean-sidebar.tsx
Labels: bug

#3079 Fix position of `warning-for-disallow-edits`
  source/features/warning-for-disallow-edits.tsx
Labels: bug

#3037 Update `web-ext run` command in contributing guide
  .gitignore
  contributing.md
  package.json
  test/web-ext-profile/.gitkeep
Labels: meta

#3087 Show `open-all-notifications` on unsaved filters
  source/features/open-all-notifications.tsx
Labels: bug

#3078 Fix `show-open-prs-of-forks` to only include related PRs
  package-lock.json
  package.json
  source/features/show-open-prs-of-forks.tsx
Labels: bug

#3085 Add `prevent-pr-commit-link-loss` feature
  package-lock.json
  package.json
  readme.md
  source/features/prevent-pr-commit-link-loss.tsx
  source/libs/utils.ts
  source/refined-github.ts
  test/utils.ts
Labels: enhancement

#3101 Lint and console errors
  source/features/default-branch-button.tsx
  source/features/expand-all-collapsed-code.tsx
  source/features/highest-rated-comment.tsx
  source/features/highlight-collaborators-and-own-discussions.tsx
  source/features/list-prs-for-file.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/show-names.tsx
  source/features/sort-issues-by-update-time.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-dropdown.tsx
  source/features/toggle-everything-with-alt.tsx
  source/libs/utils.ts
Labels: bug

#3107 Extract `flat-zip`; drop `group-by`
  package-lock.json
  package.json
  source/features/reactions-avatars.tsx
  source/libs/utils.ts
Labels: meta

#3083 Ensure features work on branches/tags with slashes
  source/features/deep-reblame.tsx
  source/features/edit-files-faster.tsx
  source/features/edit-readme.tsx
  source/features/fix-view-file-link-in-pr.tsx
  source/features/follow-file-renames.tsx
  source/features/more-dropdown.tsx
  source/libs/utils.ts
  test/utils.ts
Labels: bug

#3103 Improve and fix `remove-projects-tab`
  source/features/remove-projects-tab.tsx
  source/features/set-default-repositories-type-to-sources.tsx
Labels: bug

#3111 Fix `fix-view-file-link-in-pr` and ignore deleted files
  source/features/fix-view-file-link-in-pr.tsx
Labels: bug

#3114 Limit `show-user-top-repositories` to the main profile tab
  source/features/show-user-top-repositories.tsx
Labels: bug

#3093 Add `first-published-tag-for-merged-pr` feature
  readme.md
  source/features/first-published-tag-for-merged-pr.tsx
  source/refined-github.ts
Labels: enhancement

#3126 Restore `reactions-avatars`
  source/features/reactions-avatars.tsx
Labels: bug

#3115 `hide-zero-packages` on organization profiles
  source/features/hide-zero-packages.tsx
  source/features/remove-projects-tab.tsx
Labels: enhancement

#3128 Avoid clipping descriptions and CI status messages in `dim-bots`
  source/features/dim-bots.css
Labels: bug

#3130 Minor bug fixes
  source/features/add-tag-to-commits.tsx
  source/features/bugs-tab.tsx
  source/features/esc-to-deselect-line.tsx
  source/features/recently-pushed-branches-enhancements.tsx
  source/features/revert-file.tsx
  source/features/selection-in-new-tab.tsx
  source/features/show-names.tsx
Labels: bug

#3131 Ensure features work on branches/tags with slashes /2
  source/features/follow-file-renames.tsx
  source/features/link-to-file-in-file-history.tsx
Labels: bug

#3116 Add `show-associated-branch-prs-on-fork` feature
  readme.md
  source/features/show-associated-branch-prs-on-fork.tsx
  source/refined-github.ts
Labels: enhancement

#3106 Fix position of `more-dropdown` and `releases-tab`
  source/features/more-dropdown.tsx
  source/features/releases-tab.tsx
Labels: bug

#3141 Exclude 1-commit PRs from `clear-pr-merge-commit-message`
  source/features/clear-pr-merge-commit-message.tsx
Labels: change request

#3135 Only show `comments-time-machine-links` after visiting the link
  source/features/comments-time-machine-links.tsx
Labels: bug, enhancement

#3143 Add cache to `highlight-collaborators-and-own-discussions`
  source/features/highlight-collaborators-and-own-discussions.tsx
Labels: enhancement

#3147 Use Octicons v2
  octicon-svg-loader.ts
  package-lock.json
  package.json
  source/features/bugs-tab.tsx
  source/features/minimize-upload-bar.tsx
  source/features/release-download-count.tsx
  source/features/tags-dropdown.tsx
  webpack.config.ts
Labels: bug

#3150 Reset vertical-align for new octicons in js-issue-row
  source/refined-github.css
Labels: bug

#3138 Meta: relax `parseRoute` and turn it into a more-easily usable class
  source/features/comments-time-machine-links.tsx
  source/features/deep-reblame.tsx
  source/features/default-branch-button.tsx
  source/features/edit-files-faster.tsx
  source/features/edit-readme.tsx
  source/features/follow-file-renames.tsx
  source/features/latest-tag-button.tsx
  source/features/link-to-file-in-file-history.tsx
  source/github-helpers/github-url.ts
  source/github-helpers/parse-route.ts
  test/fixtures/globals.ts
  test/github-url.ts
Labels: bug

#3157 Meta: config and build cleanup
  .xo-config.js
  package-lock.json
  package.json
  size-plugin.json
  source/features/clean-sidebar.tsx
  source/features/index.tsx
  source/features/mark-unread.tsx
  source/features/preview-hidden-comments.tsx
  source/features/sticky-discussion-sidebar.tsx
  source/helpers/on-replaced-element.ts
  webpack.config.ts
Labels: meta

#3154 Deemphasize `update-pr-from-base-branch` button
  source/features/clean-mergeability-box.css
  source/features/update-pr-from-base-branch.tsx
Labels: enhancement
