Repository refined-github/refined-github, pull requests merged in 2020-10, with the labels that each got.

#3602 Lint
  contributing.md
  package-lock.json
  package.json
  readme.md
  source/features/action-used-by-link.tsx
  source/features/bugs-tab.tsx
  source/features/clean-conversation-filters.tsx
  source/features/conflict-marker.tsx
  source/features/conversation-links-on-repo-lists.tsx
  source/features/cross-deleted-pr-branches.tsx
  source/features/download-folder-button.tsx
  source/features/forked-to.tsx
  source/features/highlight-collaborators-and-own-conversations.tsx
  source/features/improve-shortcut-help.tsx
  source/features/index.tsx
  source/features/latest-tag-button.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-private-orgs.tsx
  source/features/parse-backticks.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-filters.tsx
  source/features/profile-gists-link.tsx
  source/features/pull-request-hotkey.tsx
  source/features/reactions-avatars.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/resolve-conflicts.tsx
  source/features/set-default-repositories-type-to-sources.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-followers-you-know.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/stop-pjax-loading-with-esc.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-on-commits-list.tsx
  source/features/trending-menu-item.tsx
  source/features/user-local-time.tsx
  source/github-helpers/get-default-branch.ts
  source/globals.d.ts
  source/options-storage.ts
  source/refined-github.ts
Labels: meta

#3598 Add `table-input` feature
  readme.md
  source/features/collapsible-content-button.tsx
  source/features/table-input.css
  source/features/table-input.tsx
  source/helpers/smart-block-wrap.ts
  source/refined-github.ts
Labels: enhancement

#3604 Add `next-scheduled-github-action` feature
  package-lock.json
  package.json
  readme.md
  source/features/next-scheduled-github-action.tsx
  source/refined-github.ts
Labels: enhancement

#3617 `link-to-github-io` improvements
  source/features/link-to-github-io.tsx
  source/refined-github.ts
Labels: bug, enhancement

#3615 Add tooltip to `table-input` button
  source/features/table-input.tsx
Labels: enhancement

#3610 Enable `bypass-checks` on more commit statuses
  source/features/bypass-checks.tsx
Labels: bug, enhancement

#3627 Use system setting for `user-local-time` time formatting
  source/features/user-local-time.tsx
Labels: enhancement

#3407 Restore `edit-comments-faster` on review comments
  source/features/edit-comments-faster.tsx
Labels: bug

#3623 Don't show next scheduled time of disabled workflows
  source/features/next-scheduled-github-action.tsx
Labels: enhancement

#3625 Extend `linkify-labels-on-dashboard` to newsfeed items
  readme.md
  source/features/linkify-labels-on-dashboard.tsx
Labels: enhancement, help wanted

#3629 Use API for `bypass-checks`
  source/features/bypass-checks.tsx
Labels: enhancement

#3637 Add `convert-pr-to-draft-improvements` feature
  readme.md
  source/features/convert-pr-to-draft-improvements.tsx
  source/refined-github.ts
Labels: enhancement

#3639 Meta: Update dependencies and simplify build
  .gitignore
  distribution/icon.png
  distribution/manifest.json
  distribution/options.html
  octicon-svg-loader.ts
  package-lock.json
  package.json
  tsconfig.json
  webpack.config.ts
Labels: meta

#3644 Don’t run `bypass-checks` on non "run" actions
  source/features/bypass-checks.tsx
Labels: bug

#3646 fix repo filelist actions
  source/features/cleanup-repo-filelist-actions.tsx
Labels: bug

#3649 Preserve capitalization of repository URL in links
  source/features/comments-time-machine-links.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/go-to-action-from-file.tsx
  source/features/latest-tag-button.tsx
  source/features/linkify-branch-references.tsx
  source/features/list-prs-for-file.tsx
  source/features/more-dropdown.tsx
  source/features/releases-tab.tsx
  source/features/repo-wide-file-finder.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-on-commits-list.tsx
  source/features/view-markdown-source.tsx
  source/github-helpers/index.ts
Labels: bug

#3651 Disable `edit-comments-faster` on hidden comments
  source/features/edit-comments-faster.tsx
Labels: bug

#3640 Restore `embed-gist-inline` feature
  source/background.ts
  source/features/embed-gist-inline.tsx
Labels: bug

#3656 Correct border radius for `toggle-files-button`
  source/features/toggle-files-button.css
Labels: enhancement

#3658 Fix "Cookie Preferences" link color in `clean-footer`
  source/features/clean-footer.css
Labels: bug

#3666 Don't add `restore-file` action on new files in PRs
  source/features/restore-file.tsx
Labels: enhancement

#3661 Fix `profile-hotkey` on Gist pages
  source/features/profile-hotkey.tsx
Labels: bug

#3653 Avoid errors caused by `more-dropdown` on issues
  source/features/default-branch-button.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/latest-tag-button.tsx
  source/features/more-dropdown.tsx
  source/features/restore-file.tsx
  source/github-helpers/get-default-branch.ts
  source/github-helpers/github-url.ts
  source/github-helpers/index.ts
Labels: bug

#3621 Meta: Validate feature descriptions and functionality
  readme.md
  source/features/clean-conversation-headers.tsx
  source/features/conflict-marker.tsx
  source/features/default-branch-button.tsx
  source/features/edit-comments-faster.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/latest-tag-button.tsx
  source/features/link-to-github-io.tsx
  source/features/linkify-commit-sha.tsx
  source/features/more-dropdown.tsx
  source/features/raw-file-link.tsx
  source/features/remove-checks-tab.tsx
  source/features/suggest-commit-title-limit.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/use-first-commit-message-for-new-prs.tsx
  source/features/user-profile-follower-badge.tsx
  source/features/vertical-front-matter.tsx
Labels: meta

#3654 Make `releases-tab` non dependent of `more-dropdown`
  source/features/releases-tab.tsx
Labels: bug

#3670 Fetch widget for `view-markdown-source` instead of maintaining a copy of it
  source/background.ts
  source/features/embed-gist-inline.tsx
  source/features/view-markdown-source.tsx
Labels: enhancement

#3681 Restore `faster-reviews` autofocus
  source/features/faster-reviews.tsx
Labels: bug

#3677 Add unpublished Safari build
  .github/workflows/test.yml
  package-lock.json
  package.json
  safari/.gitignore
  safari/Refined GitHub Extension/Info.plist
  safari/Refined GitHub Extension/Refined_GitHub_Extension.entitlements
  safari/Refined GitHub Extension/SafariWebExtensionHandler.swift
  safari/Refined GitHub.xcodeproj/project.pbxproj
  safari/Refined GitHub/AppDelegate.swift
  safari/Refined GitHub/Assets.xcassets/AccentColor.colorset/Contents.json
  safari/Refined GitHub/Assets.xcassets/AppIcon.appiconset/Contents.json
  safari/Refined GitHub/Assets.xcassets/AppIcon.appiconset/icon.png
  safari/Refined GitHub/Assets.xcassets/Contents.json
  safari/Refined GitHub/Base.lproj/Main.storyboard
  safari/Refined GitHub/Info.plist
  safari/Refined GitHub/Refined_GitHub.entitlements
  safari/Refined GitHub/ViewController.swift
  source/github-helpers/parse-backticks.tsx
  source/options.css
  test/web-ext-profile/.gitkeep
Labels: help wanted, safari

#3684 Lint
  package-lock.json
  package.json
  source/features/bugs-tab.tsx
  source/features/bypass-checks.tsx
  source/features/clone-branch.tsx
  source/features/convert-release-to-draft.tsx
  source/features/deep-reblame.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/follow-file-renames.tsx
  source/features/index.tsx
  source/features/mark-private-orgs.tsx
  source/features/new-repo-disable-projects-and-wikis.tsx
  source/features/release-download-count.tsx
  source/features/remove-label-faster.tsx
  source/features/restore-file.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/tags-on-commits-list.tsx
  source/features/toggle-files-button.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/user-local-time.tsx
  source/github-helpers/api.ts
  source/github-helpers/index.ts
  source/github-helpers/parse-backticks.tsx
  source/globals.d.ts
  source/options.tsx
  test/helpers.ts
Labels: meta

#3689 Meta: Fix typo in the description of `show-associated-branch-prs-on-fork`
  readme.md
Labels: meta

#3688 Meta: Parse feature descriptions at build time
  package-lock.json
  package.json
  source/globals.d.ts
  source/options.tsx
  webpack.config.ts
Labels: enhancement
