Repository refined-github/refined-github, pull requests merged in 2020-01, with the labels that each got.

#2655 Fix `filter-comments-by-you` link on PR list page
  source/features/filter-comments-by-you.tsx
Labels: bug

#2652 Fix `widen-search-field` caret position
  source/features/widen-search-field.css
Labels: bug

#2666 Fix alignment of fork icon in `forked-to`
  source/features/forked-to.tsx
Labels: bug

#2670 Fix `cloneNode` type
  source/features/edit-comments-faster.tsx
  source/features/embed-gist-via-iframe.tsx
  source/features/pr-filters.tsx
  source/features/reload-failed-proxied-images.tsx
  source/features/split-issue-pr-search-results.tsx
  source/globals.d.ts
Labels: help wanted, meta

#2644 `ci-link` should only refer to the default branch (+ minor fixes)
  source/features/ci-link.tsx
  source/features/pr-filters.tsx
  source/libs/utils.ts
Labels: enhancement

#2639 Keep features working after clicking the browser’s Back button
  contributing.md
  source/features/batch-open-issues.tsx
  source/features/copy-file.tsx
  source/features/cycle-lists-with-keyboard-shortcuts.tsx
  source/features/default-to-rich-diff.tsx
  source/features/extend-diff-expander.tsx
  source/features/fix-view-file-link-in-pr.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/hide-comments-faster.tsx
  source/features/hide-useless-comments.tsx
  source/features/limit-commit-title-length.tsx
  source/features/mark-unread.tsx
  source/features/minimize-user-comments.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/pr-filters.tsx
  source/features/quick-mention.tsx
  source/features/quick-review-buttons.tsx
  source/features/raw-file-link.tsx
  source/features/revert-file.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/toggle-everything-with-alt.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/wait-for-build.tsx
  source/features/warning-for-disallow-edits.tsx
  source/globals.d.ts
  source/libs/on-new-comments.ts
  source/libs/on-pr-file-load.ts
  source/libs/on-pr-merge-panel-open.ts
Labels: bug, help wanted

#2653 Enable `parse-backticks` on commit titles on more pages
  source/features/add-tag-to-commits.tsx
  source/features/follow-file-renames.tsx
  source/features/link-to-file-in-file-history.tsx
  source/features/parse-backticks.tsx
  source/libs/page-detect.ts
Labels: enhancement

#2675 Faster `latest-tag-button` feature
  source/features/latest-tag-button.tsx
Labels: enhancement

#2676 Faster `default-branch-button` feature
  source/features/default-branch-button.tsx
Labels: enhancement

#2677 Faster `clean-issue-filters` feature
  source/features/clean-issue-filters.tsx
Labels: enhancement

#2678 Meta: Enable JSX linting
  package-lock.json
  package.json
  source/features/add-tag-to-commits.tsx
  source/features/comments-time-machine-links.tsx
  source/features/copy-file.tsx
  source/features/default-branch-button.tsx
  source/features/deprioritize-marketplace-link.tsx
  source/features/download-folder-button.tsx
  source/features/edit-files-faster.tsx
  source/features/edit-readme.tsx
  source/features/embed-gist-inline.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/filter-comments-by-you.tsx
  source/features/follow-file-renames.tsx
  source/features/forked-to.tsx
  source/features/hide-comments-faster.tsx
  source/features/hide-useless-comments.tsx
  source/features/html-preview-link.tsx
  source/features/linkify-branch-references.tsx
  source/features/linkify-labels-on-dashboard.tsx
  source/features/linkify-symbolic-links.tsx
  source/features/linkify-user-location.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-private-orgs.tsx
  source/features/mark-unread.tsx
  source/features/more-dropdown.tsx
  source/features/open-all-notifications.tsx
  source/features/pr-branches.tsx
  source/features/quick-review-buttons.tsx
  source/features/reactions-avatars.tsx
  source/features/split-issue-pr-search-results.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/tags-dropdown.tsx
  source/features/toggle-files-button.tsx
  source/features/useful-not-found-page.tsx
  source/features/wait-for-build.tsx
  source/features/warn-pr-from-master.tsx
  source/options.tsx
Labels: meta

#2687 Meta: Restore stylelint on all files, cross-platform
  package.json
  source/options.css
Labels: meta

#2680 Enable `parse-backticks` in more places on discussion pages
  source/features/parse-backticks.tsx
Labels: enhancement

#2682 Add space between `ci-link` and "Private" label
  source/features/ci-link.css
Labels: bug

#2668 Highlight new features
  source/options.css
  source/options.tsx
Labels: meta

#2659 Restore `tags-dropdown` link to open tag pages
  source/features/tags-dropdown.tsx
Labels: bug

#2691 Restore `highlight-collaborators-and-own-discussions`
  source/features/highlight-collaborators-and-own-discussions.tsx
Labels: bug

#2718 Fix PR link spacing issue caused by `latest-tag-button`
  source/features/latest-tag-button.css
Labels: bug

#2708 Meta: Add error logger that helps user search/report issues
  package-lock.json
  package.json
  source/features/close-out-of-view-modals.tsx
  source/features/mark-unread.tsx
  source/features/sync-pr-commit-title.tsx
  source/libs/features.tsx
  source/libs/utils.ts
  test/page-detect.ts
  test/utils.ts
Labels: help wanted, meta

#2715 Avoid console error caused by `forked-to`
  source/features/forked-to.tsx
Labels: bug

#2714 Restore link to `highest-rated-comment`
  source/features/highest-rated-comment.tsx
  source/features/quick-mention.tsx
Labels: bug

#2694 Meta: Improve copy around personal access token in the options
  source/options.html
Labels: meta, under discussion

#2709 Fix autocompletion overlap in Notifications’ Beta
  source/features/widen-search-field.css
Labels: bug

#2738 Various fixes for `sync-pr-commit-title`
  source/features/sync-pr-commit-title.tsx
Labels: bug

#2736 Avoid duplicate `comments-time-machine-links` in comment dropdown
  source/features/comments-time-machine-links.tsx
Labels: bug

#2735 Extend `hide-zero-packages` to user profiles
  readme.md
  source/features/hide-zero-packages.tsx
Labels: enhancement

#2611 Add `friendlier-requested-changes` feature
  source/content.css
  source/content.ts
  source/features/friendlier-requested-changes.css
Labels: enhancement

#2731 Fix `link-to-file-in-file-history` path detection on page 2+
  source/features/link-to-file-in-file-history.tsx
Labels: bug
