Repository refined-github/refined-github, pull requests merged in 2020-02, with the labels that each got.

#2742 Change style of `emphasize-draft-pr-label`
  source/features/emphasize-draft-pr-label.css
Labels: change request

#2748 Fix style of deep-linked `highest-rated-comment`
  source/features/highest-rated-comment.css
Labels: bug

#2737 Improve `show-whitespace` performance on large files
  source/features/show-whitespace.css
  source/features/show-whitespace.tsx
Labels: firefox

#2753 Update dependencies + lint
  package-lock.json
  package.json
  source/features/clean-issue-filters.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/filter-comments-by-you.tsx
  source/features/forked-to.tsx
  source/globals.d.ts
  source/libs/api.ts
  source/libs/utils.ts
  source/options-storage.ts
  webpack.config.ts
Labels: meta

#2752 Improve GitHub search query manipulation
  source/features/global-discussion-list-filters.tsx
  source/features/split-issue-pr-search-results.tsx
  source/libs/search-query.ts
Labels: enhancement

#2754 Add `expand-all-hidden-comments` feature
  readme.md
  source/content.ts
  source/features/expand-all-hidden-comments.ts
Labels: enhancement

#2750 Add `bugs-tab` feature
  readme.md
  source/content.ts
  source/features/bugs-tab.tsx
Labels: enhancement, under discussion

#2757 Restore `pr-filters` and adjust spacing
  source/content.css
  source/features/pr-filters.tsx
Labels: bug

#2745 Add `extend-discussion-status-filters` feature
  readme.md
  source/content.ts
  source/features/extend-discussion-status-filters.tsx
Labels: enhancement

#2769 Avoid extra whitespace in embedded code with `show-whitespace`
  source/features/show-whitespace.tsx
Labels: bug

#2777 Fix AVA-related CI testing issues
  .github/workflows/test.yml
  .travis.yml
  package.json
Labels: help wanted, meta

#2787 Use API v4 to get the default branch
  source/libs/get-default-branch.ts
Labels: enhancement

#2772 Add the Chromium-based Edge to supported browsers
  readme.md
Labels: meta

#2790 Faster `profile-gists-link`
  source/features/profile-gists-link.tsx
  source/libs/page-detect.ts
Labels: enhancement

#2776 Cache `pr-filters` API request
  readme.md
  source/features/pr-filters.tsx
Labels: enhancement

#2788 Change icon for `mark-private-orgs`
  source/features/mark-private-orgs.css
  source/features/mark-private-orgs.tsx
Labels: change request, under discussion

#2782 Update `tags-dropdown` selectors
  source/features/tags-dropdown.css
  source/features/tags-dropdown.tsx
Labels: bug

#2793 Apply features to Milestone issue lists
  source/libs/page-detect.ts
Labels: bug

#2802 Update linters
  package-lock.json
  package.json
  source/features/faster-pr-diff-options.tsx
  source/features/follow-file-renames.tsx
  source/features/format-discussion-titles.tsx
  source/features/hide-disabled-milestone-sorter.tsx
  source/features/hide-zero-packages.tsx
  source/features/infinite-scroll.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/show-followers-you-know.tsx
  source/features/toggle-files-button.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/user-local-time.tsx
  source/libs/pr-ci-status.ts
  source/libs/utils.ts
  webpack.config.ts
Labels: meta

#2803 Update type packages
  package-lock.json
  package.json
  source/features/mark-unread.tsx
  source/globals.d.ts
Labels: meta

#2813 Fix Issues count when `bugs-tab` finds 1000+ issues
  source/features/bugs-tab.tsx
Labels: bug

#2794 Improve settings in dark mode in Firefox
  source/options.css
Labels: bug

#2789 Faster `mark-private-orgs`
  source/features/mark-private-orgs.tsx
Labels: enhancement

#2835 Don't show unnecessary `default-branch` after AJAX navigation
  source/libs/utils.ts
Labels: bug

#2824 Fix some console errors
  source/features/add-tag-to-commits.tsx
  source/features/user-local-time.tsx
  source/libs/features.tsx
  source/libs/page-detect.ts
Labels: bug

#2771 Tell me whether master is the latest published version
  readme.md
  source/features/latest-tag-button.tsx
Labels: enhancement

#2828 Don't apply `shorten-links` on search results
  source/features/shorten-links.tsx
Labels: bug

#2819 Revert usage of `@me` search keyword to restore GHE support
  source/features/global-discussion-list-filters.tsx
  source/libs/search-query.ts
Labels: bug, enterprise

#2818 Avoid console errors by `pr-branches` on global discussion lists
  source/features/pr-branches.tsx
Labels: bug

#2809 Restore `filter-comments-by-you` on GHE
  source/features/filter-comments-by-you.tsx
Labels: bug, enterprise

#2784 Update cached values earlier (stale while revalidate)
  package-lock.json
  package.json
  source/features/bugs-tab.tsx
  source/features/clean-issue-filters.tsx
  source/features/latest-tag-button.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-private-orgs.tsx
  source/features/pr-filters.tsx
  source/features/releases-tab.tsx
  source/features/user-local-time.tsx
  source/libs/get-default-branch.ts
Labels: enhancement
