Repository refined-github/refined-github, pull requests merged in 2020-11, with the labels that each got.

#3697 Meta: update types and build dependencies
  package-lock.json
  package.json
  source/features/index.tsx
  source/globals.d.ts
Labels: meta

#3660 Meta: remove no-longer-necessary alignment CSS
  source/features/github-bugs.css
Labels: enhancement

#3657 Use a consistent border color
  source/features/clean-dashboard.css
  source/features/clean-pinned-issues.css
  source/features/table-input.css
  source/refined-github.css
Labels: enhancement

#3696 Meta: unminify code in production
  package-lock.json
  package.json
  source/globals.d.ts
  webpack.config.ts
Labels: meta

#3694 Add `unfinished-comments` feature
  readme.md
  source/features/unfinished-comments.tsx
  source/refined-github.ts
Labels: enhancement

#3596 Add `git-checkout-pr` feature
  readme.md
  source/features/git-checkout-pr.tsx
  source/globals.d.ts
  source/refined-github.ts
Labels: enhancement

#3695 Meta: Extract and extend `getRepositoryInfo`
  package-lock.json
  package.json
  source/features/bugs-tab.tsx
  source/features/ci-link.tsx
  source/features/clean-conversation-filters.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/fork-source-link-same-view.tsx
  source/features/forked-to.tsx
  source/features/git-checkout-pr.tsx
  source/features/go-to-action-from-file.tsx
  source/features/highlight-collaborators-and-own-conversations.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/latest-tag-button.tsx
  source/features/link-to-github-io.tsx
  source/features/list-prs-for-file.tsx
  source/features/next-scheduled-github-action.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-filters.tsx
  source/features/recently-pushed-branches-enhancements.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/restore-file.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-dropdown.tsx
  source/features/tags-on-commits-list.tsx
  source/features/warn-pr-from-master.tsx
  source/github-helpers/api.ts
  source/github-helpers/dom-formatters.ts
  source/github-helpers/get-default-branch.ts
  source/github-helpers/index.ts
  test/helpers.ts
Labels: meta

#3698 Add `single-diff-column-selection` feature
  package-lock.json
  package.json
  readme.md
  source/features/single-diff-column-selection.css
  source/features/single-diff-column-selection.tsx
  source/refined-github.ts
Labels: enhancement

#3708 Meta: Update release workflow with `ghat`
  .github/workflows/deployment.yml
  .github/workflows/release.yml
  package.json
Labels: meta

#3710 Add `jump-to-change-requested-comment` feature
  readme.md
  source/features/jump-to-change-requested-comment.tsx
  source/refined-github.ts
Labels: enhancement

#3721 Fix `recently-pushed-branches-enhancements`
  source/features/recently-pushed-branches-enhancements.tsx
Labels: bug

#3726 Fix `profile-hotkey`
  source/features/profile-hotkey.tsx
Labels: bug

#3701 Add `esc-to-cancel` feature
  readme.md
  source/features/esc-to-cancel.tsx
  source/refined-github.ts
Labels: enhancement

#3724 Avoid duplicate upload button in 'rgh-minimize-upload-bar'
  readme.md
  source/features/minimize-upload-bar.css
  source/features/minimize-upload-bar.tsx
Labels: bug

#3725 Fix `deprioritize-marketplace-link`
  source/features/deprioritize-marketplace-link.tsx
Labels: bug

#3722 Fix `first-commit-message-for-new-prs`
  source/features/use-first-commit-message-for-new-prs.tsx
Labels: bug

#3735 Meta: Extract Type checks from build on CI
  .github/workflows/test.yml
Labels: meta

#3723 Lint
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test.yml
  .xo-config.js
  source/features/clean-conversation-filters.tsx
  source/features/clone-branch.tsx
  source/features/comments-time-machine-links.tsx
  source/features/deep-reblame.tsx
  source/features/expand-all-hidden-comments.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/latest-tag-button.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/next-scheduled-github-action.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-commit-lines-changed.tsx
  source/features/pr-filters.tsx
  source/features/quick-review-buttons.tsx
  source/features/recently-pushed-branches-enhancements.tsx
  source/features/release-download-count.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/restore-file.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/tags-on-commits-list.tsx
  source/features/user-profile-follower-badge.tsx
  source/github-helpers/api.ts
  source/github-helpers/dom-formatters.ts
  source/github-helpers/github-url.ts
  source/github-helpers/group-buttons.tsx
  source/github-helpers/index.ts
  source/github-helpers/parse-backticks.tsx
  source/helpers/on-element-removal.ts
  source/helpers/simplified-element-observer.ts
  source/helpers/smart-block-wrap.ts
  source/options-storage.ts
Labels: meta

#3734 Add `quick-fork-deletion` feature
  readme.md
  source/background.ts
  source/features/comments-time-machine-links.tsx
  source/features/quick-fork-deletion.css
  source/features/quick-fork-deletion.tsx
  source/features/show-open-prs-of-forks.tsx
  source/github-helpers/api.ts
  source/github-widgets/notice-bar.tsx
  source/helpers/pluralize.ts
  source/refined-github.ts
Labels: enhancement

#3754 Fix `z-index` conflict between `sticky-sidebar` and the footer
  source/features/sticky-sidebar.css
Labels: bug

#3755 Update `highest-rated-comment` style
  readme.md
  source/features/highest-rated-comment.css
  source/features/highest-rated-comment.tsx
Labels: bug

#3753 Drop `recently-pushed-branches-enhancements` feature
  readme.md
  source/features/recently-pushed-branches-enhancements.css
  source/features/recently-pushed-branches-enhancements.tsx
  source/refined-github.ts
Labels: change request

#3757 Meta: Add more information about the token in the options page
  distribution/options.html
  source/options.css
Labels: meta

#3707 Improve `unfinished-comments` detection logic
  source/features/unfinished-comments.tsx
Labels: bug

#3756 Meta: Extract modules `one-mutation` `push-form` `regex-join`
  package-lock.json
  package.json
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/remove-projects-tab.tsx
  source/features/restore-file.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/sync-pr-commit-title.tsx
  source/helpers/concat-regex.ts
  source/helpers/dom-utils.ts
  source/helpers/post-form.ts
  source/helpers/simplified-element-observer.ts
  webpack.config.ts
Labels: meta

#3750 Add `pr-easy-toggle-files` feature
  readme.md
  source/features/pr-easy-toggle-files.tsx
  source/refined-github.ts
Labels: enhancement

#3747 Fix `close-out-of-view-modals` bug that breaks Watch dropdown
  source/features/close-out-of-view-modals.tsx
Labels: bug

#3760 Don't `hide-zero-packages` on your own profile
  source/features/hide-zero-packages.tsx
Labels: bug

#3768 Meta: Update dependencies
  package-lock.json
  package.json
  source/features/submit-review-as-single-comment.tsx
  source/helpers/one-event.ts
Labels: meta

#3767 Enable `unfinished-comments` on temporarily-hidden text fields
  source/features/unfinished-comments.tsx
Labels: bug
