Repository refined-github/refined-github, pull requests merged in 2020-04, with the labels that each got.

#2948 Fix `hide-inactive-deployments` and "Load more..." detection
  source/features/hide-inactive-deployments.tsx
  source/libs/on-new-comments.ts
Labels: bug

#2963 Remove `copy-file` from Markdown view
  source/features/copy-file.tsx
Labels: bug

#2964 Fix deployment cronjob
  .github/workflows/deploy-auto.yml
Labels: meta

#2969 Fix link selection logic in `bypass-checks`
  readme.md
  source/features/bypass-checks.tsx
Labels: bug

#2966 Add cache to `user-profile-follower-badge`
  source/features/user-profile-follower-badge.tsx
Labels: enhancement

#2965 Fix some page detection
  source/libs/page-detect.ts
  test/page-detect.ts
Labels: bug

#2950 Use `webext-base-css` to improve Option page’s style
  package-lock.json
  package.json
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#2972 Don't 404 `deep-reblame` on renamed files
  source/features/deep-reblame.tsx
Labels: bug

#2947 Add `parse-backticks` to more places
  source/features/parse-backticks.tsx
Labels: enhancement

#2976 Fix `deep-reblame` css selector
  source/features/deep-reblame.css
Labels: bug

#2986 Simplify Octicons build by dropping Buble
  octicon-svg-loader.ts
  package-lock.json
  package.json
  webpack.config.ts
Labels: meta

#2990 Only look for `ci-link` in the last 2 days of commits
  source/features/ci-link.tsx
Labels: bug

#2992 Improve feature application on AJAXed widgets
  source/features/clean-sidebar.tsx
  source/features/mark-unread.tsx
  source/features/reactions-avatars.tsx
  source/features/sticky-discussion-sidebar.tsx
  source/globals.d.ts
  source/libs/on-element-removal.ts
  source/libs/on-replaced-element.ts
  source/libs/on-updatable-content-update.ts
Labels: bug

#2979 Avoid API call when possible in `clean-issue-filters`
  source/features/clean-issue-filters.tsx
Labels: enhancement

#2994 Disable `update-pr-from-base-branch` when action is impossible
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#2981 Add `discussion-links-on-repo-lists` feature
  readme.md
  source/features/discussion-links-on-repo-lists.tsx
  source/libs/page-detect.ts
  source/refined-github.ts
Labels: enhancement

#3000 Restore `clone-branch`
  source/features/clone-branch.tsx
Labels: bug

#2998 Fix GitHub’s own "Edit readme" link on tag pages
  readme.md
  source/features/edit-readme.tsx
Labels: enhancement

#3003 Add `clear-pr-merge-commit-message` feature
  readme.md
  source/features/clear-pr-merge-commit-message.tsx
  source/refined-github.ts
Labels: enhancement

#3023 Keep `clone-branch` after a search
  source/features/clone-branch.tsx
Labels: bug

#3011 Add `go-to-action-from-file` feature
  readme.md
  source/features/go-to-action-from-file.tsx
  source/refined-github.ts
Labels: enhancement, needs readme update

#3034 Meta: Use JSX when generating elements with functions
  package-lock.json
  package.json
  source/features/add-tag-to-commits.tsx
  source/features/bugs-tab.tsx
  source/features/clone-branch.tsx
  source/features/collapsible-content-button.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conflict-marker.tsx
  source/features/deep-reblame.tsx
  source/features/default-branch-button.tsx
  source/features/discussion-links-on-repo-lists.tsx
  source/features/edit-comments-faster.tsx
  source/features/edit-files-faster.tsx
  source/features/edit-readme.tsx
  source/features/extend-discussion-status-filters.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/forked-to.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/highest-rated-comment.tsx
  source/features/latest-tag-button.tsx
  source/features/link-to-file-in-file-history.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/mark-private-orgs.tsx
  source/features/mark-unread.tsx
  source/features/minimize-upload-bar.tsx
  source/features/more-dropdown.tsx
  source/features/open-all-notifications.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-branches.tsx
  source/features/pr-filters.tsx
  source/features/quick-mention.tsx
  source/features/release-download-count.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-dropdown.tsx
  source/features/toggle-files-button.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/user-local-time.tsx
  source/features/view-markdown-source.tsx
  source/features/wait-for-build.tsx
  source/globals.d.ts
  source/libs/icon-loading.tsx
Labels: meta

#3033 Add `action-used-by-link` feature
  readme.md
  source/features/action-used-by-link.tsx
  source/libs/page-detect.ts
  source/refined-github.ts
Labels: enhancement

#3007 Add `batch-mark-files-as-viewed` feature
  readme.md
  source/features/batch-mark-files-as-viewed.tsx
  source/refined-github.ts
Labels: enhancement
