Repository refined-github/refined-github, pull requests merged in 2020-08, with the labels that each got.

#3430 Fixes and improvements to `useful-not-found-page`
  source/features/useful-not-found-page.tsx
Labels: bug, enhancement

#3422 Fix `restore-file` for deleted files in forks
  source/features/restore-file.tsx
Labels: bug

#3429 Append `ci-link` icon after private label
  source/features/ci-link.css
  source/features/ci-link.tsx
Labels: bug

#3432 Small fix to `show-open-prs-of-forks`
  source/features/show-open-prs-of-forks.tsx
Labels: bug

#3446 Fix `sticky-conversation-sidebar` spacing
  source/features/sticky-conversation-sidebar.css
Labels: bug

#3420 Preserve current branch in `forked-to` link when possible
  source/features/forked-to.tsx
  source/github-helpers/github-url.ts
Labels: enhancement

#3447 Apply `shorten-links` after editing comments
  source/features/shorten-links.tsx
Labels: bug

#3409 Apply `linkify-code` to unfolded diffs
  source/features/linkify-code.tsx
Labels: bug

#3445 Only use the default branch to determine `repo-age`
  source/features/repo-age.tsx
Labels: bug

#3433 Add `prevent-duplicate-pr-submission` feature
  readme.md
  source/features/prevent-duplicate-pr-submission.tsx
  source/refined-github.ts
Labels: enhancement

#3437 Lint
  source/features/ci-link.tsx
  source/features/clean-sidebar.tsx
  source/features/keyboard-navigation.tsx
  source/features/linkify-user-edit-history-popup.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/more-dropdown.tsx
  source/features/releases-tab.tsx
  source/features/show-followers-you-know.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/tag-changelog-link.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/warning-for-disallow-edits.tsx
  source/github-helpers/index.ts
  source/options-storage.ts
Labels: meta

#3450 Enable `fork-source-link-same-view` on editing pages
  source/features/fork-source-link-same-view.tsx
Labels: enhancement

#3451 Meta: Update devDependencies
  package-lock.json
  package.json
  source/helpers/simplified-element-observer.ts
  webpack.config.ts
Labels: meta

#3442 Replace `repeatOnAjax` with explicit `onetime`
  contributing.md
  source/features/clean-rich-text-editor.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/copy-on-y.tsx
  source/features/deprioritize-marketplace-link.tsx
  source/features/embed-gist-via-iframe.tsx
  source/features/esc-to-deselect-line.tsx
  source/features/file-finder-buffer.tsx
  source/features/hide-navigation-hover-highlight.tsx
  source/features/hide-own-stars.tsx
  source/features/hide-useless-newsfeed-events.tsx
  source/features/hide-watch-and-fork-count.tsx
  source/features/improve-shortcut-help.tsx
  source/features/index.tsx
  source/features/infinite-scroll.tsx
  source/features/linkify-labels-on-dashboard.tsx
  source/features/linkify-user-edit-history-popup.tsx
  source/features/monospace-textareas.tsx
  source/features/one-key-formatting.tsx
  source/features/open-issue-to-latest-comment.tsx
  source/features/parse-backticks.tsx
  source/features/profile-hotkey.tsx
  source/features/recently-pushed-branches-enhancements.tsx
  source/features/remove-projects-tab.tsx
  source/features/selection-in-new-tab.tsx
  source/features/show-names.tsx
  source/features/sort-conversations-by-update-time.tsx
  source/features/stop-redirecting-in-notification-bar.tsx
  source/features/tab-to-indent.tsx
  source/features/trending-menu-item.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-local-time.tsx
Labels: meta

#3444 Minor style fixes for GitHub bugs
  source/features/github-bugs.css
  source/refined-github.css
  source/refined-github.ts
Labels: enhancement

#3456 Faster & Simplify `close-out-of-view-modals`
  source/features/close-out-of-view-modals.tsx
  source/globals.d.ts
Labels: enhancement

#3408 Add `clean-conversation-headers` feature
  readme.md
  source/features/clean-conversation-headers.tsx
  source/refined-github.ts
Labels: enhancement

#3454 Add `remove-label-faster` feature
  readme.md
  source/features/remove-label-faster.css
  source/features/remove-label-faster.tsx
  source/github-helpers/api.ts
  source/refined-github.ts
Labels: enhancement

#3439 Add `highlight-deleted-and-added-files-in-diffs` feature
  readme.md
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/refined-github.ts
Labels: enhancement

#3443 Add `convert-release-to-draft` feature
  package-lock.json
  package.json
  readme.md
  source/features/convert-release-to-draft.tsx
  source/github-helpers/api.ts
  source/refined-github.ts
Labels: enhancement

#3473 `release-download-count`: hide zero download counts
  source/features/release-download-count.tsx
Labels: enhancement

#3476 Fix `remove-label-faster`
  source/features/remove-label-faster.tsx
Labels: bug

#3477 Fix conflicts with `default-branch-button`
  source/features/download-folder-button.tsx
Labels: bug

#3474 Restore `navigate-pages-with-arrow-keys`
  source/features/navigate-pages-with-arrow-keys.tsx
Labels: bug

#3484 Add missing space in `clean-conversation-headers`
  source/features/clean-conversation-headers.tsx
Labels: bug

#3478 Lint
  source/features/bugs-tab.tsx
  source/features/clean-conversation-headers.tsx
  source/features/clone-branch.tsx
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/pr-commit-lines-changed.tsx
  source/features/remove-label-faster.tsx
  source/features/repo-age.tsx
  source/features/restore-file.tsx
  source/features/show-open-prs-of-forks.tsx
Labels: meta

#3489 Meta: enable more lint rules
  .xo-config.js
  source/features/add-tag-to-commits.tsx
  source/features/convert-release-to-draft.tsx
  source/features/deep-reblame.tsx
  source/features/faster-reviews.tsx
  source/features/highest-rated-comment.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/reactions-avatars.tsx
  source/features/remove-label-faster.tsx
  source/features/remove-projects-tab.tsx
  source/features/show-whitespace.tsx
  source/features/stop-redirecting-in-notification-bar.tsx
  source/features/tag-changelog-link.tsx
  source/features/vertical-front-matter.tsx
  source/github-helpers/api.ts
  source/github-helpers/github-url.ts
  source/github-helpers/index.ts
Labels: meta

#3479 Fix `format-conversation-titles`
  source/features/format-conversation-titles.tsx
Labels: bug

#3481 Apply `navigate-pages-with-arrow-keys` to notification page
  source/features/navigate-pages-with-arrow-keys.tsx
Labels: enhancement

#3480 Highlight a PR's base branch if it's not the default
  source/features/clean-conversation-headers.css
  source/features/clean-conversation-headers.tsx
Labels: enhancement

#3485 Add `same-page-definition-jump` feature
  readme.md
  source/features/same-page-definition-jump.tsx
  source/refined-github.ts
Labels: enhancement

#3500 Fix `pull-request-hotkey`
  source/features/pull-request-hotkey.tsx
Labels: bug

#3497 Fix `latest-tag-button` position
  source/features/latest-tag-button.tsx
Labels: bug

#3507 Adjust minimized review comment selector
  source/features/keyboard-navigation.tsx
Labels: bug

#3509 Add `isRepoSearch` into `parse-backticks`
  source/features/latest-tag-button.tsx
  source/features/parse-backticks.tsx
Labels: enhancement

#3511 Enable `warn-pr-from-master` on cross fork pr's
  source/features/warn-pr-from-master.tsx
Labels: bug, enhancement

#3516 Prevent `linkify-urls` from running multiple times
  source/features/linkify-code.tsx
Labels: bug

#3510 Faster `edit-readme`
  source/features/edit-readme.tsx
Labels: enhancement

#3512 Use `selector-observer` in `show-associated-branch-prs-on-fork`
  source/features/show-associated-branch-prs-on-fork.tsx
Labels: enhancement

#3498 Re-add top padding removed by `hide-readme-header`
  source/features/hide-readme-header.css
Labels: bug

#3515 Refactor `hide-disable-milestone-sorter` to use `selector-observer`
  source/features/hide-disabled-milestone-sorter.tsx
Labels: meta

#3513 Refactor `clone-branch` to use `selector-observer`
  source/features/clone-branch.tsx
Labels: meta

#3519 Correctly hide more information in `dim-bots`
  source/features/dim-bots.css
Labels: bug

#3517 Improve `cleanup-repo-filelist-actions`’s reliability
  source/features/cleanup-repo-filelist-actions.tsx
Labels: bug
