Repository refined-github/refined-github, pull requests merged in 2020-07, with the labels that each got.

#3266 Fix `wait-for-build` checkbox display
  source/github-helpers/pr-ci-status.ts
Labels: bug

#3264 Restore `toggle-files-button`+`repo-age` in "Repository refresh"
  source/features/repo-age.tsx
  source/features/toggle-files-button.css
  source/features/toggle-files-button.tsx
Labels: bug

#3300 Fix `clone-branch` and `show-associated-branch-prs-on-fork`
  source/features/clone-branch.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
Labels: bug

#3303 Fix `clean-pinned-issues` layout
  source/features/clean-pinned-issues.css
Labels: bug

#3273 Update `set-default-repositories-type-to-sources` selectors
  source/features/set-default-repositories-type-to-sources.tsx
Labels: bug

#3282 Update `view-markdown-source` selector
  source/features/view-markdown-source.tsx
Labels: bug

#3271 Move `user-profile-follower-badge` position
  source/features/user-profile-follower-badge.tsx
Labels: bug

#3254 Fix `download-folder-button` and `latest-tag-button`
  source/features/download-folder-button.tsx
  source/features/latest-tag-button.tsx
Labels: bug

#3316 Update dependencies; make Firefox 78 the minimum version
  package-lock.json
  package.json
  source/features/repo-age.tsx
  source/manifest.json
  source/options-storage.ts
  webpack.config.ts
Labels: meta

#3242 Add `keyboard-navigation` feature
  readme.md
  source/features/keyboard-navigation.tsx
  source/refined-github.ts
Labels: enhancement

#3313 Add `align-repository-header` feature
  package.json
  readme.md
  source/features/align-repository-header.css
  source/refined-github.ts
Labels: enhancement

#3272 Add tab icon to `profile-gists-link`
  source/features/profile-gists-link.tsx
Labels: enhancement

#3304 Update `view-markdown-source` selector again
  source/features/view-markdown-source.tsx
Labels: bug

#3320 Show `prevent-pr-commit-link-loss` on "new issue/PR" pages
  source/features/prevent-pr-commit-link-loss.tsx
Labels: enhancement

#3314 Lint and avoid errors
  package-lock.json
  package.json
  source/features/align-issue-labels.tsx
  source/features/clean-sidebar.tsx
  source/features/copy-on-y.tsx
  source/features/esc-to-deselect-line.tsx
  source/features/hide-watch-and-fork-count.css
  source/features/minimize-upload-bar.css
  source/features/pr-jump-to-first-non-viewed-file.tsx
  source/features/quick-review-buttons.tsx
  source/features/reactions-avatars.tsx
  source/features/releases-tab.tsx
  source/options.css
  source/refined-github.css
Labels: bug

#3322 Limit `align-repository-header` to non-full-width pages
  source/features/align-repository-header.css
Labels: bug

#3335 Fix `align-repository-header` on gists
  source/features/align-repository-header.css
Labels: bug

#3288 Add `fix-first-tab-length` feature
  readme.md
  source/features/fix-first-tab-length.css
  source/refined-github.ts
Labels: enhancement, help wanted

#3334 Fix links in `tags-dropdown`
  source/features/tags-dropdown.tsx
Labels: bug

#3328 Preserve "Edit comment" in dropdown
  source/features/edit-comments-faster.tsx
Labels: enhancement

#3353 Fix `latest-tag-button`
  source/features/latest-tag-button.tsx
Labels: bug

#3290 Apply `parse-backticks` to more pages
  readme.md
  source/features/parse-backticks.tsx
Labels: bug, enhancement

#3352 Fix fork popup title style
  source/refined-github.css
Labels: enhancement

#3343 Fix `highest-rated-comment` overlap with avatar
  source/features/highest-rated-comment.tsx
Labels: bug

#3326 Fix multiple `copy-file` buttons on gist svg files
  source/features/copy-file.tsx
Labels: bug

#3346 Refresh `more-dropdown` feature
  source/features/more-dropdown.css
  source/features/more-dropdown.tsx
  source/features/releases-tab.tsx
Labels: bug

#3292 Fix display of wrapped whitespace in `show-whitespace`
  source/features/show-whitespace.css
  source/features/show-whitespace.tsx
Labels: bug, help wanted

#3361 Restore `bugs-tab`
  source/features/bugs-tab.tsx
Labels: bug

#3327 Add `vertical-front-matter` feature
  readme.md
  source/features/vertical-front-matter.css
  source/features/vertical-front-matter.tsx
  source/refined-github.ts
Labels: enhancement

#3362 Fix features relying on `.pagehead`
  source/features/ci-link.css
  source/features/ci-link.tsx
  source/features/file-finder-buffer.tsx
  source/features/fork-source-link-same-view.tsx
  source/features/releases-tab.tsx
  source/features/show-open-prs-of-forks.tsx
Labels: bug

#3369 Fix permalink detection in 3 features
  source/features/comments-time-machine-links.tsx
  source/features/edit-files-faster.tsx
  source/features/edit-readme.tsx
  source/github-helpers/index.ts
Labels: bug

#3371 Restore `parse-backticts` on `isPulse`
  source/features/parse-backticks.tsx
Labels: bug

#3384 Fix `repo-age` where there is only one commit
  source/features/repo-age.tsx
Labels: bug

#3380 Fix `align-issue-labels` selector
  source/features/align-issue-labels.css
Labels: bug

#3390 Update `parse-backticks` selectors
  source/features/parse-backticks.tsx
Labels: bug

#3372 Fix `add-tag-to-commits` and `mark-merge-commits-in-list`
  source/features/add-tag-to-commits.tsx
  source/features/mark-merge-commits-in-list.tsx
Labels: bug

#3373 Restore counter on `profile-gists-link`
  source/features/profile-gists-link.tsx
Labels: enhancement

#3342 Add `use-first-commit-message-for-new-prs` feature
  readme.md
  source/features/use-first-commit-message-for-new-prs.tsx
  source/refined-github.ts
Labels: enhancement

#3395 Fix `add-tag-to-commits` selector
  source/features/add-tag-to-commits.tsx
Labels: bug

#3389 Fix `dim-bots` selectors
  source/features/dim-bots.css
Labels: bug

#3396 Fix `comment-fields-keyboard-shortcuts`
  source/features/comment-fields-keyboard-shortcuts.tsx
Labels: bug

#3402 Fix bad linebreaks in `default-branch-button` and `latest-tag-button`
  source/features/default-branch-button.tsx
  source/features/latest-tag-button.tsx
Labels: bug

#3397 Make `parse-backticks` more reliable
  package-lock.json
  package.json
  source/features/parse-backticks.tsx
Labels: bug

#3401 Reduce `pr-branches` to `highlight-non-default-base-branch`
  readme.md
  source/features/highlight-non-default-base-branch.tsx
  source/features/pr-branches.tsx
  source/refined-github.ts
Labels: change request

#3406 Restore `ci-link`
  source/features/ci-link.tsx
Labels: bug

#3405 Add `cleanup-repo-filelist-actions` feature
  readme.md
  source/features/cleanup-repo-filelist-actions.tsx
  source/refined-github.ts
Labels: enhancement

#3404 Support branches with slashes in `comments-time-machine-links`
  source/features/comments-time-machine-links.tsx
Labels: bug

#3377 Fix `keyboard-navigation` issues
  source/features/keyboard-navigation.tsx
Labels: bug

#3412 Add `linkify-user-edit-history-popup` feature
  readme.md
  source/features/linkify-user-edit-history-popup.tsx
  source/refined-github.ts
Labels: enhancement
