Repository refined-github/refined-github, pull requests merged in 2020-03, with the labels that each got.

#2831 Fix `mark-private-orgs` showing on all organizations
  source/features/mark-private-orgs.tsx
Labels: bug

#2795 Add `pinned-issues-update-time` feature
  readme.md
  source/content.ts
  source/features/pinned-issues-update-time.tsx
Labels: enhancement

#2832 Add back `mark-merge-commits-in-list` feature
  readme.md
  source/content.ts
  source/features/mark-merge-commits-in-list.css
  source/features/mark-merge-commits-in-list.tsx
Labels: enhancement, needs readme update

#2783 Determine `repo-age` with its first commit
  source/features/repo-age.tsx
Labels: enhancement

#2851 Don't exclude bugs from Issues tab (`bugs-tab`)
  source/features/bugs-tab.tsx
Labels: change request

#2853 Show `00:mm` instead of `24:mm` in `user-local-time`
  source/features/user-local-time.tsx
Labels: bug

#2862 Fix broken Compare icon in `more-dropdown`
  source/features/more-dropdown.tsx
Labels: bug

#2864 Fix `dim-bots` styles
  source/features/dim-bots.css
Labels: bug

#2868 Cache improvements for `latest-tag-button`
  source/features/latest-tag-button.tsx
Labels: bug

#2867 Fix `repo-age` selector
  source/features/repo-age.tsx
Labels: bug

#2860 Drop `friendlier-requested-changes` feature
  source/content.css
  source/content.ts
  source/features/friendlier-requested-changes.css
Labels: change request

#2869 Lint and minor console errors fixes
  .github/pull_request_template.md
  source/features/hide-navigation-hover-highlight.css
  source/features/improve-shortcut-help.tsx
  source/features/pr-branches.tsx
  source/features/selection-in-new-tab.tsx
  source/features/tags-dropdown.css
  source/libs/api.ts
Labels: bug

#2825 Add 3 `file-finder`-related features
  readme.md
  source/content.ts
  source/features/file-finder-buffer.tsx
  source/features/preserve-file-finder-term.tsx
  source/features/repo-wide-file-finder.tsx
  source/globals.d.ts
  source/libs/page-detect.ts
Labels: enhancement, needs readme update

#2872 Allow `align-issue-labels` to be disabled
  source/content.ts
  source/features/align-issue-labels.css
  source/features/align-issue-labels.tsx
Labels: enhancement

#2873 Fix `link-to-file-in-file-history`
  source/features/link-to-file-in-file-history.tsx
Labels: bug

#2866 Fix `releases-tab` position on repo with "settings" in their name
  source/features/more-dropdown.tsx
  source/features/releases-tab.tsx
  source/libs/dom-utils.ts
  source/libs/utils.ts
  test/utils.ts
Labels: bug

#2877 Fix position of `user-profile-follower-badge`
  source/features/user-profile-follower-badge.css
Labels: bug

#2847 Restore `cross-deleted-pr-branches`
  readme.md
  source/content.ts
  source/features/cross-deleted-pr-branches.css
  source/features/cross-deleted-pr-branches.tsx
Labels: enhancement

#2858 Add `pr-commit-lines-changed` feature
  readme.md
  source/content.ts
  source/features/pr-commit-lines-changed.tsx
  source/libs/utils.ts
  test/utils.ts
Labels: enhancement

#2892 Improve `forked-to` reliability
  package-lock.json
  package.json
  source/features/forked-to.tsx
  source/libs/utils.ts
Labels: bug

#2870 Improve `list-prs-for-file`'s display
  source/features/list-prs-for-file.tsx
Labels: bug

#2899 Meta, updates, lint
  package-lock.json
  package.json
  source/features/comments-time-machine-links.tsx
  source/features/esc-to-deselect-line.tsx
  source/features/infinite-scroll.tsx
  source/features/mark-unread.tsx
  source/features/view-markdown-source.tsx
  source/libs/page-detect.ts
  source/libs/utils.ts
  test/fixtures/globals.ts
  webpack.config.ts
Labels: meta

#2880 Add `show-open-prs-of-forks` feature
  readme.md
  source/content.ts
  source/features/forked-to.tsx
  source/features/show-open-prs-of-forks.tsx
  source/libs/page-detect.ts
  source/libs/utils.ts
Labels: enhancement

#2902 Adjust filters padding on Security page
  source/content.css
  source/features/batch-open-issues.tsx
  source/features/pr-filters.tsx
Labels: bug

#2915 Avoid losing options when removing the github.com permission
  source/options-storage.ts
Labels: meta

#2916 Clean `clean-sidebar` and also clean "Linked issues" section
  source/features/clean-sidebar.css
  source/features/clean-sidebar.tsx
Labels: enhancement

#2905 Exclude pre-releases from `latest-tag-button`
  source/features/latest-tag-button.tsx
  source/libs/utils.ts
  test/utils.ts
Labels: enhancement

#2904 Wrap reaction avatars to avoid "CSS IS AWESØME"
  source/features/reactions-avatars.css
  source/features/reactions-avatars.tsx
Labels: bug

#2896 Add `clone-branch` feature
  readme.md
  source/content.ts
  source/features/clone-branch.tsx
  source/libs/icon-loading.tsx
  source/libs/page-detect.ts
Labels: enhancement

#2921 Make `forked-to`'s cache case-insensitive
  source/features/forked-to.tsx
Labels: bug

#2929 Avoid console error in `preserve-file-finder-term`
  source/features/preserve-file-finder-term.tsx
Labels: bug

#2928 Fix `close-out-of-view-modals`
  source/features/close-out-of-view-modals.tsx
Labels: bug

#2919 Improve error UX
  contributing.md
  source/features/submit-review-as-single-comment.tsx
  source/libs/utils.ts
  source/manifest.json
  source/refined-github.css
  source/refined-github.ts
  webpack.config.ts
Labels: meta

#2938 Show `default-branch-button` on Commit lists
  source/features/default-branch-button.tsx
Labels: enhancement

#2933 Fix `close-out-of-view-modals` on more pages
  source/features/close-out-of-view-modals.tsx
  source/features/forked-to.tsx
  source/features/more-dropdown.tsx
Labels: bug

#2932 Limit `expand-all-hidden-comments` to 200
  readme.md
  source/features/expand-all-hidden-comments.ts
Labels: bug

#2881 Add `deep-blame` feature
  readme.md
  source/features/deep-reblame.css
  source/features/deep-reblame.tsx
  source/refined-github.ts
Labels: enhancement

#2946 Don't try to add `default-branch-button` to PR Commits pages
  source/features/default-branch-button.tsx
Labels: bug

#2945 Meta: Move deploy from Travis to GHA
  .github/workflows/deploy-auto.yml
  .github/workflows/deploy-tag.yml
  .github/workflows/test.yml
  .travis.yml
  .travis/github_deploy_key.enc
  package.json
  readme.md
Labels: meta
