Repository refined-github/refined-github, pull requests merged in 2020-06, with the labels that each got.

#3152 Let users view/edit/delete files when comparing branches
  readme.md
  source/features/enable-file-links-in-compare-view.tsx
  source/features/fix-view-file-link-in-pr.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: enhancement

#3153 Fix URL parsing in history views
  source/features/default-branch-button.tsx
  source/features/follow-file-renames.tsx
  source/github-helpers/github-url.ts
  test/github-url.ts
Labels: bug

#3166 Restore private repo in some features
  source/github-helpers/index.ts
Labels: bug

#3172 Split `options.tsx`’ `init` function into multiple parts
  source/options.tsx
Labels: meta

#3170 Meta: refactor `getCurrentBranch`
  source/github-helpers/index.ts
Labels: meta

#3149 Add `faster-reviews` feature
  readme.md
  source/features/clean-sidebar.tsx
  source/features/faster-reviews.tsx
  source/refined-github.ts
Labels: enhancement

#3148 Fix Octicons-related issues
  source/features/more-dropdown.css
  source/refined-github.css
Labels: bug

#3176 Restore `reactions-avatars` again
  source/features/reactions-avatars.tsx
Labels: bug

#3169 Make `repo-age` a clickable link
  source/features/repo-age.tsx
Labels: enhancement

#3189 `stop-redirecting-in-notification-bar` automatically when possible
  source/features/stop-redirecting-in-notification-bar.tsx
Labels: enhancement

#3190 Restore weekly cronjob
  .github/workflows/deploy-tag.yml
  .github/workflows/deployment.yml
Labels: meta

#3184 Meta: Reduce GitHub Actions runs on local PRs
  .github/workflows/test.yml
Labels: meta

#3181 Chrome: Open the options source/screenshot links in a new tab
  source/options.tsx
Labels: bug

#3177 Enable `raw-file-link` on `isCompare`
  source/features/raw-file-link.tsx
Labels: enhancement

#3175 Update dependencies and lint
  package-lock.json
  package.json
  source/features/clone-branch.tsx
  source/features/cross-deleted-pr-branches.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/faster-reviews.tsx
  source/features/prevent-pr-commit-link-loss.tsx
  source/features/remove-checks-tab.tsx
  source/features/resolve-conflicts.tsx
  source/features/revert-file.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/show-user-top-repositories.tsx
  source/features/tag-changelog-link.tsx
  source/features/tags-dropdown.tsx
  webpack.config.ts
Labels: enhancement

#3209 Avoid duplicate `fast-reviews` links
  source/features/faster-reviews.tsx
Labels: bug

#3208 Fix URL parsing in Firefox
  source/github-helpers/github-url.ts
Labels: bug, firefox

#3211 Hide duplicate "You can also open this in GitHub Desktop" in PRs
  source/refined-github.css
Labels: enhancement

#3216 Link to current file/folder in `forked-to` links
  source/features/forked-to.tsx
Labels: enhancement

#3219 Fix console errors and make `releases-tab` more reliable
  source/features/faster-reviews.tsx
  source/features/releases-tab.tsx
  source/github-helpers/index.ts
Labels: bug

#3206 Meta: Fix tests to run (only) on newer Node versions
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  .gitignore
  .xo-config.js
  package-lock.json
  package.json
  source/github-helpers/index.ts
  test/fixtures/globals.ts
  webpack.config.ts
Labels: meta

#3210 Docs: Mention Node requirement in contributing.md
  contributing.md
Labels: meta

#3174 Enable `open-issue-to-latest-comment` on the dashboard
  readme.md
  source/features/open-issue-to-latest-comment.tsx
Labels: enhancement

#3207 Add "Everything you subscribed to" filter to `filter-comments-by-you`
  readme.md
  source/features/discussion-filters.tsx
  source/features/filter-comments-by-you.tsx
  source/refined-github.ts
Labels: enhancement

#3220 Add `clean-pinned-issues` feature
  readme.md
  source/features/clean-pinned-issues.css
  source/features/pinned-issues-update-time.tsx
  source/refined-github.ts
Labels: enhancement

#3223 Fix `prevent-pr-commit-link-loss`
  source/features/prevent-pr-commit-link-loss.tsx
  source/github-helpers/index.ts
  test/helpers.ts
Labels: bug

#3238 Rename `revert-file` to `restore-file`
  readme.md
  source/features/restore-file.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: meta

#3231 Meta: Minor improvements and lint
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  contributing.md
  source/features/clean-issue-filters.tsx
  source/features/latest-tag-button.tsx
  source/features/pr-branches.tsx
  source/github-helpers/dom-formatters.ts
  source/github-helpers/get-default-branch.ts
  source/github-helpers/github-url.ts
  source/github-helpers/index.ts
  test/helpers.ts
Labels: meta

#3243 Fix `default-branch-button` in "old design"
  source/features/default-branch-button.tsx
Labels: bug

#3230 Add `fork-source-link-same-view` feature
  readme.md
  source/features/fork-source-link-same-view.tsx
  source/github-helpers/does-file-exist.tsx
  source/refined-github.ts
Labels: enhancement

#3214 Add “Compare to HEAD” link next to `latest-tag-button`
  source/features/latest-tag-button.tsx
Labels: enhancement

#3158 Fix handling lazy-loaded comments
  source/github-events/on-new-comments.ts
Labels: bug

#3235 Enable `ctrl+enter` to publish the current release notes
  package-lock.json
  package.json
  source/features/create-release-shortcut.tsx
Labels: enhancement

#3233 Improve PR commit 404 page
  package-lock.json
  package.json
  source/features/patch-diff-links.tsx
  source/features/useful-not-found-page.tsx
Labels: enhancement

#3261 Make `getDefaultBranch` quicker on `isRepoHome`
  package-lock.json
  package.json
  source/github-helpers/get-default-branch.ts
Labels: enhancement

#3257 Improve `dim-bots`’s behavior
  source/features/dim-bots.css
  source/features/dim-bots.tsx
  source/features/pr-branches.tsx
Labels: bug

#3256 Lint and avoid errors
  source/features/bypass-checks.tsx
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/deep-reblame.tsx
  source/features/default-branch-button.tsx
  source/features/download-folder-button.tsx
  source/features/fit-textareas.tsx
  source/features/fork-source-link-same-view.tsx
  source/features/improve-shortcut-help.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/minimize-upload-bar.tsx
  source/features/one-key-formatting.tsx
  source/features/pr-branches.tsx
  source/features/preview-hidden-comments.tsx
  source/features/release-download-count.tsx
  source/features/selection-in-new-tab.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/tab-to-indent.tsx
  source/github-helpers/index.ts
Labels: meta

#3260 Add `pr-jump-to-first-non-viewed-file` feature
  readme.md
  source/features/pr-jump-to-first-non-viewed-file.tsx
  source/refined-github.ts
Labels: enhancement

#3251 Don't run `comments-time-machine-links` if comment is after latest commit
  source/features/comments-time-machine-links.tsx
Labels: enhancement
