Repository refined-github/refined-github, pull requests merged in 2021-06, with the labels that each got.

#4415 Fix `edit-comments-faster` to only when editing is allowed
  source/features/edit-comments-faster.tsx
Labels: bug

#3951 Drop support for the old GitHub layout
  source/features/bugs-tab.tsx
  source/features/ci-link.tsx
  source/features/clone-branch.tsx
  source/features/comments-time-machine-links.tsx
  source/features/default-branch-button.tsx
  source/features/download-folder-button.tsx
  source/features/follow-file-renames.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/more-dropdown.tsx
  source/features/pull-request-hotkey.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/set-default-repositories-type-to-sources.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/split-issue-pr-search-results.tsx
  source/features/tags-on-commits-list.tsx
  source/features/toggle-files-button.css
  source/features/toggle-files-button.tsx
Labels: enterprise, meta

#4421 Fix console error in `clean-conversation-headers`
  source/features/clean-conversation-headers.tsx
Labels: bug

#4384 Fix duplication and cropped hovercard in `user-local-time`
  source/features/user-local-time.css
  source/features/user-local-time.tsx
Labels: bug

#4443 Check for multiple related issues in `deep-reblame`
  source/features/deep-reblame.tsx
Labels: bug

#4446 `repo-wide-file-finder`: Use current branch/tag when possible
  source/features/repo-wide-file-finder.tsx
Labels: enhancement

#4447 Disable `fit-textarea` in Safari
  source/features/fit-textareas.tsx
Labels: bug, safari

#4445 Restore `clean-conversation-sidebar` feature
  source/features/clean-conversation-sidebar.tsx
Labels: bug

#4441 Enable `file-finder-buffer` everywhere
  source/features/file-finder-buffer.tsx
  source/features/repo-wide-file-finder.tsx
Labels: bug

#4444 Small bug fixes
  package-lock.json
  package.json
  source/features/convert-release-to-draft.tsx
  source/features/default-branch-button.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/latest-tag-button.tsx
  source/features/list-pr-for-branch.tsx
  source/features/list-prs-for-file.tsx
  source/features/show-whitespace.tsx
  source/helpers/add-after-branch-selector.tsx
  source/refined-github.ts
Labels: meta

#4399 Add `hide-empty-split-diff-side` feature
  readme.md
  source/features/no-useless-split-diff-view.css
  source/features/no-useless-split-diff-view.tsx
  source/refined-github.ts
Labels: enhancement

#4450 Drop `emphasize-draft-pr-label` feature
  source/features/emphasize-draft-pr-label.css
  source/refined-github.ts
Labels: implemented by github

#4469 Don't run `comments-time-machine-links` if comment is after latest commit
  source/features/comments-time-machine-links.tsx
Labels: bug

#4470 Fix `mark-merge-commits-in-list` commit hash selector
  source/features/mark-merge-commits-in-list.tsx
Labels: bug

#4458 Meta: Add issue numbers to GHE comments
  source/features/align-issue-labels.css
  source/features/center-reactions-popup.css
  source/features/ci-link.tsx
  source/features/clean-conversation-headers.css
  source/features/clean-dashboard.css
  source/features/clean-footer.css
  source/features/clean-mergeability-box.css
  source/features/deep-reblame.css
  source/features/deprioritize-marketplace-link.tsx
  source/features/easier-pr-sha-copy.css
  source/features/extend-diff-expander.css
  source/features/extend-status-labels.css
  source/features/hide-useless-comments.css
  source/features/mark-merge-commits-in-list.css
  source/features/more-dropdown.tsx
  source/features/parse-backticks.tsx
  source/features/pr-approvals-count.css
  source/features/table-input.css
  source/features/useful-not-found-page.tsx
  source/features/wait-for-build.css
  source/refined-github.css
Labels: meta

#4453 Disable `swap-branches-on-compare` in direct comparison
  source/features/swap-branches-on-compare.tsx
Labels: bug

#4475 Fix `prevent-link-loss` warning message copy
  source/features/prevent-link-loss.tsx
Labels: bug

#4476 Fix very small images in `reaction-avatars`
  source/features/reactions-avatars.css
Labels: bug

#4474 Improve support for branches with periods and slashes
  source/github-helpers/index.ts
  test/get-current-committish.ts
Labels: bug

#4478 Fix: Submodule diffs are misaligned
  source/refined-github.css
Labels: bug

#4495 Meta: Add workflow that verifies new feature PRs
  .github/workflows/features.yml
  build/readme-parser.ts
  webpack.config.ts
Labels: meta

#4467 Add `cancel-wiki-edit-button` feature
  .github/workflows/features.yml
  readme.md
  source/features/cancel-wiki-edit-button.tsx
  source/refined-github.ts
Labels: enhancement

#4494 Fix `no-useless-split-diff-view` doesn't work newly loaded files
  source/features/hidden-review-comments-indicator.tsx
  source/features/no-useless-split-diff-view.tsx
  source/features/show-whitespace.tsx
  source/github-events/on-diff-file-load.ts
Labels: bug

#4497 Remove `open-issue-to-latest-comment` from the dashboard
  source/features/open-issue-to-latest-comment.tsx
Labels: change request

#4502 Ensure the dropdown loaded in `git-checkout-pr`
  source/features/git-checkout-pr.tsx
Labels: bug

#4521 Fix: Milestone is shown red on PR lists when it contains word "changes"
  source/features/pr-approvals-count.css
Labels: bug
