Repository refined-github/refined-github, pull requests merged in 2021-10, with the labels that each got.

#4833 Follow the user’s tab-size setting where possible
  source/features/show-whitespace.css
  source/refined-github.css
Labels: bug

#4819 Clean up more `parse-backticks` selectors
  source/features/parse-backticks.tsx
Labels: help wanted

#4818 Meta: Fix `rgh-feature-descriptions` feature
  source/features/rgh-feature-descriptions.tsx
Labels: bug, meta

#4842 Fix `clean-dashboard`’s background color
  source/features/clean-dashboard.css
  source/refined-github.css
Labels: bug

#4850 Fix `hide-low-quality-comments` style
  source/features/hide-low-quality-comments.css
  source/options.css
  source/refined-github.css
Labels: bug

#4852 Meta: Improve lack of token scopes message
  source/features/show-whitespace.css
  source/github-helpers/api.ts
Labels: meta

#4851 Fix inconsistent `show-names` color
  source/features/show-names.tsx
Labels: bug

#4858 Improve reliability of `reactions-avatar`
  source/features/reactions-avatars.tsx
Labels: bug

#4864 Drop fallback code for old GitHub Enterprise versions
  source/features/action-used-by-link.tsx
  source/features/align-issue-labels.css
  source/features/center-reactions-popup.css
  source/features/clean-conversation-headers.css
  source/features/clean-dashboard.css
  source/features/clean-footer.css
  source/features/clean-mergeability-box.css
  source/features/clean-repo-sidebar.tsx
  source/features/clone-branch.tsx
  source/features/conflict-marker.tsx
  source/features/conversation-links-on-repo-lists.tsx
  source/features/convert-pr-to-draft-improvements.tsx
  source/features/deep-reblame.css
  source/features/easier-pr-sha-copy.css
  source/features/extend-diff-expander.css
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/git-checkout-pr.tsx
  source/features/hide-low-quality-comments.css
  source/features/highest-rated-comment.tsx
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/link-to-changelog-file.tsx
  source/features/linkify-user-edit-history-popup.tsx
  source/features/list-pr-for-branch.tsx
  source/features/mark-merge-commits-in-list.css
  source/features/parse-backticks.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-approvals-count.css
  source/features/pr-commit-lines-changed.tsx
  source/features/quick-comment-hiding.tsx
  source/features/quick-pr-diff-options.tsx
  source/features/quick-review.tsx
  source/features/release-download-count.tsx
  source/features/repo-age.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/table-input.css
  source/features/tag-changelog-link.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-local-time.tsx
  source/features/user-profile-follower-badge.tsx
  source/features/wait-for-build.css
  source/options-storage.ts
  source/refined-github.css
Labels: enterprise

#4856 Run `show-whitespace` on code blocks but not diff headers
  source/features/show-whitespace.tsx
Labels: enhancement

#4859 Fix `quick-mention` on review events
  source/features/quick-mention.tsx
Labels: bug

#4866 Fix: Margin missing sometimes in the PR sidebar
  source/features/clean-repo-sidebar.css
Labels: bug

#4853 Don't leave menu open in `quick-comment-hiding`
  source/features/quick-comment-hiding.tsx
Labels: bug

#4877 Fix CI annotations in `no-unnecessary-split-diff-view`
  source/features/no-unnecessary-split-diff-view.css
Labels: bug

#4876 Fix missing spaces in `show-names`
  source/features/show-names.tsx
Labels: bug

#4982 Fix GitHub color variables
  source/features/clean-dashboard.css
  source/features/conflict-marker.css
  source/features/emphasize-draft-pr-label.css
  source/features/file-finder-buffer.tsx
  source/features/hide-low-quality-comments.css
  source/features/highlight-collaborators-and-own-conversations.css
  source/features/mark-merge-commits-in-list.css
  source/features/quick-label-removal.css
  source/features/quick-pr-diff-options.tsx
  source/features/select-notifications.tsx
  source/features/useful-not-found-page.tsx
  source/options-storage.ts
  source/refined-github.css
Labels: bug

#4996 Drop `monospace-textareas` feature
  readme.md
  source/features/github-bugs.css
  source/features/monospace-textareas.css
  source/features/monospace-textareas.tsx
  source/refined-github.css
  source/refined-github.ts
Labels: implemented by github

#5013 Fix selector for commit title input width
  source/refined-github.css
Labels: bug

#5011 Better keep track of renamed features
  source/features/rgh-feature-descriptions.tsx
  source/features/rgh-linkify-features.tsx
  source/options-storage.ts
  source/options.tsx
Labels: bug, meta

#4986 Sort projects by update time
  source/features/sort-conversations-by-update-time.tsx
Labels: enhancement

#5012 Fix `sticky-sidebar` on repo root
  source/features/clean-repo-sidebar.css
  source/features/sticky-sidebar.tsx
Labels: bug

#5021 Use new background color variables
  source/features/clean-dashboard.css
  source/features/clean-mergeability-box.css
  source/features/clean-pinned-issues.css
  source/features/emphasize-draft-pr-label.css
  source/features/hide-low-quality-comments.css
  source/features/highest-rated-comment.css
  source/features/pr-approvals-count.css
  source/features/quick-label-removal.css
  source/features/suggest-commit-title-limit.css
  source/features/table-input.css
  source/options.css
  source/refined-github.css
Labels: bug

#5022 Avoid duplicating native button in `quick-pr-diff-options`
  source/features/quick-pr-diff-options.tsx
Labels: bug

#4973 Tweak `reactions-avatars` style
  source/features/reactions-avatars.css
  source/features/reactions-avatars.tsx
Labels: enhancement

#5017 Improve usability of `quick-review-buttons`
  source/features/quick-review-buttons.tsx
Labels: change request

#5030 Fix `tags-dropdown` and `tag-changes-link` after first tags page
  package-lock.json
  package.json
  source/features/tag-changes-link.tsx
  source/features/tags-dropdown.tsx
Labels: bug

#5028 Prevent `quick-file-edit` links from being AJAXed
  source/features/quick-file-edit.tsx
Labels: bug
