Repository refined-github/refined-github, pull requests merged in 2021-02, with the labels that each got.

#3924 Meta: Specify required Node version in docs and in nvmrc
  .nvmrc
  contributing.md
Labels: meta

#3931 Move `update-pr-from-base-branch` to a more reliable position
  readme.md
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#3933 Meta: Drop local release dependencies
  .github/workflows/release.yml
  contributing.md
  package-lock.json
  package.json
Labels: meta

#3939 Fix `table-input` at 90% zoom
  source/features/table-input.css
Labels: bug

#3935 Don't `list-prs-for-file` while you're editing the same PR
  source/features/list-prs-for-file.tsx
Labels: bug

#3944 Fix merged button text in `extend-conversation-status-filters`
  source/features/extend-conversation-status-filters.tsx
Labels: bug

#3947 Make `latest-tag-button` more reliable
  source/features/latest-tag-button.tsx
Labels: bug

#3946 Fix console error in `list-prs-for-file`
  source/features/list-prs-for-file.tsx
Labels: bug

#3956 Ensure `update-pr-from-base-branch` is always clickable
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#3962 Fix `more-dropdown` on GHE
  source/features/more-dropdown.tsx
Labels: bug

#3952 Move `download-folder-button` to the dropdown
  source/features/download-folder-button.tsx
Labels: enhancement

#3955 Add `useful-forks` feature
  package-lock.json
  package.json
  readme.md
  source/features/useful-forks.tsx
  source/refined-github.ts
Labels: enhancement

#3958 Add `link-to-changelog-file` feature
  readme.md
  source/features/link-to-changelog-file.tsx
  source/refined-github.ts
Labels: enhancement

#3976 Meta: Fix small typos in readme
  readme.md
Labels: meta

#3886 Add `wait-for-attachments` feature
  readme.md
  source/features/wait-for-attachments.ts
  source/refined-github.ts
Labels: enhancement

#3977 Enable `parse-backticks` on Discussions
  source/features/parse-backticks.tsx
Labels: enhancement

#3983 Update some readme links
  contributing.md
  readme.md
Labels: meta

#3973 Update dependencies
  package-lock.json
  package.json
  source/features/bugs-tab.tsx
  source/features/collapsible-content-button.tsx
  source/features/fit-textareas.tsx
  source/features/tags-on-commits-list.tsx
  source/github-events/on-new-comments.ts
  source/options-storage.ts
  webpack.config.ts
Labels: meta

#3982 Keep diff stats in "Jump to" dropdown when header is fixed
  source/refined-github.css
Labels: enhancement

#3986 Add `preview-markdown-result` feature
  readme.md
  source/features/preview-markdown-result.css
  source/features/preview-markdown-result.tsx
  source/refined-github.ts
Labels: enhancement

#3991 Ignore triple-backtick blocks in `parse-backticks`
  source/github-helpers/parse-backticks.tsx
  test/helpers.ts
  test/parse-backticks.ts
Labels: bug

#3989 Make `quick-repo-deletion` success message more helpful
  package-lock.json
  package.json
  source/features/quick-repo-deletion.tsx
Labels: enhancement

#3992 Hide and auto-expand Similar comments in `hide-useless-comments`
  source/features/hide-useless-comments.tsx
Labels: enhancement

#3996 Preserve `sticky-sidebar` after a new comment
  package-lock.json
  package.json
  source/features/sticky-sidebar.tsx
  source/helpers/on-element-removal.ts
Labels: enhancement

#3993 Detect more comments in `hide-useless-comments`
  source/helpers/useless-comments.ts
  test/helpers.ts
Labels: enhancement

#4003 Improve GitHub Sponsors UX
  source/features/rgh-sponsor-button.tsx
  source/refined-github.ts
Labels: enhancement

#4006 Fix position of `latest-tag-button`
  source/features/latest-tag-button.tsx
Labels: bug

#4005 Support more filenames in `link-to-changelog-file`
  source/features/link-to-changelog-file.tsx
Labels: enhancement

#4002 Meta: Drop Rollup from tests
  .gitignore
  .xo-config.js
  .xo-config.json
  package-lock.json
  package.json
  tsconfig.json
Labels: meta

#3974 Improve `clean-repo-sidebar`
  readme.md
  source/features/clean-repo-sidebar.css
  source/features/clean-repo-sidebar.tsx
  source/features/repo-age.tsx
Labels: enhancement

#4010 Meta: Simplify magic variables and avoid possible duplicate injection
  .xo-config.json
  source/features/index.tsx
  source/features/rgh-feature-descriptions.tsx
  source/globals.d.ts
  source/options-storage.ts
  webpack.config.ts
Labels: meta

#3988 Avoid `master` noise in `clean-conversation-headers`
  package-lock.json
  package.json
  source/features/clean-conversation-headers.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/git-checkout-pr.tsx
Labels: enhancement

#4009 Meta: Linkify RG’s own features on this repo via `rgh-linkify-features`
  source/features/format-conversation-titles.tsx
  source/features/rgh-linkify-features.tsx
  source/github-helpers/index.ts
  source/refined-github.ts
Labels: meta

#4014 Fix console error in `clean-conversation-headers`
  source/features/clean-conversation-headers.tsx
Labels: bug

#4011 Fix console error in `sticky-sidebar`
  source/features/sticky-sidebar.tsx
Labels: bug

#4013 Fix `hide-useless-comments` selectors
  source/features/hide-useless-comments.tsx
Labels: bug

#3995 Improve reliability of `clean-repo-filelist-actions`
  readme.md
  source/features/clean-repo-filelist-actions.tsx
Labels: enhancement

#4020 Meta: Move new features to the top on the Options page
  source/options.tsx
Labels: meta

#4019 Meta: Cleanup the options page
  distribution/options.html
  source/options.tsx
Labels: meta

#4021 Fix several features that depended on specific classes
  source/features/align-issue-labels.css
  source/features/batch-open-conversations.tsx
  source/features/center-reactions-popup.css
  source/features/clean-dashboard.css
  source/features/clean-repo-sidebar.tsx
  source/features/conversation-links-on-repo-lists.tsx
  source/features/convert-pr-to-draft-improvements.tsx
  source/features/easier-pr-sha-copy.css
  source/features/faster-reviews.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/linkify-user-edit-history-popup.tsx
  source/features/open-issue-to-latest-comment.tsx
  source/features/parse-backticks.tsx
  source/features/pr-approvals-count.css
  source/features/repo-age.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/tag-changelog-link.tsx
  source/options-storage.ts
  source/refined-github.css
Labels: bug

#4034 Correctly display `hide-comments-faster` on small viewports
  source/features/hide-comments-faster.tsx
Labels: bug

#4028 Hide `useful-forks` on GitHub Enterprise
  source/features/useful-forks.tsx
Labels: bug, enterprise

#4036 Meta: Simplify Octicons usage
  package-lock.json
  package.json
  webpack.config.ts
Labels: meta

#4038 Fix more features dependent on `.link-gray`, `.text-gray` and their variants
  source/features/action-used-by-link.tsx
  source/features/batch-open-conversations.tsx
  source/features/clone-branch.tsx
  source/features/conflict-marker.tsx
  source/features/faster-pr-diff-options.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/git-checkout-pr.tsx
  source/features/hide-comments-faster.tsx
  source/features/highest-rated-comment.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/release-download-count.tsx
  source/features/repo-age.tsx
  source/features/rgh-feature-descriptions.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/user-local-time.tsx
  source/features/user-profile-follower-badge.tsx
  source/options-storage.ts
Labels: bug
