Repository refined-github/refined-github, pull requests merged in 2021-09, with the labels that each got.

#4723 Meta: Replace the word "useless" with more specific descriptions
  readme.md
  source/features/clean-repo-sidebar.tsx
  source/features/hide-low-quality-comments.css
  source/features/hide-low-quality-comments.tsx
  source/features/hide-noisy-newsfeed-events.css
  source/features/hide-noisy-newsfeed-events.tsx
  source/features/no-unnecessary-split-diff-view.css
  source/features/no-unnecessary-split-diff-view.tsx
  source/features/unwrap-unnecessary-dropdowns.tsx
  source/helpers/is-low-quality-comment.ts
  source/options-storage.ts
  source/refined-github.ts
  test/is-low-quality-comment.ts
  test/is-useless-comment.ts
Labels: meta

#4735 Drop `patch-diff-links` font size modification
  source/features/patch-diff-links.css
  source/features/patch-diff-links.tsx
Labels: bug

#4728 Restore `emphasize-draft-pr-label` feature
  source/features/emphasize-draft-pr-label.css
  source/refined-github.ts
Labels: enhancement

#4756 Add missing space to `profile-gists-link`
  source/features/profile-gists-link.tsx
Labels: bug

#4725 Meta: Catch orphaned CSS files on CI
  build/verify-features.ts
  source/refined-github.ts
Labels: meta

#4764 Meta: Make classes and feature names consistent
  source/features/hide-low-quality-comments.tsx
  source/features/hide-noisy-newsfeed-events.css
  source/features/hide-tips.css
  source/features/open-all-notifications.tsx
Labels: meta

#4769 Match `file-finder-buffer` style with GitHub
  source/features/file-finder-buffer.tsx
Labels: bug

#4776 Don't `follow-file-renames` when file was not renamed
  source/features/follow-file-renames.tsx
Labels: bug

#4777 Meta: Ensure the body loaded before bisecting
  source/helpers/bisect.tsx
Labels: bug

#4775 Enable `reactions-avatars` on more pages
  source/features/reactions-avatars.tsx
Labels: enhancement

#4794 Fix options page on iOS Safari
  .github/workflows/release.yml
  safari/Shared (App)/Base.lproj/Main.html
  source/options.css
Labels: safari

#4792 Add support for `rst` files to `view-markdown-source`
  source/features/view-markdown-source.tsx
Labels: enhancement

#4798 Fix: "Done" click is ignored when `select-notifications` is open
  source/features/select-notifications.css
  source/features/select-notifications.tsx
Labels: bug

#4804 Meta: Drop "Feature history" dropdown
  source/features/rgh-feature-descriptions.tsx
Labels: meta

#4796 Fix: `edit-comments-faster` appears on every comment
  source/features/quick-comment-edit.tsx
Labels: bug

#4803 Use safer saving mechanism in `restore-file`
  source/features/restore-file.tsx
  source/github-helpers/api.ts
Labels: enhancement

#4800 Meta: Add an `asLongAs` option to `features.add()`
  contributing.md
  source/features/comment-on-draft-pr-indicator.tsx
  source/features/comments-time-machine-links.tsx
  source/features/copy-file.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/fork-source-link-same-view.tsx
  source/features/index.tsx
  source/features/link-to-github-io.tsx
  source/features/no-duplicate-list-update-time.tsx
  source/features/no-unnecessary-split-diff-view.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/useful-not-found-page.tsx
  source/features/view-last-pr-deployment.tsx
  source/features/wait-for-build.tsx
  source/github-helpers/index.ts
  test/helpers.ts
Labels: meta

#4772 Improve styles of several PR features to blend in better
  source/features/git-checkout-pr.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/latest-tag-button.tsx
  source/features/list-pr-for-branch.tsx
  source/features/list-prs-for-file.tsx
  source/features/monospace-textareas.css
  source/features/parse-backticks.css
  source/features/quick-pr-diff-options.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/options.css
Labels: bug

#4816 Meta: Improve `conversation-activity-filter` labels
  source/features/conversation-activity-filter.tsx
Labels: enhancement

#4799 Fix: `select-notifications` disappears after clicking "Done"
  source/features/select-notifications.tsx
Labels: enhancement
