Repository refined-github/refined-github, pull requests merged in 2021-11, with the labels that each got.

#5034 Fix missing margin caused by `clean-dashboard`
  source/features/clean-dashboard.css
Labels: bug

#5027 Fix `clean-repo-sidebar` and `sticky-sidebar` top margin
  source/features/clean-repo-sidebar.css
  source/features/sticky-sidebar.css
Labels: bug

#5035 Limit width of comment form on commit pages
  source/features/github-bugs.css
Labels: bug

#5031 Hide duplicate `quick-pr-diff-options` buttons on commit and compare pages
  source/features/quick-pr-diff-options.tsx
Labels: bug

#5042 Meta: Delete hotfix.json
  README.md
  hotfix.json
Labels: meta

#5044 Make "Marketplace" menu item focusable via keyboard
  source/features/deprioritize-marketplace-link.tsx
Labels: enhancement

#5049 Meta: drop magic globals in favor of `import`ing the readme
  .xo-config.json
  build/readme.loader.cts
  source/features/index.tsx
  source/features/rgh-feature-descriptions.tsx
  source/features/rgh-linkify-features.tsx
  source/globals.d.ts
  source/helpers/bisect.tsx
  source/options-storage.ts
  source/options.tsx
  webpack.config.ts
Labels: meta

#4918 Meta: Refactor custom tab highlighting
  source/features/bugs-tab.tsx
  source/features/releases-tab.tsx
  source/helpers/dom-utils.ts
Labels: meta

#5057 Fix `tag-changes-link` for tags without release
  source/features/tag-changes-link.tsx
Labels: bug

#5054 Fix order of actions in `quick-review-buttons`
  source/features/quick-review-buttons.tsx
Labels: bug

#5036 Lint
  package-lock.json
  package.json
  source/features/bugs-tab.tsx
  source/features/conversation-filters.tsx
  source/features/esc-to-deselect-line.tsx
  source/features/global-conversation-list-filters.tsx
  source/features/global-search-filters.tsx
  source/features/open-all-conversations.tsx
  source/features/open-all-notifications.tsx
  source/features/show-names.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/sort-conversations-by-update-time.tsx
  source/features/tag-changes-link.tsx
  source/github-helpers/search-query.ts
Labels: meta

#5059 Meta: Don't store entire workflow files in cache
  source/features/clean-repo-tabs.tsx
  source/features/scheduled-and-manual-workflow-indicators.tsx
Labels: meta

#5067 Fix: `user-local-time` breaks positioning of some hovercards
  source/features/user-local-time.css
  source/features/user-local-time.tsx
Labels: bug

#5060 Fix implementation of hotfixes
  source/background.ts
  source/features/index.tsx
  source/helpers/hotfix.ts
  source/options.tsx
Labels: bug, meta

#5065 Fix `highest-rated-comment` checkmark misalignment
  source/features/highest-rated-comment.tsx
Labels: bug

#5055 Meta: Ensure features are described only once in the readme
  build/readme-parser.ts
  build/verify-features.ts
Labels: meta

#5084 Meta: Improve readme parsing
  build/readme-parser.ts
  build/verify-features.ts
  readme.md
Labels: meta

#5073 Preserve name of other repos in `prevent-pr-commit-link-loss`
  source/github-helpers/prevent-link-loss.ts
  test/prevent-link-loss.ts
Labels: bug

#5072 Fix: `conversation-activity-filter` doesn't reset its state when navigating
  source/features/conversation-activity-filter.tsx
Labels: bug

#5099 Fix selector in `wait-for-build`
  source/github-helpers/pr-ci-status.ts
Labels: bug

#5097 Fix `show-whitespace` hanging on very long lines
  source/features/show-whitespace.tsx
Labels: bug

#5100 Fix `bugs-tab` where the emoji contains a dash
  source/features/bugs-tab.tsx
Labels: bug

#5101 Fix "Yours" filter in `global-search-filters`
  source/features/global-search-filters.tsx
Labels: bug

#5095 Fix some missing editor features when editing comments
  source/features/collapsible-content-button.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/minimize-upload-bar.css
  source/features/no-unnecessary-split-diff-view.tsx
  source/features/show-whitespace.tsx
  source/features/table-input.tsx
  source/github-events/on-fragment-load.ts
Labels: bug, meta

#5094 Fix `highlight-deleted-and-added-files-in-diffs` on compare page
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/github-events/on-fragment-load.ts
Labels: bug

#5033 Meta: Extend `rgh-linkify-features` to more places
  source/features/rgh-feature-descriptions.tsx
  source/features/rgh-linkify-features.tsx
  source/github-helpers/index.ts
  source/helpers/bisect.tsx
  source/helpers/feature-link.ts
  source/options-storage.ts
  source/options.tsx
Labels: meta

#5096 Skip `useful-not-found-page` on pages that never exist
  source/features/useful-not-found-page.tsx
Labels: bug

#5105 Enable `one-key-formatting` on more places
  source/features/one-key-formatting.tsx
  source/github-events/on-field-keydown.tsx
Labels: enhancement

#5104 Disable the checkbox of hotfixed features
  source/options.css
  source/options.tsx
Labels: enhancement, meta

#5078 Fix `conversation-filters` showing multiple checked marks
  source/features/conversation-filters.tsx
Labels: bug

#5103 Fix the feature list in the options page
  build/readme-parser.ts
  build/readme.loader.cts
  build/verify-features.ts
  source/globals.d.ts
  source/helpers/bisect.tsx
  source/options-storage.ts
  source/options.tsx
Labels: bug, meta

#5102 Fix `conversation-activity-filter` sometimes failing
  source/features/conversation-activity-filter.tsx
Labels: bug

#5091 Fix broken "Details" links in PR checks due to `bypass-checks`
  source/features/bypass-checks.tsx
Labels: bug

#5109 Meta: Avoid unnecessary calls in diff load listeners
  source/github-events/on-fragment-load.ts
Labels: bug, meta

#5121 Fix duplicated features on global conversation list
  source/features/conflict-marker.tsx
  source/features/open-all-conversations.tsx
Labels: bug

#5122 Fix tab deletion in `new-repo-disable-projects-and-wikis`
  source/features/new-repo-disable-projects-and-wikis.tsx
Labels: bug

#5123 Fix `unfinished-comments` on new issue templates
  source/features/unfinished-comments.tsx
Labels: bug

#5079 Fix `preview-hidden-comments` preview text after hiding comment
  source/features/preview-hidden-comments.tsx
Labels: bug

#5127 Fix `quick-pr-diff-options` on GHE
  source/features/quick-pr-diff-options.tsx
Labels: bug, enterprise

#5098 Fix alignment of "Code of conduct" link in `clean-repo-sidebar`
  source/features/clean-repo-sidebar.tsx
Labels: bug

#5129 Fix `quick-pr-diff-options` on compare pages
  source/features/quick-pr-diff-options.tsx
Labels: bug

#5125 Hide badges in repo headers and pinned repo cards
  source/features/ci-link.css
  source/refined-github.css
Labels: enhancement

#5119 Fix `use-first-commit-message-for-new-prs`
  source/features/use-first-commit-message-for-new-prs.tsx
Labels: bug

#5132 Show error toast when `quick-label-removal` fails
  source/features/quick-label-removal.tsx
  source/github-helpers/toast.tsx
Labels: bug, meta
