Repository refined-github/refined-github, pull requests merged in 2021-12, with the labels that each got.

#5128 Move footer to right side when enabling `infinite-scroll`
  source/features/clean-footer.css
  source/features/infinite-scroll.tsx
Labels: enhancement

#5140 Fix Code of conduct link hiding in `clean-repo-sidebar`
  source/features/clean-conversation-sidebar.css
  source/features/clean-conversation-sidebar.tsx
  source/features/clean-repo-sidebar.css
Labels: bug

#5149 Fix `release-download-count` feature
  source/features/release-download-count.tsx
Labels: bug

#5154 Drop `trending-menu-item` feature
  readme.md
  source/features/trending-menu-item.tsx
  source/refined-github.ts
Labels: change request

#5153 Drop `deprioritize-marketplace-link` feature
  readme.md
  source/features/deprioritize-marketplace-link.tsx
  source/refined-github.ts
Labels: change request

#5146 Restore `hide-inactive-deployments`
  source/features/hide-inactive-deployments.tsx
Labels: bug

#5159 Hide trailing separator in PR and commit files dropdown
  source/features/github-bugs.css
Labels: enhancement

#5117 Disable `quick-mention` on reviews without a comment
  source/features/quick-mention.tsx
Labels: bug

#5136 Fix `previous-next-commit-buttons` on condensed commit views
  source/features/previous-next-commit-buttons.tsx
Labels: bug

#5124 Drop `hide-obvious-tooltips`
  readme.md
  source/features/hide-obvious-tooltips.css
  source/refined-github.ts
Labels: change request

#5156 Use emoji in `unfinished-comments`
  source/features/unfinished-comments.tsx
Labels: change request

#5166 Fix option saving in Safari
  source/options.tsx
Labels: bug, safari

#5113 Lint
  package.json
  source/features/clean-conversation-filters.tsx
  source/features/clean-conversations.css
  source/features/clean-rich-text-editor.tsx
  source/features/file-finder-buffer.tsx
  source/features/github-bugs.css
  source/features/index.tsx
  source/features/latest-tag-button.tsx
  source/features/linkify-branch-references.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/rgh-feature-descriptions.tsx
  source/features/show-open-prs-of-forks.tsx
  source/github-helpers/get-default-branch.ts
  source/helpers/hotfix.ts
Labels: meta

#5180 Update dependencies
  .xo-config.json
  package-lock.json
  package.json
  safari/Shared (App)/Resources/Script.js
  source/features/bugs-tab.tsx
  source/features/clean-repo-sidebar.tsx
  source/features/submit-review-as-single-comment.tsx
  source/features/use-first-commit-message-for-new-prs.tsx
Labels: meta

#5167 Meta: Linkify welcome issue to open options page + clean it up
  source/background.ts
  source/features/rgh-welcome-issue.css
  source/features/rgh-welcome-issue.tsx
  source/github-helpers/prevent-link-loss.ts
  source/refined-github.ts
Labels: meta

#5187 Meta: remove obsolete related projects
  readme.md
Labels: meta

#5151 Extend `raw-file-link` to `more-file-links`
  readme.md
  source/features/more-file-links.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: enhancement

#5106 Fix `show-whitespace` on newly sent suggestions
  source/features/show-whitespace.tsx
  source/globals.d.ts
Labels: bug

#5193 Fix duplication in `comment-on-draft-pr-indicator`
  source/features/comment-on-draft-pr-indicator.tsx
Labels: bug

#5175 Meta: Automatically label commits in releases
  .github/release.yml
Labels: meta

#5192 Detect more bots in `dim-bots`
  source/features/dim-bots.tsx
Labels: enhancement

#5150 Fix `reactions-avatars` on releases and review comments
  source/features/reactions-avatars.tsx
Labels: bug

#5090 Fix `sort-conversations-by-update-time` on conversation filters
  source/features/sort-conversations-by-update-time.tsx
Labels: bug

#5195 Fix `user-profile-follower-badge` feature
  source/features/user-profile-follower-badge.tsx
Labels: bug

#5199 Update `repo-age` and `clean-repo-sidebar` spacing
  source/features/clean-repo-sidebar.tsx
  source/features/repo-age.tsx
Labels: enhancement

#5198 Delay `dim-bots` after hover
  source/features/dim-bots.css
  source/features/dim-bots.tsx
Labels: change request

#5197 Restore `hide-watch-and-fork-count`
  source/features/hide-watch-and-fork-count.css
  source/features/hide-watch-and-fork-count.tsx
  source/refined-github.ts
Labels: bug

#5074 Fix handling of "Code" button in `clean-repo-filelist-actions`
  source/features/clean-repo-filelist-actions.tsx
Labels: bug

#5207 Enable `clean-rich-text-editor` on Gist pages
  source/features/clean-rich-text-editor.tsx
Labels: enhancement

#5208 Meta: Fix silencing of console errors when logged out
  source/features/index.tsx
Labels: bug, meta

#5213 Meta: Replace `deinit` option with `init` return value
  contributing.md
  source/features/batch-mark-files-as-viewed.tsx
  source/features/copy-on-y.tsx
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/index.tsx
  source/features/quick-review-comment-deletion.tsx
  source/features/releases-tab.tsx
  source/features/select-notifications.tsx
  source/features/sticky-sidebar.tsx
  source/features/wait-for-build.tsx
Labels: meta

#5209 Restore monospace font in commit and merge title fields
  source/features/github-bugs.css
Labels: bug, enhancement

#5218 Fix "unclickable Stars dropdown" bug
  source/features/sticky-sidebar.css
  source/features/sticky-sidebar.tsx
Labels: bug

#5219 Properly hide new starring dropdown in `clean-dashboard`
  source/features/clean-dashboard.css
Labels: bug

#5217 Drop `submit-review-as-single-comment` feature
  readme.md
  source/features/submit-review-as-single-comment.tsx
  source/refined-github.ts
Labels: change request

#5224 Meta: Correctly display "token missing" errors in `bugs-tab`
  source/features/bugs-tab.tsx
Labels: bug

#5226 Fix `useful-forks` and `quick-repo-deletion` selectors
  source/features/quick-repo-deletion.tsx
  source/features/useful-forks.tsx
Labels: bug

#5211 Fix handling of slashed branches in some commits list features
  source/features/list-prs-for-branch.tsx
  source/github-helpers/index.ts
  test/get-current-committish.ts
Labels: bug

#5194 Enable `sort-conversations-by-update-time` on label links
  source/features/sort-conversations-by-update-time.tsx
  source/github-helpers/search-query.ts
Labels: bug

#5212 Meta: Clarify feature names
  readme.md
  source/features/more-conversation-filters.tsx
  source/features/one-click-diff-options.tsx
  source/features/one-click-review-submission.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: meta

#5223 Meta: Automatically generate release again
  .github/workflows/release.yml
Labels: meta

#5210 Fix `conversation-activity-filter` hiding unresolved comments
  source/features/conversation-activity-filter.tsx
Labels: bug

#5220 Drop `view-markdown-source` feature
  readme.md
  source/features/view-markdown-source.tsx
  source/globals.d.ts
  source/refined-github.ts
Labels: change request

#5200 Restore `forked-to` feature
  source/features/forked-to.tsx
Labels: bug

#5196 Fix `hide-tips` CSS feature
  source/features/hide-tips.css
Labels: bug

#5221 Fix GitHub bug: PR lists wrap multiple times sometimes
  source/features/github-bugs.css
Labels: enhancement

#5206 Meta: Fix indentation of stack trace in issue links
  source/features/index.tsx
Labels: bug, meta

#5231 Fix: The welcome page isn't opened on Safari
  source/background.ts
  source/features/index.tsx
  source/helpers/hotfix.ts
  source/helpers/is-development-version.ts
  source/options.tsx
Labels: bug

#5230 Meta: Don't call init function directly in additional listeners
  source/features/clean-conversation-sidebar.tsx
  source/features/quick-review.tsx
Labels: bug, meta

#5229 Enable `hide-diff-signs` on file edition pages
  source/features/hide-diff-signs.tsx
Labels: enhancement

#5227 Meta: Default selectors to `HTMLElement` type
  source/features/batch-mark-files-as-viewed.tsx
  source/features/clean-conversation-headers.tsx
  source/features/clean-repo-sidebar.tsx
  source/features/easy-toggle-files.tsx
  source/features/hide-low-quality-comments.tsx
  source/features/highest-rated-comment.tsx
  source/features/linkify-branch-references.tsx
  source/helpers/types.d.ts
  source/refined-github.ts
Labels: meta

#5203 Meta: Allow setting local dev team
  .github/workflows/test.yml
  .gitignore
  safari/Config.xcconfig
  safari/Refined GitHub.xcodeproj/project.pbxproj
Labels: meta

#5237 Fix deduplication of `list-prs-for-file` feature
  source/features/list-prs-for-file.tsx
Labels: bug

#5245 Meta: Move small bug report fields higher
  .github/ISSUE_TEMPLATE/1_bug_report.yml
Labels: help wanted, meta

#5249 Fix alignment of `latest-tag-button` & `list-prs-for-file` icons
  source/features/latest-tag-button.tsx
  source/features/list-prs-for-file.tsx
Labels: bug

#5253 Meta: Automatically hide resolved comments on minor fixes issues
  source/features/conversation-activity-filter.tsx
Labels: meta
