Repository refined-github/refined-github, pull requests merged in 2022-04, with the labels that each got.

#5549 Fix console errors in PR merging box features
  source/features/suggest-commit-title-limit.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/wait-for-checks.tsx
  source/github-events/on-fragment-load.ts
  source/github-events/on-pr-commit-message-restore.ts
  source/github-events/on-pr-merge-panel-open.ts
Labels: bug, meta

#5570 Fix: `stop-pjax-loading-with-esc` stopped working
  source/features/stop-pjax-loading-with-esc.tsx
Labels: bug

#5544 Prevent `dim-bots` error on empty milestone list
  package-lock.json
  package.json
  source/features/conflict-marker.tsx
  source/features/dim-bots.tsx
  source/features/warn-pr-from-master.tsx
Labels: bug, meta

#5571 Exclude low quality comments from `highest-rated-comment`
  source/features/hide-low-quality-comments.tsx
  source/features/highest-rated-comment.tsx
Labels: change request

#5562 Show explicitly linked comment in `conversation-activity-filter`
  source/features/conversation-activity-filter.tsx
Labels: enhancement

#5575 Fix clean-up of observers used by features
  source/features/hidden-review-comments-indicator.tsx
  source/features/linkify-branch-references.tsx
  source/features/releases-tab.tsx
  source/features/show-whitespace.tsx
  source/features/update-pr-from-base-branch.tsx
  source/github-events/on-conversation-header-update.ts
  source/github-events/on-file-list-update.ts
  source/github-events/on-new-comments.ts
  source/helpers/get-deinit-handler.ts
Labels: bug, meta

#5578 Restore `file-finder-buffer` feature
  source/features/file-finder-buffer.tsx
Labels: bug

#5583 Fix `hide-repo-badges` feature
  source/features/hide-repo-badges.css
Labels: bug

#5580 Fix position and duplication of `quick-comment-edit` button
  readme.md
  source/features/quick-comment-edit.tsx
Labels: bug

#5582 Improve `conversation-activity-filter` for PR conversations
  source/features/conversation-activity-filter.css
  source/features/conversation-activity-filter.tsx
Labels: enhancement, change request

#5322 Improve reliability of `clean-conversation-headers`
  source/features/clean-conversation-headers.css
  source/features/clean-conversation-headers.tsx
  source/features/conversation-activity-filter.css
  source/features/conversation-activity-filter.tsx
  source/features/first-published-tag-for-merged-pr.tsx
Labels: bug, enhancement

#5579 Fix `follow-file-renames` feature
  source/features/follow-file-renames.tsx
Labels: bug

#5588 Fix slowdown caused by `select-all-notifications-shortcut`
  source/features/select-all-notifications-shortcut.tsx
Labels: bug

#5591 Meta: Move some test modules into `source` folder
  package.json
  source/github-helpers/github-url.test.ts
  source/github-helpers/index.test.ts
  source/github-helpers/parse-backticks.test.ts
  source/github-helpers/prevent-link-loss.test.ts
  source/github-helpers/search-query.test.ts
  source/helpers/is-low-quality-comment.test.ts
  source/helpers/loose-parse-int.test.ts
  source/helpers/pluralize.test.ts
Labels: meta

#5594 Fix left padding of `quick-comment-edit` button
  source/features/quick-comment-edit.tsx
Labels: bug

#5600 Fix and extend `safer-destructive-actions` on Discussions
  source/features/safer-destructive-actions.css
Labels: bug, enhancement

#5599 Restore `quick-comment-edit` on Discussions
  source/features/quick-comment-edit.tsx
Labels: bug

#5587 Allow `batch-mark-files-as-viewed` to mark all files from first
  source/features/batch-mark-files-as-viewed.tsx
  source/helpers/get-items-between.test.ts
  source/helpers/get-items-between.ts
Labels: enhancement

#5603 Disable `wait-for-checks` when PR requires admin privileges
  source/features/wait-for-checks.tsx
Labels: bug

#5601 Keep linked comments visible in `conversation-activity-filter`
  source/features/conversation-activity-filter.tsx
Labels: enhancement

#5604 Meta: Use `registerHotkey` everywhere applicable
  source/features/conversation-activity-filter.tsx
  source/features/improve-shortcut-help.tsx
  source/features/keyboard-navigation.tsx
  source/features/selection-in-new-tab.tsx
Labels: meta

#5541 Restore padding broken by `scrollable-code-and-blockquote`
  source/features/scrollable-code-and-blockquote.css
Labels: bug

#5598 Fix branch dropdown position in `clean-conversation-headers`
  source/features/clean-conversation-headers.css
  source/features/clean-conversation-headers.tsx
Labels: bug

#5597 Restore `forked-to` feature and enable it for every user
  source/features/forked-to.tsx
Labels: bug, change request
