Repository refined-github/refined-github, pull requests merged in 2022-11, with the labels that each got.

#6103 Meta: Use new APIs in `update-pr-from-base-branch`
  source/features/restore-file.tsx
  source/features/update-pr-from-base-branch.tsx
  source/github-helpers/get-pr-info.ts
Labels: meta

#6122 `clear-pr-merge-commit-message` preserve closing issues on non-default branch
  source/features/clear-pr-merge-commit-message.tsx
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#6113 `preview-hidden-comments` even if reason is missing
  source/features/preview-hidden-comments.tsx
Labels: enhancement

#6131 Fix `releases-tab` count
  source/features/releases-tab.tsx
Labels: bug

#6081 Drop outdated references to PJAX
  source/feature-manager.tsx
  source/features/comments-time-machine-links.tsx
  source/features/default-branch-button.tsx
  source/features/dim-bots.tsx
  source/features/easier-pr-sha-copy.css
  source/features/global-conversation-list-filters.tsx
  source/features/global-search-filters.tsx
  source/features/latest-tag-button.tsx
  source/features/link-to-github-io.tsx
  source/features/linkify-branch-references.tsx
  source/features/linkify-symbolic-links.tsx
  source/features/list-prs-for-file.tsx
  source/features/more-file-links.tsx
  source/features/patch-diff-links.tsx
  source/features/quick-file-edit.tsx
  source/features/quick-review.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/repo-wide-file-finder.tsx
  source/features/rgh-feature-descriptions.tsx
  source/features/rgh-linkify-features.tsx
  source/features/same-branch-author-commits.tsx
  source/features/submission-via-ctrl-enter-everywhere.tsx
  source/features/swap-branches-on-compare.tsx
  source/features/useful-forks.tsx
  source/features/view-last-pr-deployment.tsx
  source/refined-github.ts
Labels: bug, meta

#6076 Meta: Safer text node targeting
  source/features/clean-conversation-sidebar.tsx
  source/features/clean-repo-filelist-actions.tsx
  source/features/clean-repo-sidebar.tsx
  source/features/conversation-links-on-repo-lists.tsx
  source/features/one-click-diff-options.tsx
  source/features/show-names.tsx
  source/features/useful-forks.tsx
  source/helpers/dom-utils.ts
Labels: meta

#6141 Restore `view-last-pr-deployment`
  source/features/view-last-pr-deployment.tsx
Labels: bug

#6140 Fix overflow caused by `patch-diff-links`
  source/features/patch-diff-links.tsx
Labels: bug

#6136 Fix `clean-dashboard` spacing of grouped items
  source/features/clean-dashboard.css
Labels: bug

#6133 Add `last-notification-page-button` feature
  readme.md
  source/features/last-notification-page-button.tsx
  source/refined-github.ts
Labels: enhancement

#6137 Restore `scheduled-and-manual-workflow-indicators`
  source/features/scheduled-and-manual-workflow-indicators.tsx
Labels: bug

#6138 Drop incorrect link added by `infinite-scroll`
  source/features/infinite-scroll.tsx
Labels: bug

#6114 Meta: Improve release workflow
  .github/workflows/release.yml
Labels: meta

#6148 Meta: Cleanup issue templates
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  .github/ISSUE_TEMPLATE/4_change_request.yml
Labels: meta

#6153 Cleanup and extend `pagination-hotkey`
  source/features/pagination-hotkey.tsx
  tsconfig.json
Labels: bug

#6160 Avoid duplicate `open-all-notifications` buttons
  source/features/open-all-notifications.tsx
Labels: bug

#6165 Fix `repo-avatars` rounding in orgs
  source/features/repo-avatars.tsx
Labels: bug

#6167 Fix: `profile-gists-link` appears in status selection on profile
  source/features/profile-gists-link.tsx
Labels: bug

#6168 Restore `scheduled-and-manual-workflow-indicators` again
  source/features/scheduled-and-manual-workflow-indicators.tsx
Labels: bug

#6166 Improve `select-notifications` style
  source/features/select-notifications.tsx
Labels: enhancement

#6169 Restore `quick-file-edit` on new directory views
  source/features/quick-file-edit.tsx
Labels: bug

#6178 Drop `split-issue-pr-search-results` feature
  readme.md
  source/features/split-issue-pr-search-results.css
  source/features/split-issue-pr-search-results.tsx
  source/refined-github.ts
Labels: implemented by github
