Repository refined-github/refined-github, pull requests merged in 2022-01, with the labels that each got.

#5259 Meta: Start tracking bundle sizes
  .github/workflows/test.yml
  .gitignore
  webpack.config.ts
Labels: meta

#5265 Meta: Update some dependencies
  package-lock.json
  package.json
Labels: meta

#5239 Meta: Refactor `SearchQuery`
  source/features/bugs-tab.tsx
  source/features/extend-conversation-status-filters.tsx
  source/features/global-conversation-list-filters.tsx
  source/features/global-search-filters.tsx
  source/features/more-conversation-filters.tsx
  source/features/sort-conversations-by-update-time.tsx
  source/features/split-issue-pr-search-results.tsx
  source/github-helpers/search-query.ts
  test/search-query.ts
Labels: meta

#5252 Fix: `profile-gists-link` is not responsive
  source/features/profile-gists-link.tsx
Labels: bug

#5243 Meta: Automatically generate release notes again /2
  .github/workflows/release.yml
Labels: meta

#5278 Change `hide-repo-badges` into a feature that can be disabled
  readme.md
  source/features/hide-repo-badges.css
  source/features/hide-repo-badges.tsx
  source/refined-github.css
  source/refined-github.ts
Labels: change request

#5279 Hide "New repository" button on organization dashboard
  source/refined-github.css
Labels: bug

#5271 Allow using videos as screenshots
  build/readme-parser.ts
  readme.md
  source/options.tsx
Labels: bug, enhancement, meta

#5281 Fix: `dim-bots` only works on the first page
  source/features/dim-bots.css
  source/features/dim-bots.tsx
Labels: bug

#5282 Meta: Run tests on Windows
  .github/workflows/test.yml
  package.json
  webpack.config.ts
Labels: meta

#5258 Mute visited conversation links on conversation lists
  source/refined-github.css
Labels: enhancement

#5285 `dim-bots` when not hovering
  source/features/dim-bots.css
Labels: change request

#5254 Meta: Toggle all screenshots in options page with Alt
  source/options.tsx
Labels: enhancement, meta

#5287 Fix `reactions-avatars` in reviews, releases and discussions
  source/features/github-bugs.css
  source/features/reactions-avatars.tsx
Labels: bug

#5289 Add `same-branch-author-commits` feature
  readme.md
  source/features/same-branch-author-commits.tsx
  source/refined-github.ts
Labels: enhancement

#5246 Fix branch handling on commit list without a branch
  source/features/comments-time-machine-links.tsx
  source/github-helpers/get-default-branch.ts
  source/github-helpers/index.ts
Labels: bug

#5297 Fix default branch getter
  source/github-helpers/get-default-branch.ts
Labels: bug

#5294 Don't hide custom enterprise footer in `clean-footer.css`
  source/features/clean-footer.css
Labels: bug, enhancement

#5295 Fix duplicated "Merged" filter in global conversation list
  source/features/extend-conversation-status-filters.tsx
Labels: bug

#5308 Fix some editor features on issue forms text fields
  source/features/collapsible-content-button.tsx
  source/features/table-input.tsx
Labels: bug

#5296 Add `prevent-pr-merge-panel-opening` feature
  readme.md
  source/features/prevent-pr-merge-panel-opening.tsx
  source/refined-github.ts
Labels: enhancement, github bug

#5310 Clear `forked-to` cache after `quick-repo-deletion`
  source/features/forked-to.tsx
  source/features/quick-repo-deletion.tsx
Labels: enhancement

#5298 Meta: require cleared cache and extension version in bug reports
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  readme.md
  source/features/index.tsx
Labels: meta

#5313 Deduplicate `same-branch-author-commits`
  readme.md
  source/features/same-branch-author-commits.tsx
Labels: bug

#5305 Make `dim-visited-conversations` a CSS feature
  readme.md
  source/features/dim-visited-conversations.css
  source/features/dim-visited-conversations.tsx
  source/refined-github.css
  source/refined-github.ts
Labels: enhancement

#5315 Extend `clean-conversations` to new comment forms
  source/features/clean-conversations.css
  source/refined-github.css
Labels: enhancement

#5323 Improve `clean-footer` support for custom Enterprise footers
  source/features/clean-footer.css
Labels: enhancement

#5324 Lint and extend `hide-tips.css`
  source/features/hide-tips.css
Labels: enhancement, meta

#5312 Refactor `list-prs-for-file`
  source/features/list-prs-for-file.tsx
Labels: bug, enhancement

#5320 Fix `comments-time-machine-links` loading
  source/features/comments-time-machine-links.tsx
Labels: bug

#5319 Clean up and stick sidebar footer in `infinite-scroll`
  source/features/infinite-scroll.css
  source/features/infinite-scroll.tsx
Labels: enhancement

#5238 Remove `quick-review` additional listener when navigating
  source/features/index.tsx
  source/features/quick-review.tsx
  source/helpers/on-element-removal.ts
  source/helpers/on-replaced-element.ts
Labels: bug

#5328 Fix page getting stuck when leaving PR conversation
  source/features/clean-conversation-sidebar.tsx
  source/features/index.tsx
  source/features/quick-review.tsx
  source/github-events/on-discussion-sidebar-update.ts
Labels: bug

#5329 Disable deduplication mechanism for all CSS features
  source/features/align-issue-labels.tsx
  source/features/clean-pinned-issues.tsx
  source/features/dim-visited-conversations.tsx
  source/features/hide-diff-signs.tsx
  source/features/hide-repo-badges.tsx
  source/features/index.tsx
  source/features/minimize-upload-bar.tsx
Labels: bug, meta

#5327 Improve `tags-on-commits-list` and `first-published-tag-for-merged-pr` style
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/tags-on-commits-list.tsx
Labels: enhancement

#5284 Fix `ci-link` on Discussions and get from page if present
  source/features/ci-link.css
  source/features/ci-link.tsx
Labels: bug, enhancement

#5337 Extend `hide-low-quality-comments` with more keywords
  source/helpers/is-low-quality-comment.ts
  test/is-low-quality-comment.ts
Labels: enhancement

#5349 Fix `clean-conversation-sidebar` leaking style
  source/features/clean-conversation-sidebar.css
Labels: bug
