Repository refined-github/refined-github, pull requests merged in 2022-09, with the labels that each got.

#5949 Fix `set-default-repositories-type-to-sources` on project views
  source/features/set-default-repositories-type-to-sources.tsx
  source/github-events/on-profile-dropdown-load.ts
Labels: bug

#5946 Restore support for unmarked bots in `dim-bots`
  source/features/dim-bots.tsx
Labels: bug

#5955 Update dependencies
  build/verify-features.ts
  package-lock.json
  package.json
  source/features/bypass-checks.tsx
  source/features/select-notifications.tsx
  source/features/toggle-files-button.tsx
  source/helpers/dom-utils.ts
Labels: meta

#5956 Meta: Cleanup DOM tests
  .xo-config.json
  package-lock.json
  package.json
  source/helpers/select-has.test.ts
  test/fixtures/globals.js
  test/fixtures/globals.ts
  vite.config.ts
Labels: meta

#5950 Restore `hidden-review-comments-indicator`
  source/features/hidden-review-comments-indicator.css
  source/features/hidden-review-comments-indicator.tsx
Labels: bug

#5954 Lint
  .xo-config.json
  build/readme.loader.cts
  package-lock.json
  package.json
  source/features/conflict-marker.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/index.tsx
  source/features/latest-tag-button.tsx
  source/features/link-to-changelog-file.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/reactions-avatars.tsx
  source/features/release-download-count.tsx
  source/features/repo-age.tsx
  source/features/scheduled-and-manual-workflow-indicators.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/tag-changes-link.tsx
  source/features/tags-on-commits-list.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-local-time.tsx
  source/github-helpers/api.ts
  source/github-helpers/banner.tsx
  source/github-helpers/get-pr-info.ts
  source/github-widgets/notice-bar.tsx
  source/globals.d.ts
  source/helpers/types.d.ts
  source/options.tsx
  source/resolve-conflicts.ts
  tsconfig.json
Labels: meta

#5966 Meta: Drop code specific to "Releases UI refresh"
  source/features/link-to-changelog-file.tsx
  source/features/tag-changes-link.tsx
Labels: meta

#5965 Meta: Drop deprecated color classes
  source/features/action-used-by-link.tsx
  source/features/align-issue-labels.css
  source/features/clean-dashboard.css
  source/features/clean-mergeability-box.css
  source/features/clean-repo-sidebar.tsx
  source/features/conflict-marker.tsx
  source/features/conversation-activity-filter.tsx
  source/features/dim-bots.css
  source/features/emphasize-draft-pr-label.css
  source/features/file-finder-buffer.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/git-checkout-pr.tsx
  source/features/hide-low-quality-comments.css
  source/features/highest-rated-comment.tsx
  source/features/highlight-collaborators-and-own-conversations.css
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/link-to-changelog-file.tsx
  source/features/linkify-notification-repository-header.tsx
  source/features/list-prs-for-branch.tsx
  source/features/one-click-diff-options.tsx
  source/features/parse-backticks.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-approvals-count.css
  source/features/pr-commit-lines-changed.tsx
  source/features/quick-comment-hiding.tsx
  source/features/select-notifications.tsx
  source/features/show-names.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-local-time.tsx
  source/features/user-profile-follower-badge.tsx
  source/refined-github.css
Labels: meta

#5964 Allow replacing quotes in `one-key-formatting`
  source/features/one-key-formatting.tsx
Labels: change request

#5962 Limit `shorten-links` to only Markdown links
  source/features/shorten-links.tsx
Labels: bug

#5961 Don't change `sticky-sidebar` state while interacting with it
  source/features/sticky-sidebar.css
  source/features/sticky-sidebar.tsx
  source/helpers/calculate-css-calc-string.test.ts
  source/helpers/calculate-css-calc-string.ts
Labels: bug

#5958 Avoid duplicate `on-click-diff-options`
  package.json
  source/features/one-click-diff-options.tsx
Labels: bug

#5959 Fix reaction popup at bottom of comments
  source/features/center-reactions-popup.css
Labels: bug

#5973 Meta: Disable sourcemaps
  safari/Refined GitHub.xcodeproj/project.pbxproj
  webpack.config.ts
Labels: meta

#5976 Fix: `select-notifications` causes button overlap on mobile
  source/features/select-notifications.css
Labels: bug

#5968 Consistently `shorten-links` even if other features altered them
  package-lock.json
  package.json
  source/features/comments-time-machine-links.tsx
  source/features/sort-conversations-by-update-time.tsx
Labels: bug

#5974 Fix `open-all-notifications` on back button
  package.json
  source/features/open-all-notifications.tsx
  source/helpers/attach-element.ts
Labels: bug

#5977 Persist `one-click-diff-options` like the native buttons
  source/features/one-click-diff-options.tsx
Labels: bug

#5975 Notify users of errors in `open-all-notifications`
  source/features/open-all-conversations.tsx
  source/features/open-all-notifications.tsx
  source/github-helpers/toast.tsx
  source/helpers/open-tabs.ts
Labels: bug, safari

#5980 Make `toggle-files-button` act faster and more reliably
  source/features/toggle-files-button.css
  source/features/toggle-files-button.tsx
Labels: bug

#5970 Fix `quick-review-comment-deletion`
  source/features/quick-review-comment-deletion.tsx
Labels: bug

#5986 Avoid triggering `pr-branch-auto-delete` when simply watching a PR
  source/github-events/on-pr-merge.ts
Labels: bug

#5985 Disable `sticky-sidebar` on small viewports
  source/features/sticky-sidebar.css
  source/features/sticky-sidebar.tsx
Labels: bug

#5983 Rename `first-published-tag-for-merged-pr` to `closing-remarks`
  readme.md
  source/features/closing-remarks.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: change request

#5994 Make `show-whitespace` more reliable
  source/features/select-notifications.css
  source/features/show-whitespace.tsx
  source/globals.d.ts
Labels: enhancement

#5991 Meta: Drop some custom listeners
  source/features/quick-file-edit.tsx
  source/features/show-names.tsx
  source/github-events/on-file-list-update.ts
  source/github-events/on-fragment-load.ts
  source/github-events/on-newsfeed-load.ts
  source/github-helpers/index.ts
  source/helpers/batched-function.ts
Labels: meta

#5990 Fix `quick-review` and `comment-on-draft-pr-indicator`
  source/features/comment-on-draft-pr-indicator.tsx
  source/features/quick-review.tsx
Labels: bug

#5998 Restore ability to open selected issues in `open-all-conversations`
  source/features/open-all-conversations.tsx
  source/helpers/attach-element.ts
Labels: bug, enhancement

#5997 Restore `clean-conversation-sidebar`
  source/features/clean-conversation-sidebar.tsx
Labels: bug

#6002 Avoid duplicate indentation in `tab-to-indent`
  package-lock.json
  package.json
Labels: bug

#6018 Restore `quick-review-comment-deletion`
  source/features/quick-review-comment-deletion.tsx
  source/github-helpers/load-details-menu.ts
Labels: bug

#6016 Drop `linkify-labels-on-dashboard` feature
  readme.md
  source/features/linkify-labels-on-dashboard.tsx
  source/refined-github.ts
Labels: under discussion, change request

#6007 Avoid duplication of `useful-not-found-page` on back button
  source/features/useful-not-found-page.tsx
Labels: bug

#6006 Warp speed 🚀
  package-lock.json
  package.json
  source/feature-manager.tsx
  source/features/bypass-checks.tsx
  source/features/ci-link.tsx
  source/features/clean-header-search-field.tsx
  source/features/clean-repo-filelist-actions.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conversation-activity-filter.tsx
  source/features/conversation-links-on-repo-lists.tsx
  source/features/convert-pr-to-draft-improvements.tsx
  source/features/edit-readme.tsx
  source/features/embed-gist-inline.tsx
  source/features/hide-disabled-milestone-sorter.tsx
  source/features/hide-inactive-deployments.tsx
  source/features/hide-own-stars.tsx
  source/features/jump-to-change-requested-comment.tsx
  source/features/jump-to-conversation-close-event.tsx
  source/features/keyboard-navigation.tsx
  source/features/link-to-github-io.tsx
  source/features/linkify-code.tsx
  source/features/linkify-user-edit-history-popup.tsx
  source/features/linkify-user-labels.tsx
  source/features/linkify-user-location.tsx
  source/features/new-repo-disable-projects-and-wikis.tsx
  source/features/one-click-diff-options.tsx
  source/features/parse-backticks.tsx
  source/features/preview-hidden-comments.tsx
  source/features/quick-comment-edit.tsx
  source/features/quick-file-edit.tsx
  source/features/quick-label-removal.tsx
  source/features/quick-mention.css
  source/features/quick-mention.tsx
  source/features/quick-repo-deletion.tsx
  source/features/reactions-avatars.tsx
  source/features/releases-tab.tsx
  source/features/rgh-linkify-features.tsx
  source/features/set-default-repositories-type-to-sources.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-names.tsx
  source/features/sticky-sidebar.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/useful-forks.tsx
  source/features/user-local-time.tsx
  source/github-events/on-new-comments.ts
  source/github-helpers/dom-formatters.ts
  source/github-widgets/notice-bar.tsx
  source/helpers/attach-element.ts
  source/helpers/batched-function.ts
  source/helpers/selector-observer.tsx
Labels: :rocket:

#6019 Add notice to `clear-pr-merge-commit-message`
  source/features/clear-pr-merge-commit-message.tsx
Labels: change request
