Repository refined-github/refined-github, pull requests merged in 2022-12, with the labels that each got.

#6177 Replace `commenter:` filters with `involves:`
  readme.md
  source/features/global-conversation-list-filters.tsx
  source/features/more-conversation-filters.tsx
Labels: change request

#6182 Add `unhide-reactions-on-mobile` feature
  readme.md
  source/features/unhide-reactions-on-mobile.css
  source/refined-github.ts
Labels: enhancement

#6199 Update and fix `highest-rated-comment`
  source/features/highest-rated-comment.css
  source/features/highest-rated-comment.tsx
Labels: bug

#6171 Restore `restore-file` feature
  source/features/restore-file.tsx
  source/github-helpers/api.ts
Labels: bug

#6193 Fix `hide-own-stars`
  source/features/hide-own-stars.tsx
Labels: bug

#6205 Update CSS color names
  source/refined-github.css
Labels: bug
