Repository refined-github/refined-github, pull requests merged in 2022-08, with the labels that each got.

#5827 Meta: Move content to wiki
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  source/features/new-repo-disable-projects-and-wikis.tsx
  source/features/prevent-link-loss.tsx
  source/features/rgh-welcome-issue.tsx
Labels: help wanted, meta

#5873 Don't deduplicate event-only features
  source/features/avoid-accidental-submissions.tsx
  source/features/batch-mark-files-as-viewed.tsx
  source/features/clear-pr-merge-commit-message.tsx
  source/features/convert-pr-to-draft-improvements.tsx
  source/features/easy-toggle-commit-messages.tsx
  source/features/easy-toggle-files.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/expand-all-hidden-comments.tsx
  source/features/extend-diff-expander.tsx
  source/features/first-published-tag-for-merged-pr.tsx
  source/features/fit-textareas.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/more-file-links.tsx
  source/features/one-click-diff-options.tsx
  source/features/one-click-review-submission.tsx
  source/features/one-key-formatting.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/pr-jump-to-first-non-viewed-file.tsx
  source/features/prevent-duplicate-pr-submission.tsx
  source/features/prevent-link-loss.tsx
  source/features/quick-comment-hiding.tsx
  source/features/quick-label-removal.tsx
  source/features/quick-review-comment-deletion.tsx
  source/features/restore-file.tsx
  source/features/rgh-sponsor-button.tsx
  source/features/same-page-definition-jump.tsx
  source/features/show-names.tsx
  source/features/show-whitespace.tsx
  source/features/stop-redirecting-in-notification-bar.tsx
  source/features/suggest-commit-title-limit.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/toggle-everything-with-alt.tsx
  source/features/unfinished-comments.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/wait-for-checks.tsx
Labels: bug, ajax

#5845 Lint
  package-lock.json
  package.json
  source/features/ci-link.tsx
  source/features/clean-conversation-headers.tsx
  source/features/conversation-activity-filter.tsx
  source/features/create-release-shortcut.tsx
  source/features/pagination-hotkey.tsx
  source/features/parse-backticks.tsx
  source/features/pull-request-hotkeys.tsx
  source/features/restore-file.tsx
  source/features/select-all-notifications-shortcut.tsx
  source/features/selection-in-new-tab.tsx
  source/github-helpers/hotkey.tsx
  source/github-helpers/hotkeys.test.ts
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
  source/github-helpers/register-hotkey.tsx
  source/helpers/abort-controller.ts
  source/helpers/hotfix.tsx
  source/helpers/template-literal.ts
Labels: meta

#5885 Link `repo-avatars` to repository author
  source/features/repo-avatars.tsx
Labels: enhancement

#5891 Hide label on Milestones link if there are zero milestones
  source/refined-github.css
Labels: enhancement

#5896 Disable `clean-rich-text-editor` on mobile
  source/features/clean-rich-text-editor.css
Labels: bug

#5898 Fix `show-whitespace` peekaboo bugfix bug
  source/features/show-whitespace.css
Labels: bug

#5904 Drop some fixes for GitHub bugs
  source/features/github-bugs.css
Labels: github bug

#5906 Fix: User style lost after navigation
  source/features/index.tsx
Labels: bug, ajax

#5905 Fix `fork-source-link-same-view` on tags/releases
  source/features/fork-source-link-same-view.tsx
Labels: bug

#5899 Always show `first-published-tag-for-merged-pr`
  source/features/first-published-tag-for-merged-pr.tsx
  source/github-helpers/banner.tsx
Labels: bug, enhancement

#5912 Fix `repo-avatars` alignment
  source/features/repo-avatars.tsx
Labels: bug

#5853 Only run `useful-forks` on public repositories
  source/features/useful-forks.tsx
Labels: enhancement

#5918 Enable `linkify-code` on discussions
  source/features/linkify-code.tsx
Labels: enhancement

#5925 Restore `convert-release-to-draft` feature
  source/features/convert-release-to-draft.tsx
Labels: bug

#5919 Support "For you" feed in `infinite-scroll`
  source/features/infinite-scroll.tsx
Labels: enhancement

#5923 Fix: Repo tabs are hidden in Actions on Firefox
  source/features/more-dropdown-links.css
Labels: bug

#5930 Fix position of sticky file headers after opening notification
  source/features/sticky-file-header.css
Labels: bug

#5931 Restore `show-names` feature
  source/features/show-names.tsx
  source/github-events/on-fragment-load.ts
  source/github-events/on-newsfeed-load.ts
Labels: bug, meta

#5933 Restore `center-reactions-popup` feature
  source/features/center-reactions-popup.css
Labels: bug
