Repository refined-github/refined-github, pull requests merged in 2022-05, with the labels that each got.

#5616 Meta: Change `tag-changes-link`’ label to "Commits"
  source/features/tag-changes-link.tsx
Labels: meta

#5620 Fix spacing of icons in repo header buttons
  package.json
  source/features/github-bugs.css
Labels: enhancement

#5623 Fix GitHub bug: Avoid excessive repo title wrap
  source/features/github-bugs.css
Labels: enhancement, github bug

#5612 Hide text of "Edit Pins" dropdown button in organization repos
  source/refined-github.css
Labels: enhancement

#5626 Add `type/bug` and `kind/bug` to list of supported labels in `bugs-tab`
  source/features/bugs-tab.tsx
Labels: enhancement

#5625 Restore `expand-all-hidden-comments` feature
  source/features/expand-all-hidden-comments.tsx
Labels: bug

#5633 Fix `suggest-commit-title-limit` 1-character-short width
  source/features/suggest-commit-title-limit.css
  source/features/suggest-commit-title-limit.tsx
  source/refined-github.css
Labels: bug

#5632 Avoid some console errors when attempting to edit files on non-own repos
  source/features/avoid-accidental-submissions.tsx
  source/features/list-prs-for-file.tsx
  source/features/submission-via-ctrl-enter-everywhere.tsx
Labels: bug

#5642 Don't link to first comment in `highest-rated-comment`
  source/features/highest-rated-comment.tsx
Labels: bug

#5636 Restore broken `release-download-count`
  source/features/release-download-count.tsx
Labels: bug

#5638 Don't `shorten-links` in code blocks in tables in comments
  source/features/shorten-links.tsx
  source/github-helpers/dom-formatters.ts
Labels: bug

#5639 Apply `rgh-linkify-features` to all RGH repos
  source/features/rgh-linkify-features.tsx
  source/github-helpers/index.ts
Labels: meta

#5631 Drop `hide-tips` feature
  source/features/hide-tips.css
  source/refined-github.ts
Labels: change request

#5643 Add large `first-published-tag-for-merged-pr` banner
  readme.md
  source/features/first-published-tag-for-merged-pr.tsx
Labels: enhancement

#5645 Silence `clean-conversation-filters` errors on orgs without projects
  source/features/clean-conversation-filters.tsx
Labels: bug

#5644 Ensure that Refined GitHub preserves existing shortcuts
  source/features/create-release-shortcut.tsx
  source/features/pagination-hotkey.tsx
  source/features/pull-request-hotkeys.tsx
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
Labels: bug

#5646 Avoid clipping `conversation-activity-filter`
  source/features/conversation-activity-filter.tsx
Labels: bug

#5640 Restore broken `forked-to`
  source/features/forked-to.tsx
  source/features/sort-conversations-by-update-time.tsx
Labels: bug

#5641 Ensure `restore-file` appears after navigating to the Files tab
  source/features/restore-file.tsx
Labels: bug

#5647 Lint
  .xo-config.json
  build/readme-parser.ts
  package-lock.json
  package.json
  source/features/ci-link.tsx
  source/features/easy-toggle-files.tsx
  source/features/one-click-diff-options.tsx
  source/features/scheduled-and-manual-workflow-indicators.tsx
  source/features/use-first-commit-message-for-new-prs.tsx
  source/github-helpers/pr-ci-status.ts
  source/globals.d.ts
Labels: meta

#5651 Add link to the upstream repo after `quick-repo-deletion`
  source/features/quick-repo-deletion.tsx
Labels: enhancement

#5652 Meta: Add link to TSX file when looking at CSS feature
  source/features/rgh-feature-descriptions.tsx
Labels: meta

#5649 Fix `highlight-deleted-and-added-files-in-diffs` with CODEOWNERS
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
Labels: bug

#5655 Alt-click on `open-all-notifications` to also mark them as done
  source/features/open-all-notifications.tsx
Labels: enhancement

#5653 Make `toggle-files-button` unforgettable
  source/features/toggle-files-button.tsx
Labels: enhancement

#5650 `prevent-link-loss` for more discussion URLs
  source/features/prevent-link-loss.tsx
  source/github-helpers/prevent-link-loss.test.ts
  source/github-helpers/prevent-link-loss.ts
Labels: bug

#5648 Don't run Refined GitHub on login pages
  source/features/dim-bots.tsx
  source/manifest.json
Labels: bug

#5662 Ensure all features appears after navigating to the "Files" tab
  source/features/enable-file-links-in-compare-view.tsx
  source/features/linkify-code.tsx
Labels: bug
