Repository refined-github/refined-github, pull requests merged in 2023-04, with the labels that each got.

#6462 Update CSS comment
  source/features/clean-footer.css
Labels: meta

#6447 Allow color customization via CSS in `file-age-color` and `release-download-count`
  source/github-helpers/heat-map.css
Labels: enhancement

#6475 Fix merge button corners in Firefox
  source/refined-github.css
Labels: bug

#6472 Drop `clean-mergeability-box` feature
  readme.md
  source/features/clean-mergeability-box.css
  source/features/clean-mergeability-box.tsx
  source/refined-github.ts
Labels: change request

#6479 Drop `clean-commit-form`
  source/features/clean-commit-form.css
  source/refined-github.ts
Labels: change request

#6468 Fix pull request review list style
  source/features/clean-checks-list.css
Labels: bug

#6457 Restore `swap-branches-on-compare`
  readme.md
  source/features/swap-branches-on-compare.tsx
Labels: bug

#6458 Drop `useful-forks` feature
  readme.md
  source/features/useful-forks.tsx
  source/refined-github.ts
Labels: change request

#6481 Add `archive-forks-link` feature
  readme.md
  source/features/archive-forks-link.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: enhancement

#6448 Add options export/import
  .github/release.yml
  package-lock.json
  package.json
  source/options.html
Labels: enhancement

#6480 Refactor `tab-size` to reduce conflicts
  source/features/show-whitespace.css
  source/features/tab-size.css
Labels: bug

#6483 Refactor `tab-size` /2
  source/features/tab-size.css
Labels: bug

#6486 Restore `quick-new-issue` on Global navigation update
  package-lock.json
  package.json
  source/features/quick-new-issue.tsx
  source/github-helpers/index.ts
Labels: bug

#6487 Less eye-catching `rgh-netiquette`
  source/features/rgh-netiquette.tsx
  source/refined-github.css
Labels: meta

#6492 Add `small-user-avatars` feature
  readme.md
  source/features/small-user-avatars.css
  source/features/small-user-avatars.tsx
  source/refined-github.ts
Labels: enhancement

#6490 Hide avatar entirely from comment form
  source/features/clean-conversations.css
Labels: bug

#6503 Fix `html-preview-link` in new file UI
  source/features/html-preview-link.tsx
Labels: bug

#6497 Less flashy `closing-remarks`
  source/features/closing-remarks.tsx
  source/features/rgh-netiquette.tsx
  source/refined-github.css
Labels: change request

#6518 Add support for Firefox and Safari in options import/export
  package-lock.json
  package.json
Labels: enhancement

#6519 Fix `table-input` position
  source/features/table-input.tsx
Labels: bug

#6510 Fix `release-download-count` spacing
  source/features/github-bugs.css
  source/features/release-download-count.css
  source/features/release-download-count.tsx
Labels: bug

#6505 Exclude mannequins from `show-names`
  source/features/linkify-user-labels.tsx
  source/features/show-names.tsx
Labels: bug

#6506 Add `releases-dropdown` feature
  readme.md
  source/features/github-bugs.css
  source/features/highlight-non-default-base-branch.tsx
  source/features/latest-tag-button.tsx
  source/features/releases-dropdown.tsx
  source/globals.d.ts
  source/refined-github.ts
Labels: enhancement

#6522 Disable `swap-branches-on-compare` on blank page
  package-lock.json
  package.json
  source/features/swap-branches-on-compare.tsx
Labels: bug

#6516 More ergonomic `table-input` HTML
  source/features/table-input.tsx
Labels: enhancement

#6532 Use correct `view-last-pr-deployment` icon
  readme.md
  source/features/view-last-pr-deployment.tsx
Labels: change request

#6531 Ensure `hide-user-forks` works coming from anywhere
  package-lock.json
  package.json
  source/features/hide-user-forks.tsx
Labels: bug

#6536 Better search link in console issue reporter
  source/feature-manager.tsx
Labels: meta

#6534 Reduce `has` selector console noise in Firefox
  source/features/clean-conversation-sidebar.tsx
  source/features/hide-own-stars.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/quick-new-issue.tsx
  source/features/rgh-netiquette.tsx
  source/features/table-input.tsx
  source/helpers/select-has.ts
Labels: bug, firefox

#6543 Show "Disabled" state in `github-actions-indicators`
  source/features/github-actions-indicators.tsx
Labels: enhancement

#6563 Update `delegate-it`
  contributing.md
  package-lock.json
  package.json
  source/features/avoid-accidental-submissions.tsx
  source/features/batch-mark-files-as-viewed.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/collapsible-content-button.tsx
  source/features/command-palette-navigation-shortcuts.tsx
  source/features/convert-pr-to-draft-improvements.tsx
  source/features/convert-release-to-draft.tsx
  source/features/deep-reblame.tsx
  source/features/dim-bots.tsx
  source/features/easy-toggle-commit-messages.tsx
  source/features/easy-toggle-files.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/expand-all-hidden-comments.tsx
  source/features/extend-diff-expander.tsx
  source/features/fit-textareas.tsx
  source/features/git-checkout-pr.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/hide-low-quality-comments.tsx
  source/features/more-file-links.tsx
  source/features/new-repo-disable-projects-and-wikis.tsx
  source/features/one-click-review-submission.tsx
  source/features/one-key-formatting.tsx
  source/features/open-all-conversations.tsx
  source/features/open-all-notifications.tsx
  source/features/pr-jump-to-first-non-viewed-file.tsx
  source/features/prevent-duplicate-pr-submission.tsx
  source/features/prevent-link-loss.tsx
  source/features/quick-comment-hiding.tsx
  source/features/quick-label-removal.tsx
  source/features/quick-mention.tsx
  source/features/quick-repo-deletion.tsx
  source/features/quick-review-comment-deletion.tsx
  source/features/quick-review.tsx
  source/features/releases-dropdown.tsx
  source/features/reload-failed-proxied-images.tsx
  source/features/restore-file.tsx
  source/features/rgh-sponsor-button.tsx
  source/features/rgh-welcome-issue.tsx
  source/features/select-notifications.tsx
  source/features/stop-redirecting-in-notification-bar.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/table-input.tsx
  source/features/toggle-everything-with-alt.tsx
  source/features/toggle-files-button.tsx
  source/features/unfinished-comments.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/wait-for-checks.tsx
  source/features/warning-for-disallow-edits.tsx
  source/github-events/on-commit-title-update.ts
  source/github-events/on-field-keydown.tsx
  source/github-events/on-fragment-load.ts
  source/github-events/on-pr-merge-panel-open.ts
  source/github-events/on-pr-merge.ts
  source/options.tsx
Labels: meta

#6555 Lint
  source/feature-manager.tsx
  source/features/bypass-checks.tsx
  source/features/clear-pr-merge-commit-message.tsx
  source/features/conversation-activity-filter.tsx
  source/features/enable-file-links-in-compare-view.tsx
  source/features/link-to-github-io.tsx
  source/features/linkify-user-labels.tsx
  source/features/sync-pr-commit-title.tsx
  source/github-helpers/turbo-events-polyfill.ts
  source/globals.d.ts
  source/helpers/selector-observer.tsx
Labels: meta

#6565 Enable `fit-textareas` sooner, don't wait for focus
  source/features/fit-textareas.tsx
Labels: enhancement

#6564 Improve `sync-pr-commit-title` reliability
  source/features/sync-pr-commit-title.tsx
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
  source/helpers/pr-commit-cleaner.test.ts
  source/helpers/pr-commit-cleaner.ts
Labels: bug

#6561 Drop `git-checkout-pr` feature
  readme.md
  source/features/git-checkout-pr.tsx
  source/refined-github.ts
Labels: change request

#6567 Drop `onConversationHeaderUpdate` listener
  source/features/clean-conversation-headers.tsx
  source/features/clear-pr-merge-commit-message.tsx
  source/features/closing-remarks.tsx
  source/features/conversation-activity-filter.tsx
  source/features/dim-bots.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/github-events/on-conversation-header-update.ts
  source/github-events/on-fragment-load.ts
  source/github-events/on-pr-merge-panel-open.ts
  source/helpers/simplified-element-observer.ts
Labels: meta

#6537 Use native style in `update-pr-from-base-branch`
  readme.md
  source/features/update-pr-from-base-branch.tsx
  source/github-widgets/mergeability-row.tsx
Labels: enhancement

#6301 Add automated selector testing
  source/features/releases-tab.tsx
  source/github-helpers/selectors.test.ts
  source/github-helpers/selectors.ts
Labels: meta, under discussion

#6578 Restore `list-prs-for-file`
  readme.md
  source/features/list-prs-for-file.tsx
Labels: bug

#6580 Adjust `table-input` size on mobile
  source/features/table-input.css
Labels: bug

#6581 Silence `ci-link` error
  source/features/ci-link.tsx
Labels: bug

#6575 Drop `latest-tag-button` feature
  readme.md
  source/features/latest-tag-button.css
  source/features/latest-tag-button.tsx
  source/refined-github.ts
Labels: change request

#6584 Avoid race conditions in PR merge commit fields
  source/features/clear-pr-merge-commit-message.tsx
  source/features/sync-pr-commit-title.tsx
Labels: bug

#6582 Avoid `show-names` on the wrong links in the For You dashboard
  source/features/show-names.tsx
Labels: bug

#6586 Safari: Restore migrations and the actions button
  package-lock.json
Labels: bug, safari
