Repository refined-github/refined-github, pull requests merged in 2023-08, with the labels that each got.

#6794 Restore `show-names`
  source/features/show-names.tsx
Labels: bug

#6795 Dim unclickable reaction buttons
  source/features/github-bugs.css
Labels: enhancement, github bug

#6803 Select closed rejected issues in `select-notifications`
  source/features/select-notifications.tsx
Labels: bug

#6805 Improve page detection
  package-lock.json
  package.json
  source/features/actionable-pr-view-file.tsx
  source/features/conversation-links-on-repo-lists.tsx
  source/features/convert-release-to-draft.tsx
  source/features/download-folder-button.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/link-to-changelog-file.tsx
  source/features/link-to-github-io.tsx
  source/features/one-click-diff-options.tsx
  source/features/one-click-review-submission.tsx
  source/features/pagination-hotkey.tsx
  source/features/parse-backticks.tsx
  source/features/previous-next-commit-buttons.tsx
  source/features/restore-file.tsx
  source/features/tag-changes-link.tsx
Labels: bug

#6797 Extend `action-pr-link` to links in PRs
  source/features/action-pr-link.tsx
Labels: enhancement

#6808 Fix options overscroll on load
  package.json
  source/options.tsx
Labels: bug

#6816 Meta: Build on Node 20
  .nvmrc
  package-lock.json
  package.json
Labels: meta

#6817 Fix VIP label check for low quality comments
  source/features/hide-low-quality-comments.tsx
Labels: bug

#6813 Extend `rgh-netiquette`
  source/features/rgh-netiquette.tsx
Labels: meta

#6815 Update actions/upload-artifact action to v3
  .github/workflows/test.yml
Labels: meta

#6825 Restore `quick-comment-hiding`
  source/features/quick-comment-hiding.tsx
Labels: bug

#6835 Add missing `isSingleReleaseOrTag` when `isReleasesOrTags` usage
  source/features/reactions-avatars.tsx
  source/features/release-download-count.tsx
  source/features/rgh-linkify-features.tsx
  source/features/tag-changes-link.tsx
Labels: bug

#6837 Improve support of New Repository Overview
  source/github-helpers/get-default-branch.ts
Labels: bug

#6839 Fix `conflict-marker` duplicated
  source/features/conflict-marker.tsx
Labels: bug

#6847 Restore `linkify-user-location` in hover cards
  source/features/linkify-user-location.tsx
Labels: bug

#6842 Enable `parse-backticks` on search and subscription pages
  source/features/parse-backticks.tsx
Labels: enhancement

#6855 Disable broken `sticky-sidebar` in Firefox
  source/features/sticky-sidebar.tsx
Labels: bug, firefox

#6830 Meta: Update old screenshots
  readme.md
Labels: meta

#6858 Update dependencies
  package-lock.json
  package.json
  source/github-helpers/banner.tsx
  test/__snapshots__/shorten-link.test.ts.snap
  tsconfig.json
Labels: meta

#6857 Avoid false positives in `dim-bots`
  source/features/dim-bots.tsx
Labels: bug
