Repository refined-github/refined-github, pull requests merged in 2023-09, with the labels that each got.

#6869 Meta: Validate `addCssFeature` usage
  build/verify-features.ts
Labels: meta

#6868 Meta: Drop `deinit` functions
  source/feature-manager.tsx
  source/features/conversation-activity-filter.tsx
  source/features/create-release-shortcut.tsx
  source/features/linkify-branch-references.tsx
  source/features/profile-hotkey.tsx
  source/features/repo-wide-file-finder.tsx
  source/features/select-all-notifications-shortcut.tsx
  source/features/selection-in-new-tab.tsx
  source/github-helpers/hotkey.tsx
  source/globals.d.ts
  source/helpers/abort-controller.ts
Labels: meta

#6871 Drop `hide-disabled-milestone-sorter` feature
  readme.md
  source/features/hide-disabled-milestone-sorter.tsx
  source/refined-github.ts
Labels: change request

#6875 Drop `edit-readme` feature
  readme.md
  source/features/edit-readme.tsx
  source/refined-github.ts
Labels: change request

#6867 Meta: Accept `init` array
  source/feature-manager.tsx
  source/features/clean-repo-sidebar.tsx
  source/features/clean-repo-tabs.tsx
  source/features/rgh-improve-new-issue-form.tsx
  source/globals.d.ts
  source/helpers/async-for-each.ts
Labels: meta

#6872 Meta: Fix some TODOs
  source/features/clean-conversation-sidebar.tsx
  source/features/embed-gist-via-iframe.tsx
  source/features/file-age-color.tsx
  source/features/hide-newsfeed-noise.css
  source/features/linkify-code.tsx
  source/features/parse-backticks.tsx
  source/options.tsx
Labels: meta

#6876 Meta: Improve bisect message
  source/helpers/bisect.tsx
Labels: meta

#6881 Meta: Enable prettier on CSS and GQL
  .npmrc
  .prettierignore
  package-lock.json
  package.json
  source/features/align-issue-labels.css
  source/features/always-show-branch-delete-buttons.css
  source/features/clean-conversation-headers.css
  source/features/clean-conversation-sidebar.css
  source/features/clean-repo-sidebar.css
  source/features/clean-rich-text-editor.css
  source/features/dim-bots.css
  source/features/extend-diff-expander.css
  source/features/github-bugs.css
  source/features/hide-diff-signs.css
  source/features/hide-navigation-hover-highlight.css
  source/features/hide-newsfeed-noise.css
  source/features/link-to-compare-diff.css
  source/features/list-prs-for-file.gql
  source/features/minimize-upload-bar.css
  source/features/mobile-tabs.css
  source/features/night-not-found.css
  source/features/no-unnecessary-split-diff-view.css
  source/features/open-all-notifications.css
  source/features/pr-approvals-count.css
  source/features/quick-comment-edit.css
  source/features/quick-label-removal.css
  source/features/rgh-welcome-issue.css
  source/features/safer-destructive-actions.css
  source/features/scrollable-areas.css
  source/features/sticky-conversation-list-toolbar.css
  source/features/sticky-sidebar.css
  source/features/suggest-commit-title-limit.css
  source/features/table-input.css
  source/features/tag-changes-link.css
  source/features/user-local-time.css
  source/features/warning-for-disallow-edits.css
  source/github-helpers/heat-map.css
  source/options.css
  source/refined-github.css
  test/__snapshots__/shorten-link.test.ts.snap
  test/shorten-link.test.ts
Labels: meta

#6879 Meta: Extract GQL queries
  .git-blame-ignore-revs
  source/features/bugs-tab.gql
  source/features/bugs-tab.tsx
  source/features/clean-conversation-filters.gql
  source/features/clean-conversation-filters.tsx
  source/features/clean-repo-tabs.gql
  source/features/clean-repo-tabs.tsx
  source/features/comments-time-machine-links.gql
  source/features/comments-time-machine-links.tsx
  source/features/deep-reblame.gql
  source/features/deep-reblame.tsx
  source/features/github-actions-indicators.gql
  source/features/github-actions-indicators.tsx
  source/features/link-to-changelog-file.gql
  source/features/link-to-changelog-file.tsx
  source/features/pr-commit-lines-changed.gql
  source/features/pr-commit-lines-changed.tsx
  source/features/pr-filters.gql
  source/features/pr-filters.tsx
  source/features/profile-gists-link.gql
  source/features/profile-gists-link.tsx
  source/features/releases-dropdown.gql
  source/features/releases-dropdown.tsx
  source/features/releases-tab.gql
  source/features/releases-tab.tsx
  source/features/repo-age-first-commit.gql
  source/features/repo-age.gql
  source/features/repo-age.tsx
  source/features/restore-file.gql
  source/features/restore-file.tsx
  source/features/show-associated-branch-prs-on-fork.gql
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-open-prs-of-forks.gql
  source/features/show-open-prs-of-forks.tsx
  source/features/tags-on-commits-list.gql
  source/features/tags-on-commits-list.tsx
  source/features/unreleased-commits.gql
  source/features/unreleased-commits.tsx
  source/features/useful-not-found-page.gql
  source/features/useful-not-found-page.tsx
  source/github-helpers/does-file-exist.gql
  source/github-helpers/does-file-exist.tsx
  source/github-helpers/get-default-branch.gql
  source/github-helpers/get-default-branch.ts
Labels: meta

#6886 Drop ability to `quick-file-edit` on permalinks
  source/features/quick-file-edit.tsx
Labels: change request

#6892 Meta: Verify GQL files
  build/verify-features.ts
  source/features/link-to-changelog-file.tsx
Labels: meta

#6893 Match the behavior of function `isUrlReachable` to its name
  source/features/default-branch-button.tsx
  source/features/useful-not-found-page.tsx
  source/github-helpers/index.ts
Labels: meta

#6896 Meta: Extract `linkify-code` truncation logic to `linkify-urls`
  package-lock.json
  package.json
  source/features/linkify-code.tsx
  source/github-helpers/dom-formatters.tsx
Labels: meta

#6897 Add `mark-private-repos` feature
  source/features/mark-private-repos.css
  source/refined-github.ts
Labels: enhancement

#6898 Add support for "minimum font size" browser setting in `pr-approvals-count`
  source/features/pr-approvals-count.css
Labels: bug

#6901 Restore `releases-tab` when "Global Navigation Bar" is disabled
  source/features/releases-tab.tsx
  source/github-helpers/selectors.ts
Labels: bug

#6900 Add `repo-header-info` feature
  package-lock.json
  readme.md
  source/features/ci-link.tsx
  source/features/repo-header-info.gql
  source/features/repo-header-info.tsx
  source/refined-github.ts
Labels: enhancement

#6895 Add support for New Repository Overview in `unreleased-commits`
  readme.md
  source/features/unreleased-commits.tsx
  source/helpers/abbreviate-string.ts
Labels: bug

#6909 Faster `releases-tab` on repo home
  source/features/bugs-tab.tsx
  source/features/clean-repo-sidebar.tsx
  source/features/more-dropdown-links.css
  source/features/releases-tab.tsx
  source/github-helpers/index.ts
  source/github-helpers/selectors.ts
Labels: bug

#6908 Restore `clean-repo-header` feature
  readme.md
  source/features/clean-repo-header.css
  source/refined-github.ts
Labels: enhancement

#6910 Disable `dim-bots` only when clicking on empty areas
  source/features/dim-bots.tsx
  source/features/hide-navigation-hover-highlight.tsx
Labels: bug

#6920 Properly merge API requests
  source/features/pinned-issues-update-time.tsx
  source/features/show-names.tsx
Labels: bug

#6916 `show-names` - Exclude invalid elements on new dashboard
  source/features/show-names.tsx
Labels: bug

#6927 `unreleased-commits` - Restore support for old repository overview
  source/features/unreleased-commits.tsx
Labels: bug

#6924 `repo-header-info` - Bugfix: Also appears in wrong place
  source/features/repo-header-info.tsx
Labels: bug

#6931 Meta: Rename `GitHubURL` to `GitHubFileURL`
  source/features/actionable-pr-view-file.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conflict-marker.tsx
  source/features/deep-reblame.tsx
  source/features/default-branch-button.tsx
  source/features/linkify-branch-references.tsx
  source/features/list-prs-for-file.tsx
  source/features/more-file-links.tsx
  source/features/previous-version.tsx
  source/features/quick-file-edit.tsx
  source/features/rgh-dim-commits.tsx
  source/features/useful-not-found-page.tsx
  source/github-helpers/does-file-exist.tsx
  source/github-helpers/get-current-git-ref.ts
  source/github-helpers/github-file-url.test.ts
  source/github-helpers/github-file-url.ts
Labels: meta

#6932 `repo-header-info` - Add link and tooltip
  source/features/repo-header-info.tsx
Labels: enhancement

#6936 `link-to-changelog-file` - Drop extraneous character in tooltip
  source/features/link-to-changelog-file.tsx
Labels: bug

#6938 `linkify-code` - Fix console error
  package-lock.json
  package.json
Labels: bug

#6935 Drop `hide-own-stars` feature
  readme.md
  source/features/hide-own-stars.tsx
  source/refined-github.ts
Labels: change request

#6941 `clean-repo-header` - Let users disable it
  source/features/clean-repo-header.css
  source/features/clean-repo-header.tsx
  source/features/conversation-activity-filter.css
  source/refined-github.ts
Labels: change request

#6949 Add buttons to toggle all features at once
  source/options.html
  source/options.tsx
Labels: meta

#6948 Only show the options if JS has loaded correctly
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#6947 Add `rgh-pr-template` feature
  .github/pull_request_template.md
  source/features/rgh-pr-template.tsx
  source/refined-github.ts
Labels: meta

#6894 Meta: Async include functions
  source/feature-manager.tsx
  source/features/clean-conversation-filters.tsx
  source/features/clean-repo-tabs.tsx
  source/features/default-branch-button.tsx
  source/features/github-actions-indicators.tsx
  source/features/hide-low-quality-comments.tsx
  source/features/list-prs-for-branch.tsx
  source/features/open-all-conversations.tsx
  source/features/quick-file-edit.tsx
  source/features/quick-new-issue.tsx
  source/features/quick-repo-deletion.tsx
  source/features/unreleased-commits.tsx
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
  source/github-helpers/is-default-branch.ts
  source/helpers/feature-utils.test.ts
  source/helpers/feature-utils.ts
  source/helpers/p-utils.ts
Labels: meta

#6953 Meta: Replace JSDOM with linkedom
  package-lock.json
  package.json
  source/github-helpers/dom-formatters.tsx
  source/github-helpers/search-query.ts
  source/github-helpers/selectors.test.ts
  source/helpers/select-has.test.ts
  source/helpers/show-whitespace-on-line.test.ts
  test/__snapshots__/shorten-link.test.ts.snap
  test/fixtures/globals.js
  test/shorten-link.test.ts
Labels: meta
