Repository refined-github/refined-github, pull requests merged in 2023-12, with the labels that each got.

#7112 Hide inactive comment box tabs
  source/features/github-bugs.css
Labels: enhancement

#6465 `sticky-notifications-actions` - New feature
  readme.md
  source/features/sticky-notifications-actions.css
  source/refined-github.ts
Labels: enhancement

#7119 `quick-review` - Add "Approve PR" button to Conversation tab
  readme.md
  source/features/quick-review.tsx
  source/features/repo-age.tsx
  source/github-helpers/api.ts
  source/helpers/math.ts
Labels: enhancement

#7130 Meta: Support new screenshot URLs in readme parser
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/readme-parser.test.ts
  build/readme-parser.ts
  build/verify-features.ts
Labels: meta

#7100 Lint
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/__snapshots__/imported-features.txt
  build/readme-parser.test.ts
  package.json
  readme.md
  source/features/avoid-accidental-submissions.tsx
  source/features/conflict-marker.tsx
  source/features/highlight-collaborators-and-own-conversations.tsx
  source/features/link-to-changelog-file.tsx
  source/features/link-to-compare-diff.tsx
  source/features/linkify-notification-repository-header.tsx
  source/features/list-prs-for-file.tsx
  source/features/open-all-notifications.tsx
  source/features/pagination-hotkey.tsx
  source/features/rgh-feature-descriptions.tsx
  source/features/select-all-notifications-shortcut.tsx
  source/features/select-notifications.tsx
  source/features/show-names.tsx
  source/features/unreleased-commits.tsx
  source/features/visit-tag.tsx
  source/github-helpers/group-buttons.tsx
  source/helpers/dom-utils.ts
Labels: meta

#7139 `small-user-avatars` - Don't mistakenly add to commit authors
  source/features/small-user-avatars.tsx
Labels: bug

#7150 Meta: Improve release script
  .github/workflows/release.yml
Labels: meta

#7145 Meta: Move feature checker to vitest
  .github/workflows/features.yml
  .github/workflows/test.yml
  .xo-config.json
  build/__snapshots__/features-meta.json
  build/features.test.ts
  build/readme-parser.test.ts
  build/readme-parser.ts
  build/verify-features.ts
  package-lock.json
  package.json
  source/features/rgh-feature-descriptions.tsx
  source/github-helpers/prevent-link-loss.ts
  source/resolve-conflicts.ts
Labels: meta

#7131 Lint
  package-lock.json
  package.json
  source/features/copy-on-y.tsx
  source/features/deep-reblame.tsx
  source/features/embed-gist-inline.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/highest-rated-comment.tsx
  source/github-events/on-fragment-load.ts
  source/github-events/on-pr-merge-panel-open.ts
  source/github-helpers/api.ts
  source/github-helpers/index.ts
  source/github-helpers/pr-branches.test.ts
  source/github-helpers/selectors.test.ts
  source/github-helpers/selectors.ts
  source/helpers/click-all.ts
  source/helpers/fetch-dom.ts
  source/helpers/on-element-removal.ts
Labels: meta

#7146 `prevent-link-loss` - Restore support for all fields
  source/features/prevent-link-loss.tsx
Labels: bug

#7121 `unreleased-commits` - Add button to create release
  source/features/unreleased-commits.tsx
Labels: enhancement

#7162 `unreleased-commits` - Show on Releases page
  source/features/link-to-changelog-file.tsx
  source/features/unreleased-commits.tsx
Labels: enhancement

#7164 Meta: Restore CI tests
  .github/workflows/features.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  source/github-helpers/pr-branches.test.ts
  source/github-helpers/selectors.ts
Labels: meta

#7165 Meta: Update selector tests to expect an exact match count
  package-lock.json
  package.json
  source/features/open-issue-to-latest-comment.tsx
  source/github-helpers/get-current-git-ref.test.ts
  source/github-helpers/selectors.test.ts
  source/github-helpers/selectors.ts
  test/setup-file.js
  vite.config.ts
Labels: meta

#7168 `link-to-github-io` - Support new organization repository list style
  source/features/link-to-github-io.tsx
Labels: bug

#7169 `click-outside-modal` - New feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.txt
  build/features.test.ts
  readme.md
  source/features/click-outside-modal.tsx
  source/refined-github.ts
Labels: enhancement

#7104 `pr-notification-link` - New feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.txt
  readme.md
  source/features/pr-notification-link.tsx
  source/refined-github.ts
Labels: enhancement

#7175 Meta: Update vitest
  .github/workflows/test.yml
  package-lock.json
  package.json
  test/__snapshots__/shorten-link.test.ts.snap
Labels: meta

#7186 `one-click-diff-options` - Disable on single commits
  source/features/one-click-diff-options.tsx
Labels: bug

#7185 `conversation-links-on-repo-lists` - Disable on organizations
  source/features/conversation-links-on-repo-lists.tsx
Labels: bug

#7180 `rgh-dim-commits` - Add support for new commit view
  source/features/rgh-dim-commits.tsx
Labels: bug
