Repository refined-github/refined-github, pull requests merged in 2023-05, with the labels that each got.

#6594 Drop `bypass-checks` feature
  readme.md
  source/features/bypass-checks.tsx
  source/refined-github.ts
Labels: change request

#6604 Restore `quick-review-comment-deletion`
  source/features/quick-review-comment-deletion.tsx
Labels: bug

#6610 Meta: Improve DX when features are not yet finalized
  source/feature-manager.tsx
Labels: meta

#6592 Automatically set popup to contain options on iOS
  package-lock.json
  package.json
  source/background.ts
  source/options-storage.ts
  source/options.tsx
Labels: meta, safari, mobile

#6595 Meta: Include information about storage in options
  package-lock.json
  package.json
  source/background.ts
  source/helpers/types.d.ts
  source/helpers/used-storage.ts
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#6619 Restore `one-click-review-submissions`
  source/features/one-click-review-submission.tsx
Labels: bug

#6621 `restore-file` UX improvements
  readme.md
  source/features/restore-file.tsx
Labels: enhancement

#6620 Meta: Update feature screenshots
  readme.md
Labels: meta

#6617 Make CSS hotfixes visible in the options
  source/feature-manager.tsx
  source/options.html
  source/options.tsx
Labels: enhancement, under discussion

#6627 Some fixes around `quick-file-edit`
  source/features/default-branch-button.tsx
  source/features/quick-file-edit.tsx
  source/github-helpers/get-default-branch.ts
  source/github-helpers/index.ts
  source/github-helpers/selectors.ts
Labels: bug

#6550 Add `previous-version` feature
  readme.md
  source/features/previous-version.tsx
  source/refined-github.ts
Labels: enhancement

#6630 Lint (ESM file imports 2)
  .xo-config.json
  build/readme-parser.ts
  source/features/default-branch-button.tsx
  source/features/previous-version.tsx
  source/features/quick-file-edit.tsx
  source/github-helpers/index.ts
  source/helpers/show-whitespace-on-line.test.ts
  source/options.tsx
  source/refined-github.ts
  test/get-current-committish.test.ts
  test/shorten-link.test.ts
  vite.config.ts
Labels: meta

#6631 Fix Code-button error in `clean-repo-filelist-actions`
  source/features/clean-repo-filelist-actions.tsx
Labels: bug

#6635 Restore PR review buttons on GitHub Enterprise
  source/features/one-click-review-submission.tsx
Labels: bug

#6629 Reliability fixes for `default-branch-button`
  .git-blame-ignore-revs
  source/features/comments-time-machine-links.tsx
  source/features/default-branch-button.tsx
  source/features/list-prs-for-branch.tsx
  source/features/more-dropdown-links.tsx
  source/features/repo-wide-file-finder.tsx
  source/features/unreleased-commits.tsx
  source/github-helpers/get-current-git-ref.test.ts
  source/github-helpers/get-current-git-ref.ts
  source/github-helpers/get-default-branch.ts
  source/github-helpers/github-url.ts
  source/github-helpers/index.ts
  source/github-helpers/is-default-branch.ts
  test/fixtures/globals.js
Labels: bug

#6638 `fit-textareas` after `clear-pr-merge-commit-message`
  source/features/clear-pr-merge-commit-message.tsx
  source/features/sync-pr-commit-title.tsx
Labels: bug

#6636 Default branch and current branch detector improvements
  source/features/default-branch-button.tsx
  source/features/download-folder-button.tsx
  source/features/fork-source-link-same-view.tsx
  source/features/warn-pr-from-master.tsx
  source/github-helpers/get-current-git-ref.test.ts
  source/github-helpers/get-current-git-ref.ts
  source/github-helpers/get-default-branch.ts
  source/github-helpers/github-url.ts
  source/github-helpers/index.ts
  source/github-helpers/prevent-link-loss.ts
  source/github-helpers/selectors.test.ts
  source/github-helpers/selectors.ts
  test/fixtures/globals.js
Labels: bug

#6640 Add basic support for fine-grained tokens
  source/options.html
  source/options.tsx
Labels: enhancement

#6641 Improve reliability of `list-prs-for-branch`
  source/features/default-branch-button.tsx
  source/features/list-prs-for-branch.tsx
  source/features/unreleased-commits.tsx
  source/github-helpers/api.ts
  source/github-helpers/get-current-git-ref.ts
  source/github-helpers/get-default-branch.ts
  source/github-helpers/index.ts
  source/github-helpers/selectors.ts
  source/helpers/add-after-branch-selector.tsx
Labels: bug

#6645 Improve `rgh-feature-descriptions` links
  build/verify-features.ts
  source/background.ts
  source/feature-manager.tsx
  source/features/rgh-feature-descriptions.tsx
  source/helpers/feature-utils.ts
  source/options-storage.ts
  source/options.tsx
Labels: meta

#6623 Fix `open-all-notifications` error display
  source/features/open-all-notifications.tsx
  source/helpers/open-tabs.ts
Labels: bug

#6612 Meta: Use dynamic file list in Xcode
  safari/Refined GitHub.xcodeproj/project.pbxproj
  source/background.ts
  source/features/resolve-conflicts.tsx
  source/manifest.json
  source/options.css
  webpack.config.ts
Labels: meta, safari

#6622 Improve `prevent-link-loss` layou on mobile
  source/features/prevent-link-loss.tsx
  source/github-helpers/banner.tsx
Labels: bug

#6647 Fix `ci-link` duplicates on mobile
  source/features/ci-link.tsx
Labels: bug, mobile

#6488 Lint
  source/feature-manager.tsx
  source/features/highlight-collaborators-and-own-conversations.tsx
  source/features/show-whitespace.css
  source/features/small-user-avatars.tsx
Labels: meta

#6649 Ignore `clean-repo-sidebar` report link error
  source/features/clean-repo-sidebar.tsx
Labels: bug

#6653 Meta: Ensure new or edited features have Test URLs
  .github/workflows/features.yml
  build/verify-test-urls.sh
Labels: meta

#6654 Meta: Fix typo in readme
  readme.md
Labels: meta

#6655 Fix notification action bar style
  source/features/open-all-notifications.tsx
  source/refined-github.css
Labels: bug

#6671 Lint API usage
  build/verify-test-urls.sh
  source/features/bugs-tab.tsx
  source/features/ci-link.tsx
  source/features/clean-conversation-filters.tsx
  source/features/clean-repo-tabs.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conflict-marker.tsx
  source/features/convert-release-to-draft.tsx
  source/features/deep-reblame.tsx
  source/features/github-actions-indicators.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/link-to-changelog-file.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/mark-private-orgs.tsx
  source/features/new-repo-disable-projects-and-wikis.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-base-commit.tsx
  source/features/pr-commit-lines-changed.tsx
  source/features/pr-filters.tsx
  source/features/previous-version.tsx
  source/features/profile-gists-link.tsx
  source/features/quick-label-removal.tsx
  source/features/quick-repo-deletion.tsx
  source/features/release-download-count.tsx
  source/features/releases-dropdown.tsx
  source/features/releases-tab.tsx
  source/features/repo-age.tsx
  source/features/restore-file.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-names.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/sync-pr-commit-title.tsx
  source/features/tags-on-commits-list.tsx
  source/features/unreleased-commits.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-local-time.tsx
  source/features/user-profile-follower-badge.tsx
  source/github-helpers/api.ts
  source/github-helpers/does-file-exist.tsx
  source/github-helpers/get-default-branch.ts
  source/github-helpers/get-pr-info.ts
  source/github-helpers/pr-ci-status.ts
Labels: meta

#6670 Use correct file after merges in in `restore-file`
  source/features/restore-file.tsx
  source/github-helpers/get-pr-info.ts
Labels: bug

#6673 Restore `wait-for-checks` (no more Firefox support)
  build/verify-test-urls.sh
  source/features/wait-for-checks.tsx
  source/github-helpers/pr-ci-status.ts
  source/github-helpers/selectors.test.ts
  source/github-helpers/selectors.ts
Labels: bug

#6680 Meta: Improve "Test URLs" annotations
  build/verify-test-urls.sh
  source/background.ts
  source/features/rgh-linkify-yolo-issues.tsx
Labels: meta

#6684 Hide reason text in `status-subscription`
  source/features/status-subscription.tsx
Labels: enhancement

#6674 Meta: Use variables in GraphQL
  .xo-config.json
  build/verify-features.ts
  source/features/bugs-tab.tsx
  source/features/clean-conversation-filters.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conversation-activity-filter.tsx
  source/features/deep-reblame.css
  source/features/deep-reblame.tsx
  source/features/highlight-deleted-and-added-files-in-diffs.tsx
  source/features/list-prs-for-file.gql
  source/features/list-prs-for-file.tsx
  source/features/pr-commit-lines-changed.tsx
  source/features/previous-version.tsx
  source/features/profile-gists-link.tsx
  source/features/repo-age.tsx
  source/features/restore-file.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/useful-not-found-page.tsx
  source/github-helpers/api.ts
  source/github-helpers/does-file-exist.tsx
  source/github-helpers/get-default-branch.ts
  source/github-helpers/pr-ci-status.ts
  source/globals.d.ts
  source/options.html
  source/options.tsx
  webpack.config.ts
Labels: meta

#6672 Open options in a new tab on iOS Safari
  source/background.ts
  source/helpers/feature-utils.ts
  source/options.tsx
Labels: safari, mobile

#6675 Meta: Automatically clear cache on reload while developing
  source/background.ts
Labels: meta

#6682 Hide `conversation-activity-filter` on PR Files tab
  source/features/conversation-activity-filter.css
Labels: bug

#6677 Better wrap: `clean-pinned-issues`/`pinned-issues-update-time`
  readme.md
  source/features/clean-pinned-issues.css
  source/features/pinned-issues-update-time.tsx
  source/features/small-user-avatars.tsx
Labels: enhancement, change request

#6692 Fix page number calculation in `last-notification-page-button`
  source/features/last-notification-page-button.tsx
Labels: bug

#6695 Fix `quick-review` position due to race condition
  source/features/quick-review.tsx
Labels: bug

#6696 Avoid `wait-for-checks` conflicts with GitHub’s AutoMerge
  source/features/wait-for-checks.tsx
Labels: bug

#6698 Fix: “Clear filters” doesn’t work due to `hide-user-forks`
  source/features/hide-user-forks.tsx
Labels: bug
