Repository refined-github/refined-github, pull requests merged in 2023-11, with the labels that each got.

#7005 `linkify-code` - Fix issue links on global search pages
  source/features/linkify-code.tsx
Labels: bug

#7004 `small-user-avatars` - Adjust spacing
  source/features/highlight-collaborators-and-own-conversations.css
  source/features/small-user-avatars.css
  source/features/small-user-avatars.tsx
Labels: bug

#6973 `close-as-unplanned` - New feature
  readme.md
  source/features/close-as-unplanned.tsx
  source/refined-github.ts
Labels: enhancement

#6991 Remind users to be kind when commenting
  source/features/netiquette.tsx
Labels: enhancement

#7019 `clean-rich-text-editor` - Restore feature
  source/features/clean-rich-text-editor.css
Labels: bug

#7021 `collapsible-content-button` - Restore feature
  source/features/collapsible-content-button.tsx
Labels: bug

#7022 `table-input` - Restore feature
  source/features/table-input.tsx
Labels: bug

#7025 `close-as-planned` - Fix "close with comment" bug
  source/features/close-as-unplanned.tsx
Labels: bug

#7027 `releases-tab`: Hide dropdown item when there are no releases
  source/features/releases-tab.tsx
Labels: bug

#7032 `link-to-changelog-file`: Drop broken `parseFromDom`
  source/features/link-to-changelog-file.tsx
Labels: bug, meta

#7031 `releases-tab`: Add support for tags-only repos
  source/features/closing-remarks.tsx
  source/features/releases-tab.gql
  source/features/releases-tab.tsx
Labels: enhancement

#7033 `pr-jump-to-first-non-viewed-file` - Restore feature in all PRs
  source/features/pr-jump-to-first-non-viewed-file.tsx
Labels: bug

#7041 `bugs-tab` - Support the labels `triage:bug` and `triage/bug`
  source/github-helpers/bugs-label.test.ts
  source/github-helpers/bugs-label.ts
Labels: enhancement

#7042 `table-input` and `collapsible-content-button` - Silence Firefox error
  source/features/collapsible-content-button.tsx
  source/features/table-input.css
  source/features/table-input.tsx
Labels: bug, firefox

#7036 `easy-toggle-files` - Apply to code search
  source/features/easy-toggle-files.tsx
  source/github-helpers/selectors.ts
Labels: enhancement

#7038 `clean-checks-list` - Untruncate check descriptions
  source/features/clean-checks-list.css
Labels: enhancement

#7053 Fix "Hotfixes are not applied on GitHub Enterprise." error
  package-lock.json
  package.json
  source/options-storage.ts
  source/options.tsx
Labels: bug, meta

#7054 Lint
  .github/workflows/features.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  source/features/ci-link.css
  source/features/clean-repo-tabs.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conversation-activity-filter.tsx
  source/features/download-folder-button.css
  source/features/download-folder-button.tsx
  source/features/quick-mention.css
  source/features/quick-new-issue.tsx
  source/features/rgh-pr-template.tsx
  source/features/show-names.tsx
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
  source/options.tsx
Labels: meta

#7051 `locked-issue` - New feature
  readme.md
  source/features/locked-issue.css
  source/features/locked-issue.tsx
  source/refined-github.ts
Labels: enhancement

#7056 `one-click-review-submission` - Fix "Abandon review" position
  source/features/one-click-review-submission.tsx
Labels: bug

#7058 `wait-for-attachments` - Drop feature
  readme.md
  source/features/wait-for-attachments.tsx
  source/refined-github.ts
Labels: change request

#7057 `minimize-upload-bar` - Drop feature
  readme.md
  source/features/minimize-upload-bar.css
  source/features/minimize-upload-bar.tsx
  source/refined-github.ts
Labels: change request

#7060 Move "Toggle all features" into the "Identify feature" section
  source/options.html
Labels: meta

#7061 Fix: Some features show information from the wrong/previous repository visited
  source/github-helpers/api.ts
Labels: bug, ajax

#7062 `default-branch-button` - Don't show on the default branch
  source/github-helpers/is-default-branch.ts
Labels: bug

#7065 `locked-issue` - Disable on GitHub Enterprise
  source/features/locked-issue.tsx
Labels: bug, enterprise

#7072 `locked-issue` - Disable on logged out users due to false positives
  source/features/locked-issue.tsx
Labels: bug

#7071 `quick-mention` - Fix "locked issue" detection
  source/features/quick-mention.css
  source/features/quick-mention.tsx
Labels: bug

#7069 `vertical-front-matter` - Fix flickering/loss of the feature on content rehydration
  source/features/vertical-front-matter.tsx
Labels: bug

#7075 `locked-issue` - Remove after unlocking issue
  source/features/locked-issue.css
  source/features/locked-issue.tsx
Labels: bug

#7055 `prevent-comment-loss` - New feature
  readme.md
  source/features/prevent-comment-loss.tsx
  source/refined-github.ts
Labels: enhancement

#7083 `tags-on-commits-list` - Support new commit list style
  readme.md
  source/features/mark-merge-commits-in-list.tsx
  source/features/tags-on-commits-list.tsx
Labels: bug

#7087 `mark-merge-commits-in-list` - Support new commit list style
  readme.md
  source/features/mark-merge-commits-in-list.tsx
Labels: bug

#7092 `dim-bots` - Support new commit list style
  source/features/dim-bots.css
  source/features/dim-bots.tsx
  source/features/mark-merge-commits-in-list.css
Labels: bug

#7094 `list-prs-for-file` - Fix overlap with other components
  source/features/list-prs-for-file.css
  source/features/list-prs-for-file.tsx
Labels: bug

#7095 `default-branch-button` - Fix mistaken display on commits list
  source/features/default-branch-button.tsx
  source/github-helpers/is-default-branch.ts
Labels: bug

#7089 `mark-merge-commits-in-list` - Avoid duplicating icon
  source/features/mark-merge-commits-in-list.tsx
Labels: enhancement

#7088 `select-notifications` - Add filter for "Anything other than issues and PRs"
  source/features/select-notifications.tsx
Labels: enhancement

#7090 `visit-tag` - New feature
  readme.md
  source/features/visit-tag.tsx
  source/refined-github.ts
Labels: enhancement

#7117 `highlight-non-default-base-branch` - Use selector-observer
  source/features/highlight-non-default-base-branch.tsx
Labels: enhancement, meta

#7099 `mark-merge-commits-in-list` - Use selector-observer
  source/features/mark-merge-commits-in-list.tsx
Labels: enhancement, meta

#7105 `unwrap-unnecessary-dropdowns` - Restore feature
  source/features/unwrap-unnecessary-dropdowns.tsx
Labels: bug

#7127 `visit-tag` - Enable on single releases
  source/features/visit-tag.tsx
Labels: bug
