Repository refined-github/refined-github, pull requests merged in 2023-02, with the labels that each got.

#6252 Restore `copy-on-y` and enable it on every page
  source/features/copy-on-y.tsx
Labels: bug

#6267 Reduce content shift on navigation
  source/feature-manager.tsx
Labels: bug, ajax

#6266 Restore `clean-header-search-field`
  source/features/clean-header-search-field.tsx
Labels: bug

#6262 Restore `download-folder-button`
  source/features/download-folder-button.tsx
Labels: bug

#6261 Remember `one-click-diff-options` state
  source/features/one-click-diff-options.tsx
  source/helpers/dom-utils.ts
Labels: bug

#6251 Avoid misplacement of `profile-gists-link`
  source/features/profile-gists-link.tsx
  source/github-helpers/create-dropdown-item.tsx
Labels: bug

#6246 Restore `mark-merge-commits-in-list` in PRs
  source/features/mark-merge-commits-in-list.tsx
Labels: bug

#6264 Restore `linkify-user-labels`
  source/features/clean-conversation-headers.css
  source/features/linkify-user-labels.tsx
Labels: bug

#6248 Drop `global-search-filters` feature
  readme.md
  source/features/global-search-filters.tsx
  source/refined-github.ts
Labels: implemented by github

#6247 Drop `align-repository-header` feature
  readme.md
  source/features/align-repository-header.css
  source/refined-github.ts
Labels: change request

#6245 Restore `release-download-count`
  source/features/release-download-count.tsx
Labels: bug

#6255 Restore `hide-diff-signs` on edit pages’ Preview
  source/features/hide-diff-signs.css
Labels: bug

#6212 Drop duplicate hotfix notice in the options page
  source/options.css
  source/options.tsx
Labels: meta

#6277 Shrink text field after `clear-pr-merge-commit-message`
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#6249 Restore `default-branch-button`
  source/features/default-branch-button.css
  source/features/default-branch-button.tsx
  source/github-helpers/group-buttons.tsx
  source/refined-github.css
Labels: bug

#6253 Restore `rgh-feature-descriptions`
  source/features/rgh-feature-descriptions.css
  source/features/rgh-feature-descriptions.tsx
Labels: meta

#6260 Fix global search dropdown overlap caused by `sticky-sidebar`
  source/features/sticky-sidebar.css
Labels: bug

#6270 Minor correction in `feature.add` examples in contributing.md
  contributing.md
Labels: meta

#6278 Fix GitHub bug: header overflow on homepage on mobile
  source/features/github-bugs.css
Labels: enhancement, github bug

#6280 Fetch correct item from cache after an ajax navigation
  package-lock.json
  package.json
Labels: bug, ajax

#6254 Update links in `sticky-file-header`
  source/features/sticky-file-header.css
Labels: meta

#6298 Improve `releases-tab` reliability
  source/features/releases-tab.tsx
Labels: bug

#6281 Add `rgh-linkify-yolo-issues` feature
  source/features/rgh-linkify-yolo-issues.tsx
  source/github-helpers/index.ts
  source/refined-github.ts
Labels: meta

#6286 Update `webext-domain-permission-toggle`
  package-lock.json
  package.json
Labels: enterprise

#6296 Drop `file-finder-buffer` feature
  readme.md
  source/features/file-finder-buffer.css
  source/features/file-finder-buffer.tsx
  source/refined-github.ts
Labels: change request

#6292 Add name and "Copy name" button to `rgh-feature-descriptions`
  source/features/rgh-feature-descriptions.css
  source/features/rgh-feature-descriptions.tsx
Labels: meta

#6290 Use new File Finder view in `repo-wide-file-finder`
  source/features/repo-wide-file-finder.tsx
Labels: bug

#6265 Limit `fork-source-link-same-view` to known-good pages
  source/features/fork-source-link-same-view.tsx
Labels: bug, under discussion

#6256 Fix `github-actions-indicators` wording and tooltip
  readme.md
  source/features/github-actions-indicators.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: bug, under discussion

#6306 Correctly hide grouped "Follow" events in `hide-newsfeed-noise`
  source/features/hide-newsfeed-noise.css
Labels: bug

#6312 Restore `download-folder-button` for non-beta users
  source/features/download-folder-button.css
  source/features/download-folder-button.tsx
Labels: bug

#6311 Restore `clean-header-search-field` for some users
  source/features/clean-header-search-field.tsx
Labels: bug

#6303 Enable `link-to-github-io` for `.github.com` repos
  source/features/link-to-github-io.tsx
Labels: enhancement

#6313 Fix GitHub header overflow bug on every page
  source/features/github-bugs.css
Labels: enhancement, github bug

#6314 Restore `comment-fields-keyboard-shortcuts`
  package-lock.json
  package.json
  source/globals.d.ts
Labels: bug

#6326 Lint
  .xo-config.json
  package-lock.json
  package.json
  source/features/clean-conversation-sidebar.tsx
  source/features/comment-fields-keyboard-shortcuts.tsx
  source/features/dim-bots.tsx
  source/features/highest-rated-comment.tsx
  source/features/keyboard-navigation.tsx
  source/features/linkify-user-location.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/parse-backticks.tsx
  source/features/quick-label-removal.tsx
  source/features/quick-review.tsx
  source/features/rgh-welcome-issue.tsx
  source/features/show-whitespace.tsx
  source/features/user-local-time.tsx
  source/github-helpers/dom-formatters.ts
  source/helpers/types.d.ts
  source/manifest.json
  tsconfig.json
  webpack.config.ts
Labels: meta

#6322 Enable `quick-mention` in more places
  source/features/quick-mention.tsx
Labels: bug

#6318 Fixed partially broken `tag-changes-link`
  source/features/tag-changes-link.tsx
Labels: bug

#6316 Enable `reaction-avatars` on organization discussions
  package-lock.json
  package.json
  source/features/reactions-avatars.tsx
Labels: bug

#6315 Fix `sticky-sidebar` on repo's "Code" tab
  source/features/sticky-sidebar.css
Labels: bug

#6320 Add support for PR review comments to `quick-comment-hiding`
  source/features/quick-comment-hiding.tsx
  source/globals.d.ts
Labels: bug

#6325 Drop discussion support from `quick-comment-edit`
  source/features/quick-comment-edit.tsx
Labels: change request

#6327 Enable some features before the page has finished loading
  source/features/edit-readme.tsx
  source/features/quick-comment-edit.tsx
  source/features/quick-mention.tsx
  source/github-helpers/index.ts
Labels: enhancement

#6330 Run `clear-pr-merge-commit-message` only once per load
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#6328 Fix "closing keyword" logic in `clear-pr-merge-commit-message`
  package-lock.json
  package.json
  source/features/clear-pr-merge-commit-message.tsx
  source/features/update-pr-from-base-branch.tsx
  source/github-helpers/pr-branches.ts
  source/helpers/clean-commit-message.test.ts
  source/helpers/clean-commit-message.ts
Labels: bug

#6323 Restore alt-clicks in `batch-mark-files-as-viewed`
  source/features/batch-mark-files-as-viewed.tsx
Labels: bug

#6329 Better wrap 6 reactions in releases in `center-reactions-popup`
  source/features/center-reactions-popup.css
Labels: bug

#6324 Make `create-release-shortcut` more resilient
  source/features/create-release-shortcut.tsx
  source/features/submission-via-ctrl-enter-everywhere.tsx
Labels: bug

#6332 Add `quick-new-issue` feature
  readme.md
  source/features/quick-new-issue.tsx
  source/refined-github.ts
Labels: enhancement

#6333 Let user disable 3 more CSS features
  readme.md
  source/features/clean-repo-header.css
  source/features/clean-repo-header.tsx
  source/features/emphasize-draft-pr-label.css
  source/features/emphasize-draft-pr-label.tsx
  source/features/hide-watch-and-fork-count.css
  source/features/scrollable-areas.css
  source/features/scrollable-areas.tsx
  source/refined-github.css
  source/refined-github.ts
Labels: change request

#6354 Drop `copy-file` feature
  readme.md
  source/features/copy-file.tsx
  source/refined-github.ts
Labels: implemented by github

#6355 Drop `same-page-definition-jump` feature
  readme.md
  source/features/same-page-definition-jump.tsx
  source/refined-github.ts
Labels: implemented by github

#6341 Use `batched-function` module
  package-lock.json
  package.json
  source/features/show-names.tsx
  source/helpers/batched-function.ts
Labels: meta

#6340 Add `file-age-color` feature
  readme.md
  source/features/file-age-color.tsx
  source/features/release-download-count.tsx
  source/refined-github.ts
Labels: enhancement

#6335 Correctly escape tags in the tooltip of `tag-changes-link`
  source/features/tag-changes-link.tsx
Labels: bug

#6346 Properly clear field in `clear-pr-merge-commit-message`
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#6356 Drop `open-ci-details-in-new-tab` feature
  readme.md
  source/features/open-ci-details-in-new-tab.tsx
  source/refined-github.ts
Labels: change request

#6363 Drop `link-to-prior-blame-line` feature
  readme.md
  source/features/link-to-prior-blame-line.tsx
  source/refined-github.ts
Labels: implemented by github

#6145 Meta: Improve release workflow
  .github/workflows/release.yml
Labels: meta

#6375 Avoid console error in `html-preview-link`
  source/features/html-preview-link.tsx
Labels: bug

#6374 Improve UX of `dim-bots` by disabling the feature on click
  readme.md
  source/features/dim-bots.css
  source/features/dim-bots.tsx
  source/features/mark-merge-commits-in-list.css
  source/features/mark-merge-commits-in-list.tsx
Labels: change request

#6370 Meta: Update `typed-query-selector`
  package-lock.json
  package.json
  source/features/bypass-checks.tsx
  source/features/show-names.tsx
  source/features/sort-conversations-by-update-time.tsx
  source/helpers/types.d.ts
Labels: meta

#6385 Sort Refined GitHub shortcuts in Shortcut Help dialog
  source/features/improve-shortcut-help.tsx
  source/features/pull-request-hotkeys.tsx
Labels: enhancement

#6384 Collapse sections in options page
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta
