Repository refined-github/refined-github, pull requests merged in 2024-09, with the labels that each got.

#7776 `repo-header-info` - Shows whether you starred the repo
  source/features/repo-header-info.gql
  source/features/repo-header-info.tsx
Labels: enhancement

#7775 `easy-toggle-commit-messages` - Restore feature
  source/features/easy-toggle-commit-messages.tsx
Labels: bug

#7796 `conventional-commits` - New feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/features.test.ts
  build/readme-parser.ts
  readme.md
  source/features/conventional-commits.css
  source/features/conventional-commits.tsx
  source/helpers/conventional-commits.test.ts
  source/helpers/conventional-commits.ts
  source/refined-github.ts
Labels: enhancement

#7810 Drop link to deleted `Undo-unwanted-styles` wiki page
  source/helpers/bisect.tsx
Labels: meta

#7813 `conventional-commits` - Cleanup
  build/__snapshots__/features-meta.json
  readme.md
  source/features/conventional-commits.css
  source/features/conventional-commits.tsx
  source/helpers/conventional-commits.test.ts
  source/helpers/conventional-commits.ts
  source/helpers/dom-utils.ts
Labels: enhancement

#7785 `pr-branch-auto-delete` - Skip long-lived branches
  build/__snapshots__/features-meta.json
  readme.md
  source/features/pr-branch-auto-delete.tsx
  source/helpers/matches-any-patterns.ts
Labels: enhancement

#7804 `default-branch-button` - Highlight non default branch button
  source/features/default-branch-button.css
  source/features/default-branch-button.tsx
Labels: enhancement

#7824 `embed-gist-inline` - Restore feature
  package-lock.json
  package.json
  source/background.ts
  source/feature-manager.tsx
  source/features/embed-gist-inline.tsx
  source/features/quick-repo-deletion.tsx
  source/features/selection-in-new-tab.tsx
  source/helpers/messaging.ts
  source/helpers/open-options.ts
  source/helpers/open-tabs.ts
Labels: bug

#7496 `list-prs-for-file` - Use new style
  source/features/list-prs-for-file.tsx
  source/globals.d.ts
Labels: enhancement

#7838 `list-prs-for-file` - Simplify code
  source/features/list-prs-for-file.tsx
Labels: enhancement

#7830 `quick-repo-deletion` - Drop `delete_repo` permission
  build/__snapshots__/features-meta.json
  readme.md
  source/features/quick-repo-deletion.css
  source/features/quick-repo-deletion.tsx
  source/options.html
Labels: change request

#7833 Show version in options page
  source/features/conversation-activity-filter.tsx
  source/options.html
  source/options.tsx
Labels: meta

#7837 `download-folder-button` - Hide if the native link is available
  source/features/download-folder-button.tsx
Labels: bug

#7836 `tags-on-commits` - Restore feature
  source/github-helpers/selectors.ts
Labels: bug

#7829 `pr-branch-auto-delete` - Exclude `staging`
  source/features/pr-branch-auto-delete.tsx
Labels: enhancement

#7816 `conventional-commits` - Various fixes
  source/features/conventional-commits.css
  source/features/conventional-commits.tsx
  source/helpers/conventional-commits.ts
  source/helpers/dom-utils.ts
Labels: bug

#7831 Meta: Reorganize options page code
  source/options.tsx
  source/options/feature-list.tsx
  tsconfig.json
Labels: meta
