Repository refined-github/refined-github, pull requests merged in 2024-02, with the labels that each got.

#7238 `use-first-commit-message-for-new-prs` rename to `pr-first-commit-title`
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.txt
  readme.md
  source/features/pr-first-commit-title.tsx
  source/options-storage.ts
  source/refined-github.ts
Labels: meta

#7237 `pr-first-commit-title` - Preserve previous user changes
  source/features/pr-first-commit-title.tsx
Labels: bug

#7240 Update style of repo navigation dropdown
  source/features/more-dropdown-links.tsx
  source/features/profile-gists-link.tsx
  source/features/releases-tab.tsx
  source/github-helpers/create-dropdown-item.tsx
  source/github-helpers/selectors.ts
Labels: bug

#7242 `deep-reblame` - Restore feature
  source/features/deep-reblame.css
  source/features/deep-reblame.tsx
Labels: bug

#7243 `closing-remarks` - Exclude nightly tags and non-version tags
  source/features/closing-remarks.tsx
  tsconfig.json
Labels: enhancement

#7244 `show-names` - Avoid duplicates on GitHub Enterprise
  source/features/show-names.tsx
Labels: bug, enterprise

#7249 `wait-for-checks` - Drop feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.txt
  readme.md
  source/features/unfinished-comments.tsx
  source/features/wait-for-checks.css
  source/features/wait-for-checks.tsx
  source/github-events/on-fragment-load.ts
  source/github-events/on-pr-merge-panel-open.ts
  source/helpers/simplified-element-observer.ts
  source/options-storage.ts
  source/refined-github.ts
Labels: change request

#7252 Fix constant Safari crashes due to browser's CSS selector parsing bug
  source/features/show-associated-branch-prs-on-fork.css
Labels: bug, safari

#7221 Include more features in API usage list
  source/options.html
Labels: meta

#7275 `releases-tab` - Mention that it requires a token
  source/features/releases-tab.tsx
Labels: meta
