Repository refined-github/refined-github, pull requests merged in 2024-11, with the labels that each got.

#7993 `bugs-tab` - Support `issue-bug`
  source/github-helpers/bugs-label.test.ts
  source/github-helpers/bugs-label.ts
Labels: enhancement

#7996 Meta: Extract `webext-msg`
  package-lock.json
  package.json
  source/background.ts
  source/feature-manager.tsx
  source/features/embed-gist-inline.tsx
  source/features/selection-in-new-tab.tsx
  source/helpers/messaging.ts
  source/helpers/open-options.ts
  source/helpers/open-tabs.ts
Labels: meta

#8002 Warn user of mismatch between token user and logged-in user
  build/__snapshots__/imported-features.json
  source/features/rgh-feature-descriptions.tsx
  source/features/rgh-improve-new-issue-form.tsx
  source/features/rgh-token-user.tsx
  source/github-helpers/api.ts
  source/helpers/open-options.ts
  source/helpers/open-options.tsx
  source/refined-github.ts
Labels: meta

#7999 Options page: Count disabled features
  source/options/feature-list.tsx
Labels: meta

#7997 Meta: Drop `additionalListeners`
  source/feature-manager.tsx
  source/features/batch-mark-files-as-viewed.tsx
  source/features/closing-remarks.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/reactions-avatars.tsx
  source/features/show-whitespace.tsx
  source/features/sticky-sidebar.tsx
  source/github-events/on-pr-merge.ts
  source/helpers/abort-controller.ts
Labels: meta

#7998 `rgh-linkify-yolo` - Support feature names
  build/__snapshots__/imported-features.json
  source/features/pr-branch-auto-delete.tsx
  source/features/rgh-feature-descriptions.tsx
  source/features/rgh-linkify-features.tsx
  source/features/rgh-linkify-yolo.tsx
  source/helpers/bisect.tsx
  source/helpers/feature-link.ts
  source/helpers/rgh-issue-link.tsx
  source/helpers/rgh-links.tsx
  source/options/feature-list.tsx
  source/refined-github.ts
Labels: meta

#8005 `tags-on-commits` - Improve GitHub Enterprise compatibility
  package-lock.json
  package.json
  source/features/tags-on-commits-list.tsx
Labels: bug, enterprise

#8001 `clean-converstion-headers` - Support new PR view
  package-lock.json
  package.json
  source/features/clean-conversation-headers.css
  source/features/clean-conversation-headers.tsx
Labels: bug

#8007 `conversation-activity-filter` - Restore on issues
  source/features/conversation-activity-filter.tsx
Labels: bug

#8008 `unread-anywhere` - Add feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  readme.md
  source/features/avoid-accidental-submissions.tsx
  source/features/unread-anywhere.tsx
  source/github-helpers/api.ts
  source/github-helpers/hotkey.tsx
  source/github-helpers/toast.tsx
  source/helpers/fetch-dom.ts
  source/refined-github.ts
Labels: enhancement

#8011 `jump-to-conversation-close-event` - Support new issue view
  source/features/jump-to-conversation-close-event.tsx
  source/features/netiquette.tsx
Labels: bug

#8010 `netiquette` - Support new text fields
  source/features/netiquette.tsx
  source/features/quick-comment-hiding.tsx
  source/features/rgh-netiquette.tsx
  source/github-helpers/selectors.ts
  source/helpers/loose-parse-int.ts
Labels: bug

#8014 Meta: Fix build warnings
  eslint.config.js
  package-lock.json
  package.json
  source/feature-manager.tsx
  source/features/avoid-accidental-submissions.tsx
  source/features/batch-mark-files-as-viewed.tsx
  source/features/click-outside-modal.tsx
  source/features/close-as-unplanned.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/collapsible-content-button.tsx
  source/features/command-palette-navigation-shortcuts.tsx
  source/features/convert-pr-to-draft-improvements.tsx
  source/features/deep-reblame.tsx
  source/features/dim-bots.tsx
  source/features/easy-toggle-commit-messages.tsx
  source/features/easy-toggle-files.tsx
  source/features/esc-to-cancel.tsx
  source/features/expand-all-hidden-comments.tsx
  source/features/extend-diff-expander.tsx
  source/features/fix-no-pr-search.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/hide-low-quality-comments.tsx
  source/features/linkify-line-numbers.tsx
  source/features/more-file-links.tsx
  source/features/one-click-review-submission.tsx
  source/features/one-key-formatting.tsx
  source/features/open-all-conversations.tsx
  source/features/open-all-notifications.tsx
  source/features/pr-base-commit.tsx
  source/features/prevent-comment-loss.tsx
  source/features/prevent-duplicate-pr-submission.tsx
  source/features/prevent-link-loss.tsx
  source/features/quick-comment-hiding.tsx
  source/features/quick-label-removal.tsx
  source/features/quick-mention.tsx
  source/features/quick-repo-deletion.tsx
  source/features/quick-review-comment-deletion.tsx
  source/features/quick-review.tsx
  source/features/releases-dropdown.tsx
  source/features/reload-failed-proxied-images.tsx
  source/features/restore-file.tsx
  source/features/rgh-improve-new-issue-form.tsx
  source/features/stop-redirecting-in-notification-bar.tsx
  source/features/table-input.tsx
  source/features/update-pr-from-base-branch.tsx
  source/github-events/on-commit-title-update.ts
  source/github-events/on-field-keydown.tsx
  source/github-helpers/api.ts
  source/github-helpers/banner.tsx
  source/github-helpers/index.ts
  source/github-helpers/prevent-link-loss.ts
  source/helpers/attach-element.ts
  source/helpers/click-all.ts
  source/helpers/feature-utils.ts
  source/helpers/hotfix.tsx
  source/helpers/p-utils.ts
  source/helpers/selector-observer.tsx
  source/options.tsx
  source/options/feature-list.tsx
  tsconfig.json
Labels: meta

#7979 Refactor: bumped svelte to v5
  package-lock.json
  package.json
  rollup.config.js
  source/options/header.svelte
  source/welcome.svelte
  svelte.config.js
Labels: meta

#8013 `html-preview-link` - Restore feature
  source/features/html-preview-link.tsx
Labels: bug

#8021 `show-names` - Extend support of new issue view
  source/github-helpers/selectors.ts
Labels: bug

#8020 `rgh-netiquette` - Fix console error on open PRs and issues
  source/features/jump-to-conversation-close-event.tsx
Labels: bug

#8015 `patch-diff-links` - Restore feature on non-beta issues
  package-lock.json
  package.json
  source/features/patch-diff-links.tsx
Labels: bug

#8023 `keyboard-navigation` - Restore navigation without pre-selection
  source/features/keyboard-navigation.tsx
Labels: bug

#8027 Fix options page header overflow
  source/options/header.css
  source/options/header.svelte
  source/welcome.css
  source/welcome.svelte
Labels: meta

#8028 Adjust spacing/borders in options
  source/options.css
  source/options.html
  source/options/token-validation.tsx
Labels: meta

#8029 `batch-mark-files-as-viewed` - Don't select excluded files
  source/features/batch-mark-files-as-viewed.tsx
Labels: bug

#8030 `default-branch-button` - Fix Firefox rounded corners bug
  source/features/default-branch-button.tsx
  source/refined-github.css
Labels: bug, firefox

#8031 Update dependencies
  package-lock.json
  package.json
Labels: meta

#8032 Label notifications as coming from Refined GitHub
  source/github-helpers/toast.tsx
Labels: enhancement

#8033 `mobile-tabs` - Also compact PR tabs
  source/features/mobile-tabs.css
Labels: enhancement

#8037 `clean-conversation-headers` - Support new PR view
  package-lock.json
  package.json
  source/features/actionable-pr-view-file.tsx
  source/features/clean-conversation-headers.tsx
  source/features/closing-remarks.tsx
  source/features/jump-to-conversation-close-event.tsx
  source/features/netiquette.tsx
  source/features/pr-base-commit.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/quick-review.tsx
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#8036 `clean-conversation-headers` - Use nested CSS
  source/features/clean-conversation-headers.css
  source/features/clean-conversation-headers.tsx
Labels: meta

#8040 `clean-repo-tabs` - Fix console error
  source/features/clean-repo-tabs.tsx
Labels: bug

#8041 Work around Firefox bug that causes tab freezes
  source/features/table-input.css
Labels: bug, firefox

#8044 `more-dropdown-links` - Fix duplicates on security tab
  source/features/more-dropdown-links.tsx
Labels: bug

#8043 `show-associated-branch-prs-on-fork` - Restore feature
  source/features/show-associated-branch-prs-on-fork.tsx
Labels: bug

#8047 `status-subscription` - Improve contrast
  source/features/status-subscription.css
  source/features/status-subscription.tsx
Labels: enhancement

#8042 `table-input` - Fix sidebar overlap; Further improve performance
  source/features/table-input.css
  source/features/table-input.tsx
Labels: bug

#8050 `submission-via-ctrl-enter-everywhere` - Drop feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/features.test.ts
  readme.md
  source/features/submission-via-ctrl-enter-everywhere.tsx
  source/refined-github.ts
Labels: implemented by github

#8056 `pr-branch-auto-delete` - Restore feature
  source/github-events/on-pr-merge.ts
Labels: bug

#8057 `rgh-token-user` - Fix token button style
  source/features/rgh-token-user.tsx
Labels: bug

#8070 `mobile-tabs` - Further tighten spacing
  source/features/mobile-tabs.css
Labels: enhancement

#8067 `clean-conversation-sidebar` - Don't break the label picker
  source/features/clean-conversation-sidebar.tsx
Labels: bug

#8071 `unread-anywhere` - Change shortcut to `g u` to avoid conflicts
  build/__snapshots__/features-meta.json
  readme.md
  source/features/unread-anywhere.tsx
  source/github-helpers/hotkey.tsx
Labels: bug

#8072 Don't unload persistent features on page change
  eslint.config.js
  source/feature-manager.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/command-palette-navigation-shortcuts.tsx
  source/features/embed-gist-via-iframe.tsx
  source/features/hide-user-forks.tsx
  source/features/improve-shortcut-help.tsx
  source/features/linkify-user-location.tsx
  source/features/new-repo-disable-projects-and-wikis.tsx
  source/features/parse-backticks.tsx
  source/features/profile-hotkey.tsx
  source/features/reload-failed-proxied-images.tsx
  source/features/rgh-token-user.tsx
  source/features/selection-in-new-tab.tsx
  source/features/shorten-links.tsx
  source/features/small-user-avatars.tsx
  source/features/unread-anywhere.tsx
  source/features/useful-not-found-page.tsx
Labels: bug

#8061 Fix storage display in options
  rollup.config.js
  source/helpers/used-storage.ts
  source/options.css
  source/options.html
  source/options.tsx
  source/options/storage-usage.svelte
Labels: bug, meta

#8074 Extract feature helpers
  source/feature-manager.tsx
  source/features/close-as-unplanned.tsx
  source/features/close-out-of-view-modals.tsx
  source/features/dim-bots.tsx
  source/features/improve-shortcut-help.tsx
  source/features/open-all-notifications.tsx
  source/features/pr-branch-auto-delete.tsx
  source/github-helpers/api.ts
  source/helpers/feature-helpers.ts
  source/helpers/fetch-dom.ts
Labels: meta

#8073 Make init logic more linear
  source/feature-manager.tsx
Labels: meta

#8076 `extend-diff-expander` - Support new commit view
  source/features/extend-diff-expander.css
  source/features/extend-diff-expander.tsx
Labels: bug

#8075 `netiquette` - Support new commit view
  source/features/netiquette.tsx
Labels: bug

#8048 Improve CI testing experience
  .github/workflows/features.yml
  .github/workflows/test.yml
Labels: meta

#8084 Meta: Automatically format Svelte files
  .prettierignore
  eslint.config.js
  package-lock.json
  package.json
  source/features/list-prs-for-file.gql
  source/features/show-associated-branch-prs-on-fork.gql
  source/features/tags-on-commits-list.gql
  source/features/unreleased-commits.gql
  source/options/header.css
  source/options/header.svelte
  source/options/storage-usage.svelte
  source/welcome.css
  source/welcome.svelte
Labels: meta

#8083 `reactions-avatars` - Fix feature in locked conversation
  source/features/reactions-avatars.tsx
Labels: bug

#8078 `hide-low-quality-comments` - Fix feature on linked comments
  source/features/hide-low-quality-comments.tsx
Labels: bug

#8079 Enforce `fuchsia` usage
  build/features.test.ts
  source/features/clean-conversation-headers.css
  source/features/clean-pinned-issues.css
  source/features/conflict-marker.css
  source/features/conversation-authors.css
  source/features/cross-deleted-pr-branches.css
  source/features/deep-reblame.css
  source/features/emphasize-draft-pr-label.css
  source/features/github-bugs.css
  source/features/hide-low-quality-comments.css
  source/features/highest-rated-comment.css
  source/features/link-to-compare-diff.css
  source/features/mark-private-repos.css
  source/features/mobile-tabs.css
  source/features/parse-backticks.css
  source/features/resolve-conflicts.css
  source/features/show-associated-branch-prs-on-fork.css
  source/features/status-subscription.css
  source/features/sticky-csv-header.css
  source/features/suggest-commit-title-limit.css
  source/features/table-input.css
  source/refined-github.css
Labels: meta

#8080 Add more feature validation
  build/__snapshots__/imported-features.json
  build/features.test.ts
  source/feature-manager.tsx
  source/features/mark-private-orgs.tsx
  source/features/rgh-deduplicator.tsx
  source/features/select-all-notifications-shortcut.tsx
  source/refined-github.ts
Labels: meta

#8086 `shorten-links` - Support new commit view
  source/features/shorten-links.tsx
Labels: bug

#8089 `scrollable-areas` - Support new commit view
  source/features/scrollable-areas.css
Labels: bug

#8087 `linkify-user-label` - Support new commit view
  source/github-helpers/get-comment-author.ts
Labels: bug

#7842 `locked-issue` - Detect status more reliably
  source/feature-manager.tsx
  source/features/locked-issue.tsx
  source/github-helpers/is-conversation-locked.gql
  source/github-helpers/is-conversation-locked.ts
  source/helpers/feature-helpers.ts
Labels: bug

#8095 Meta: Nested CSS
  source/features/clean-pinned-issues.css
  source/features/clean-repo-sidebar.css
  source/features/hide-low-quality-comments.css
  source/features/link-to-compare-diff.css
  source/features/night-not-found.css
  source/features/no-unnecessary-split-diff-view.css
  source/features/rgh-feature-descriptions.css
  source/features/scrollable-areas.css
  source/features/sticky-csv-header.css
Labels: meta

#8100 `scrollable-areas` - Remove from new commit conversation view
  source/features/scrollable-areas.css
Labels: bug
