Repository refined-github/refined-github, pull requests merged in 2024-12, with the labels that each got.

#8111 Fix missing colors on GitHub Enterprise
  source/features/clean-conversation-headers.css
  source/features/extend-diff-expander.css
  source/features/status-subscription.css
Labels: bug, enterprise

#8112 `clear-pr-merge-commit-message` - Clear at every opening
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#8114 `conventional-commits` - Support links following the type
  source/features/conventional-commits.tsx
  source/helpers/conventional-commits.test.ts
  source/helpers/conventional-commits.ts
Labels: bug

#8113 `one-key-formatting` - Enable on commit title fields
  source/features/one-key-formatting.tsx
Labels: bug

#8090 Meta: Small test fixes
  build/features.test.ts
  source/feature-renames.test.ts
  source/github-helpers/selectors.test.ts
Labels: meta

#8115 Options: place broken features after user-disabled feature
  source/features/pr-branch-auto-delete.tsx
  source/options/feature-list.tsx
Labels: meta

#7786 `pr-branch-auto-delete` - Skip branches with active PRs
  source/features/pr-branch-auto-delete.gql
  source/features/pr-branch-auto-delete.tsx
Labels: enhancement

#8117 Options: expand screenshot inline instead of new tab
  source/helpers/target-blank-polyfill.ts
Labels: bug

#8116 Fix GitHub bug: broken layout with long release assets names
  source/features/github-bugs.css
Labels: enhancement

#8118 Add debug link to open welcome page
  source/options.html
Labels: meta

#8121 `comments-time-machine-links` - Support new view
  source/features/comments-time-machine-links.tsx
Labels: bug

#8122 `previous-version` - Show in blame page
  source/features/previous-version.tsx
Labels: enhancement

#8127 Add button to refresh hotfixes
  source/helpers/hotfix.tsx
  source/options.html
  source/options.tsx
Labels: meta

#8128 Improve hotfix loading reliability
  source/helpers/hotfix.tsx
Labels: bug

#8131 Meta: Use `select-dom` more
  package-lock.json
  package.json
  source/features/batch-mark-files-as-viewed.tsx
  source/features/clean-repo-tabs.tsx
  source/features/clear-pr-merge-commit-message.tsx
  source/features/fit-textareas.tsx
  source/features/hidden-review-comments-indicator.tsx
  source/features/hide-low-quality-comments.tsx
  source/features/linkify-branch-references.tsx
  source/features/netiquette.tsx
  source/features/one-click-review-submission.tsx
  source/features/open-all-notifications.tsx
  source/features/release-download-count.tsx
  source/github-helpers/group-buttons.tsx
  source/options/feature-list.tsx
Labels: meta

#8130 Options: Move "Toggle all" section
  package-lock.json
  source/options.html
  source/options.tsx
  source/options/toggle-all.ts
Labels: meta

#8133 `comments-time-machine-links` - Add support for all "Code" links
  source/features/comments-time-machine-links.tsx
Labels: bug

#8132 `pull-request-hotkeys` - Restore feature
  source/features/pull-request-hotkeys.tsx
Labels: bug

#8119 `suggest-commit-title-limit` - Disable on merged PRs
  rollup.config.js
  source/feature-manager.tsx
  source/features/conversation-activity-filter.tsx
  source/features/jump-to-conversation-close-event.tsx
  source/features/suggest-commit-title-limit.tsx
  source/helpers/abortable-classname.ts
Labels: enhancement

#8135 Open Welcome page links in new tab in Safari
  source/helpers/target-blank-polyfill.ts
Labels: bug, meta, safari

#8134 `safer-destructive-actions` - Restore feature
  source/features/quick-review-comment-deletion.tsx
  source/features/safer-destructive-actions.css
Labels: bug

#8137 Options: Change visualization of fine-grained tokens
  source/github-helpers/github-token.ts
  source/options.html
  source/options/token-validation.tsx
Labels: meta

#8136 Options: Fix colors
  rollup.config.js
  source/manifest.json
  source/options.css
Labels: meta

#8140 Faster disableable CSS features
  build/features.test.ts
  source/feature-manager.tsx
  source/features/align-issue-labels.css
  source/features/align-issue-labels.tsx
  source/features/clean-pinned-issues.css
  source/features/clean-pinned-issues.tsx
  source/features/clean-rich-text-editor.css
  source/features/clean-rich-text-editor.tsx
  source/features/emphasize-draft-pr-label.css
  source/features/hide-diff-signs.css
  source/features/hide-diff-signs.tsx
  source/features/no-unnecessary-split-diff-view.css
  source/features/no-unnecessary-split-diff-view.tsx
  source/features/scrollable-areas.css
Labels: meta

#8139 `restore-file` - Add confirm modal
  source/features/restore-file.tsx
Labels: enhancement

#8138 `unread-anywhere` - Apply `pr-notification-link` to links
  source/features/pr-notification-link.tsx
  source/features/unread-anywhere.tsx
Labels: enhancement

#8143 Handle hotfix loading from GitHub Pages
  source/background.ts
  source/helpers/hotfix.tsx
  source/helpers/isomorphic-fetch.ts
Labels: bug, meta

#8141 `rgh-netiquette` - Support new views
  source/features/closing-remarks.tsx
  source/features/rgh-netiquette.tsx
  source/github-helpers/timeline-item.tsx
Labels: bug

#8162 `action-pr-link` - Support new PR view
  source/features/action-pr-link.tsx
Labels: bug

#8159 `show-names` - Fix spacing on new issues
  source/features/show-names.tsx
  source/github-helpers/selectors.ts
Labels: bug

#8163 `clear-pr-merge-commit-message` - Support new PR merge box
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#8145 `hide-low-quality-comments` - Hide more comments
  source/helpers/is-low-quality-comment.test.ts
  source/helpers/is-low-quality-comment.ts
Labels: enhancement

#8164 `closing-remarks` - Support new PR merge box
  source/github-events/on-pr-merge.ts
  source/helpers/selector-observer.tsx
Labels: bug

#8165 `pr-branch-auto-delete` - Support new PR merge box
  source/features/pr-branch-auto-delete.tsx
Labels: bug

#8151 `linkify-code` - Support inline links
  source/github-helpers/dom-formatters.tsx
Labels: enhancement

#8170 Add "Reload without Refined GitHub" action
  package-lock.json
  package.json
  source/background.ts
  source/feature-manager.tsx
  source/options/reload-without.ts
Labels: meta
