Repository refined-github/refined-github, pull requests merged in 2024-03, with the labels that each got.

#7306 Fix colors on dark themes
  source/refined-github.css
Labels: bug

#7278 `previous-next-commit-buttons` - Restore feature
  source/features/previous-next-commit-buttons.tsx
Labels: bug

#7307 Ensure support for Firefox for Android
  source/manifest.json
Labels: firefox, mobile

#7315 Disable 4 slow features in Firefox/Safari
  source/features/locked-issue.tsx
  source/features/quick-comment-edit.tsx
  source/features/quick-review-comment-deletion.tsx
  source/features/show-whitespace.tsx
  source/helpers/7116.tsx
Labels: firefox, safari

#7313 Use new GitHub color variables
  source/features/clean-conversation-headers.css
  source/features/clean-footer.css
  source/features/conflict-marker.css
  source/features/emphasize-draft-pr-label.css
  source/features/extend-diff-expander.css
  source/features/github-bugs.css
  source/features/hide-low-quality-comments.css
  source/features/highest-rated-comment.css
  source/features/highlight-collaborators-and-own-conversations.css
  source/features/link-to-compare-diff.css
  source/features/mark-private-repos.css
  source/features/mobile-tabs.css
  source/features/parse-backticks.css
  source/features/resolve-conflicts.css
  source/features/show-associated-branch-prs-on-fork.css
  source/features/sticky-csv-header.css
  source/features/table-input.css
  source/github-helpers/heat-map.css
  source/refined-github.css
Labels: bug
