Repository refined-github/refined-github, pull requests merged in 2024-10, with the labels that each got.

#7844 Fix a few options page bugs
  source/feature-manager.tsx
  source/features/select-notifications.tsx
  source/helpers/bisect.tsx
  source/options.css
  source/options.tsx
  source/options/feature-list.tsx
Labels: bug

#7845 Meta: Reorganize options page code (token validation)
  source/github-helpers/github-token.ts
  source/helpers/conventional-commits.ts
  source/helpers/used-storage.ts
  source/options.css
  source/options.html
  source/options.tsx
  source/options/token-validation.tsx
Labels: meta

#7859 `default-branch-button` - Fix pink button on GHE
  source/features/default-branch-button.css
Labels: bug, enterprise

#7863 Meta: Move metadata guidelines to wiki
  readme.md
Labels: meta

#7868 Fix sponsor button size in mobile view
  source/features/github-bugs.css
Labels: enhancement

#7848 `sidebar-focus-file` - New feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  readme.md
  source/features/sidebar-focus-file.tsx
  source/refined-github.ts
Labels: enhancement

#7864 Improve options page forms style across browsers
  package-lock.json
  package.json
  source/options.css
  source/options.html
  source/options.tsx
Labels: meta

#7866 `quick-repo-deletion` - Two-click deletion with key modifiers
  .github/pull_request_template.md
  build/__snapshots__/features-meta.json
  readme.md
  source/features/quick-repo-deletion.tsx
  source/features/rgh-pr-template.tsx
  source/github-helpers/toast.tsx
Labels: enhancement

#7873 `more-conversation-filters` - Fix error on new beta view
  source/features/more-conversation-filters.tsx
Labels: bug

#7880 `release-download-count` - Fix misalignment
  source/features/release-download-count.css
  source/features/release-download-count.tsx
Labels: bug

#7874 `hide-issue-list-autocomplete` - Fix error on new beta view
  source/features/hide-issue-list-autocomplete.tsx
Labels: bug

#7876 `clean-conversation-filters` - Add support for new beta view
  source/features/clean-conversation-filters.tsx
  source/refined-github.css
Labels: bug

#7869 `download-folder-button` - Add to permalinks and archived repos
  source/features/download-folder-button.tsx
  source/helpers/recreate-element.ts
Labels: bug

#7879 `mobile-tabs` - Improve reliability
  build/__snapshots__/imported-features.json
  source/features/mobile-tabs.css
  source/features/mobile-tabs.tsx
  source/refined-github.ts
Labels: bug

#7882 `select-notifications` - Improve spacing and alignment
  source/features/select-notifications.tsx
Labels: bug

#7883 Update dependencies
  eslint.config.js
  package-lock.json
  package.json
  source/features/clean-repo-sidebar.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conversation-activity-filter.tsx
  source/features/pr-first-commit-title.tsx
  source/options/feature-list.tsx
Labels: meta

#7884 `linkify-code` - Add support for `GH-num` and `forkuser@num`
  package-lock.json
  package.json
  source/features/linkify-code.tsx
  source/features/rgh-pr-template.tsx
  source/github-helpers/dom-formatters.tsx
Labels: enhancement

#7854 Improve first-install flow to facilitate token input
  build/__snapshots__/imported-features.json
  eslint.config.js
  package-lock.json
  package.json
  rollup.config.js
  source/background.ts
  source/features/rgh-improve-new-issue-form.tsx
  source/features/rgh-options-link.tsx
  source/features/rgh-welcome-issue.css
  source/features/rgh-welcome-issue.tsx
  source/github-helpers/github-token.ts
  source/helpers/target-blank-polyfill.ts
  source/options.html
  source/options.tsx
  source/refined-github.ts
  source/welcome.css
  source/welcome.html
  source/welcome.svelte
Labels: meta

#7798 Improve user capability detection across multiple features
  source/features/clear-pr-merge-commit-message.tsx
  source/features/closing-remarks.tsx
  source/features/netiquette.tsx
  source/features/pr-branch-auto-delete.tsx
  source/features/quick-comment-edit.tsx
  source/features/quick-repo-deletion.tsx
  source/features/show-open-prs-of-forks.tsx
  source/features/unreleased-commits.tsx
  source/github-helpers/get-user-permission.ts
  source/github-helpers/github-token.ts
  source/options-storage.ts
Labels: enhancement

#7899 Improve console output for features that require a token
  build/features.test.ts
  source/feature-manager.tsx
  source/features/bugs-tab.tsx
  source/features/ci-link.tsx
  source/features/clean-conversation-filters.tsx
  source/features/clean-conversation-headers.tsx
  source/features/clear-pr-merge-commit-message.tsx
  source/features/comments-time-machine-links.tsx
  source/features/conflict-marker.tsx
  source/features/deep-reblame.tsx
  source/features/default-branch-button.tsx
  source/features/github-actions-indicators.tsx
  source/features/highlight-non-default-base-branch.tsx
  source/features/list-prs-for-file.tsx
  source/features/mark-merge-commits-in-list.tsx
  source/features/pinned-issues-update-time.tsx
  source/features/pr-filters.tsx
  source/features/previous-version.tsx
  source/features/profile-gists-link.tsx
  source/features/release-download-count.tsx
  source/features/releases-dropdown.tsx
  source/features/repo-header-info.tsx
  source/features/repo-wide-file-finder.tsx
  source/features/restore-file.tsx
  source/features/show-associated-branch-prs-on-fork.tsx
  source/features/show-names.tsx
  source/features/tags-on-commits-list.tsx
  source/features/useful-not-found-page.tsx
  source/features/user-local-time.tsx
  source/github-helpers/api.ts
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
Labels: meta

#7825 Capture source feature for all errors automatically
  source/feature-manager.tsx
  source/features/convert-release-to-draft.tsx
  source/features/expand-all-hidden-comments.tsx
  source/features/linkify-code.tsx
  source/features/linkify-user-labels.tsx
  source/features/netiquette.tsx
  source/features/new-or-deleted-file.tsx
  source/features/one-click-review-submission.tsx
  source/features/quick-review-comment-deletion.tsx
  source/features/restore-file.tsx
  source/features/update-pr-from-base-branch.tsx
  source/features/visit-tag.tsx
  source/github-helpers/dom-formatters.tsx
  source/helpers/dom-utils.ts
  source/helpers/errors.ts
Labels: meta

#7900 Improve layout of feature list in options
  source/options.css
  source/options.html
  source/options/feature-list.tsx
  source/welcome.svelte
Labels: meta

#7902 `clean-conversation-filters` - Fix error on project-free orgs
  source/features/clean-conversation-filters.tsx
Labels: bug

#7885 Meta: Avoid typescript target assertions
  source/helpers/clear-cache-handler.ts
  source/options.tsx
  source/options/feature-list.tsx
Labels: meta

#7903 Meta: Improve "New Issue" templates
  .github/ISSUE_TEMPLATE/3_discussion.md
  .github/release.yml
  source/features/rgh-improve-new-issue-form.tsx
Labels: meta

#7905 Fix recent token-related issues
  source/github-helpers/get-user-permission.ts
  source/github-helpers/github-token.ts
  source/options-storage.ts
  source/options/token-validation.tsx
  source/welcome.svelte
Labels: bug

#7904 Show Welcome page to some existing users
  package-lock.json
  package.json
  source/background.ts
  source/helpers/used-storage.ts
Labels: meta

#7888 `tab-to-indent` - Support new text fields
  source/features/unfinished-comments.tsx
  source/github-events/on-field-keydown.tsx
Labels: bug

#7890 `unfinished-comments` - Support new text fields
  source/features/unfinished-comments.tsx
Labels: bug

#7891 `clean-rich-text-editor` - Support new text fields
  source/features/clean-rich-text-editor.css
Labels: bug

#7889 `netiquette` - Support new text fields (partial)
  source/features/netiquette.tsx
Labels: bug

#7892 `one-key-formatting` - Support new issue view
  source/features/esc-to-cancel.tsx
  source/github-events/on-field-keydown.tsx
Labels: bug

#7906 Fix some Firefox issues; switch to MV3 in Firefox too
  .github/workflows/release.yml
  build/manifest.js
  package.json
  source/background.ts
  source/welcome.svelte
Labels: bug, meta, firefox

#7923 Improve options page style
  eslint.config.js
  rollup.config.js
  source/features/select-notifications.tsx
  source/features/suggest-commit-title-limit.tsx
  source/github-helpers/search-query.ts
  source/options.css
  source/options.html
  source/options/header.css
  source/options/header.svelte
  source/welcome.css
  source/welcome.html
  source/welcome.svelte
Labels: meta

#7931 `table-input` - Support new text fields
  source/features/table-input.tsx
Labels: bug

#7924 `small-user-avatars` - Support new issue page
  source/features/small-user-avatars.tsx
Labels: bug

#7921 `unreleased-commits` - Only show "Create release" if allowed
  source/features/unreleased-commits.tsx
Labels: bug

#7909 `patch-diff-links` - Support new commit view
  source/features/patch-diff-links.tsx
Labels: bug

#7937 `fit-textareas` - Avoid conflict with native feature
  source/features/fit-textareas.css
  source/features/fit-textareas.tsx
Labels: bug

#7911 `linkify-user-labels` - Support new issue view
  source/features/linkify-user-labels.tsx
  source/github-helpers/get-comment-author.ts
Labels: bug

#7929 `collapsible-content-button` - Support new text fields
  source/features/collapsible-content-button.tsx
Labels: bug

#7915 `mobile-tabs` - Fix layout on profiles
  source/features/mobile-tabs.css
Labels: bug, mobile

#7912 `sticky-sidebar` - Support new issue view
  source/features/sticky-sidebar.css
  source/features/sticky-sidebar.tsx
Labels: bug

#7941 `hide-newsfeed-noise` - Drop feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/features.test.ts
  readme.md
  source/feature-renames.json
  source/features/hide-newsfeed-noise.css
  source/features/hide-newsfeed-noise.tsx
  source/refined-github.ts
Labels: change request, implemented by github

#7918 Animate notifications
  source/github-helpers/toast.tsx
Labels: meta

#7930 `reactions-avatars` - Support new issue view
  source/features/github-bugs.css
  source/features/quick-label-removal.tsx
  source/features/reactions-avatars.css
  source/features/reactions-avatars.tsx
  source/features/status-subscription.tsx
  source/github-helpers/get-user-avatar.ts
Labels: bug

#7946 `pr-branch-auto-delete` - Preserve more `release` branches
  source/features/pr-branch-auto-delete.tsx
Labels: enhancement

#7940 `ci-link` - Add explanatory tooltip
  source/features/ci-link.tsx
Labels: enhancement

#7943 `infinite-scroll` - Drop feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/features.test.ts
  readme.md
  source/features/infinite-scroll.tsx
  source/refined-github.ts
Labels: change request

#7947 Log broken selectors in the observer
  source/helpers/errors.ts
  source/helpers/event-listener-loop.test.ts
  source/helpers/event-listener-loop.ts
  source/helpers/selector-observer.tsx
Labels: meta

#7949 Workaround for fatal Safari CSS bug
  package-lock.json
  package.json
  rollup.config.js
Labels: bug, meta, safari

#7956 `link-to-changelog-file` - Make UI more compact
  source/features/link-to-changelog-file.tsx
Labels: enhancement

#7950 Use nested CSS
  source/features/align-issue-labels.css
  source/features/center-reactions-popup.css
  source/features/dim-bots.css
  source/features/hide-navigation-hover-highlight.css
  source/features/quick-label-removal.css
  source/features/reactions-avatars.css
  source/features/release-download-count.css
  source/features/rgh-feature-descriptions.css
  source/features/scrollable-areas.css
  source/features/show-associated-branch-prs-on-fork.css
  source/features/suggest-commit-title-limit.css
  source/github-helpers/heat-map.css
Labels: meta

#7963 `default-branch-button` - Fix wrapping on mobile
  source/features/default-branch-button.tsx
  source/features/hide-navigation-hover-highlight.css
  source/github-helpers/group-buttons.tsx
Labels: bug, mobile

#7961 `select-notifications` - Fix selection bug
  package-lock.json
  source/features/select-notifications.tsx
Labels: bug

#7964 Fix GitHub bug: Notification buttons overlap on mobile
  source/features/github-bugs.css
Labels: enhancement, github bug

#7952 `scrollable-areas` - Support new issue view
  source/features/scrollable-areas.css
Labels: bug

#7965 `linkify-code` - Restore feature
  source/features/linkify-code.tsx
  source/github-helpers/dom-formatters.tsx
Labels: bug

#7972 Meta: Fix TODOs date
  source/features/collapsible-content-button.tsx
  source/features/esc-to-cancel.tsx
Labels: meta

#7973 `highlight-collaborators-and-own-conversations` - Rename to `conversation-authors`
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  readme.md
  source/feature-renames.json
  source/features/conversation-authors.css
  source/features/conversation-authors.tsx
  source/refined-github.css
  source/refined-github.ts
Labels: meta

#7971 `conversation-authors` - Support new issue view
  source/features/conversation-authors.tsx
Labels: bug

#7955 `prevent-link-loss` - Support new input field
  package-lock.json
  package.json
  source/features/prevent-link-loss.tsx
Labels: bug

#7982 `show-names` - Support new issue view
  source/github-helpers/selectors.ts
Labels: bug

#7975 `small-user-avatars` - Don't duplicate native functionality
  source/features/small-user-avatars.tsx
Labels: bug

#7985 `linkify-code` - Restore feature
  source/features/linkify-code.tsx
  source/github-helpers/dom-formatters.tsx
Labels: bug

#7981 `shorten-links` - Support new issue view
  source/features/shorten-links.tsx
  source/github-helpers/dom-formatters.tsx
Labels: bug

#7974 `emphasize-draft-pr-label` - Support new issue view
  source/features/emphasize-draft-pr-label.css
Labels: bug
