Repository refined-github/refined-github, pull requests merged in 2024-01, with the labels that each got.

#7210 Exclude non-standalone CSS features from test URLs check
  build/verify-test-urls.sh
Labels: meta

#7197 `fit-textareas` - Fit on focus
  source/features/fit-textareas.tsx
Labels: enhancement

#7212 Fix flacky selectors tests
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: meta

#7189 Automatically fit comment preview height
  build/verify-test-urls.sh
  source/features/github-bugs.css
Labels: enhancement, github bug

#7214 `table-input`/`collapsible-content-button` - Fix overflow
  source/features/collapsible-content-button.tsx
  source/features/table-input.tsx
Labels: bug

#7220 `quick-comment-hiding` - Use AJAX again
  source/features/quick-comment-hiding.tsx
Labels: bug

#7194 `show-associated-branch-prs-on-fork` - Support new page style
  source/features/show-associated-branch-prs-on-fork.css
  source/features/show-associated-branch-prs-on-fork.tsx
Labels: bug
