Repository refined-github/refined-github, pull requests merged in 2024-06, with the labels that each got.

#7378 Improve `has`-selector performance
  source/features/locked-issue.css
  source/features/locked-issue.tsx
  source/features/quick-comment-edit.css
  source/features/quick-comment-edit.tsx
  source/features/quick-mention.tsx
  source/features/readable-title-change-events.css
Labels: performance

#7376 `unreleased-commits` - Avoid internal wrapping
  source/features/unreleased-commits.tsx
Labels: bug

#7350 `clean-conversation-sidebar` - Restore mistakenly-hidden links
  source/features/clean-conversation-sidebar.tsx
Labels: bug

#7380 Show token owner in options page
  source/options.tsx
Labels: meta

#7385 Drop outdated code
  source/features/clean-rich-text-editor.css
  source/features/closing-remarks.tsx
  source/features/file-age-color.tsx
  source/features/mobile-tabs.tsx
  source/features/one-click-review-submission.tsx
  source/features/previous-next-commit-buttons.tsx
  source/features/quick-file-edit.tsx
  source/features/rgh-dim-commits.tsx
  source/features/tags-on-commits-list.tsx
  source/features/unreleased-commits.tsx
  source/github-helpers/group-buttons.tsx
Labels: meta

#7386 `toggle-files-button` - Restore feature
  build/__snapshots__/features-meta.json
  readme.md
  source/features/toggle-files-button.css
  source/features/toggle-files-button.tsx
Labels: bug

#7383 `quick-review` - Restore auto-focus
  source/features/quick-review.tsx
Labels: bug

#7387 `small-user-avatars` - Fix wrapping
  source/features/small-user-avatars.tsx
Labels: bug

#7391 `selection-in-new-tab` - Restore feature
  source/features/quick-comment-edit.tsx
  source/features/selection-in-new-tab.tsx
Labels: bug

#7392 `close-out-of-view-modals` - Fix conflict with Development menu
  source/features/close-out-of-view-modals.tsx
Labels: bug

#7394 `quick-new-issue` - Restore feature
  source/features/quick-new-issue.tsx
Labels: bug

#7388 Show token owner in options page: GHE support
  source/options.tsx
Labels: meta

#7395 `rgh-improve-new-issue-form` - Improve wording on incomplete tokens
  source/features/rgh-improve-new-issue-form.tsx
Labels: meta

#7396 `swap-branches-on-compare` - Show when list is empty
  source/features/swap-branches-on-compare.tsx
Labels: bug

#7397 `quick-label-removal` - Don't restore labels when adding some
  source/features/quick-label-removal.tsx
Labels: firefox

#7407 Stop allowing "all urls" as a permission
  package-lock.json
  package.json
  source/background.ts
Labels: meta

#7402 `github-actions-indicators` - Restore feature
  source/features/github-actions-indicators.tsx
Labels: bug

#7401 `one-click-pr-or-gist` - Fix mobile wrapping
  package.json
  source/features/one-click-pr-or-gist.tsx
Labels: bug

#7403 `default-branch-button` - Various fixes
  source/features/default-branch-button.tsx
Labels: bug

#7411 `restore-file` - Restore UTF-8 support
  source/background.ts
  source/features/restore-file.tsx
  source/features/toggle-files-button.css
Labels: bug

#7412 Meta: Move contributing guide to wiki
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  build/new-feature.sh
  contributing.md
  readme.md
Labels: meta

#7413 Meta: Invite users to add token
  source/features/rgh-improve-new-issue-form.tsx
  source/features/rgh-welcome-issue.css
  source/options.html
Labels: meta

#7431 `previous-version` - Restore feature
  source/features/previous-version.tsx
Labels: ajax

#7430 `default-branch-button` - Fix overlap with other components
  source/features/default-branch-button.css
  source/features/default-branch-button.tsx
Labels: bug

#7421 `fit-textareas` - Enable CSS-native feature where available
  source/features/fit-textareas.css
  source/features/fit-textareas.tsx
Labels: enhancement, performance

#7435 Meta: Improve error message related to fine-grained tokens
  source/feature-manager.tsx
Labels: meta

#7436 `quick-review` - Update view after quick approval
  source/features/quick-review.tsx
  source/github-helpers/index.ts
Labels: enhancement

#7437 Meta: Allow opening the options page via "Button Link"
  source/background.ts
  source/options-storage.ts
  source/options.html
Labels: enhancement

#7450 Restore extension
  source/features/fit-textareas.tsx
Labels: bug

#7441 `locked-issue` - Fix performance issues
  package-lock.json
  package.json
  source/features/locked-issue.tsx
Labels: enhancement, performance

#7456 Meta: Fix opening the options page via "Button Link"
  source/background.ts
Labels: bug

#7432 `netiquette` - Add banner to popular issues
  source/features/netiquette.tsx
  source/features/rgh-netiquette.tsx
Labels: enhancement

#7457 Meta: `locked-issue` - Fix comment typo
  source/features/locked-issue.tsx
Labels: meta

#7451 `list-pr-for-files` - Improve performance
  source/features/default-branch-button.css
  source/features/default-branch-button.tsx
  source/features/list-prs-for-file.css
  source/features/list-prs-for-file.tsx
  source/github-helpers/index.ts
  source/refined-github.css
Labels: bug

#7429 Meta: Clarify "Conversation" jargon
  build/__snapshots__/features-meta.json
  readme.md
Labels: meta

#7434 `open-all-notifications` - Add keyboard shortcut: P
  source/features/deep-reblame.tsx
  source/features/open-all-notifications.tsx
  source/features/status-subscription.tsx
  source/github-helpers/index.ts
Labels: enhancement

#7428 `suggest-commit-title-limit` - Enable on PR title
  build/__snapshots__/features-meta.json
  readme.md
  source/features/suggest-commit-title-limit.css
  source/features/suggest-commit-title-limit.tsx
  source/features/sync-pr-commit-title.tsx
  source/github-helpers/index.ts
Labels: enhancement

#7427 `conversation-activity-filter` - Add label to Events
  source/features/conversation-activity-filter.css
  source/features/conversation-activity-filter.tsx
Labels: enhancement

#7422 `sort-conversations-by-update-time` - Various improvements
  source/features/bugs-tab.tsx
  source/features/sort-conversations-by-update-time.tsx
  source/github-helpers/search-query.test.ts
  source/github-helpers/search-query.ts
  source/github-helpers/selectors.ts
Labels: enhancement

#7426 `linkify-line-numbers` - New feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.txt
  package-lock.json
  package.json
  readme.md
  source/features/linkify-line-numbers.tsx
  source/refined-github.ts
Labels: enhancement

#7473 Migrate to MV3
  package-lock.json
  package.json
  source/background.ts
  source/features/resolve-conflicts.tsx
  source/manifest.json
Labels: meta

#7482 Drop `webextension-polyfill`
  package-lock.json
  package.json
  source/background.ts
  source/feature-manager.tsx
  source/features/embed-gist-inline.tsx
  source/features/quick-repo-deletion.tsx
  source/features/resolve-conflicts.tsx
  source/features/rgh-improve-new-issue-form.tsx
  source/features/selection-in-new-tab.tsx
  source/helpers/hotfix.tsx
  source/helpers/is-development-version.ts
  source/helpers/open-options.ts
  source/helpers/open-tabs.ts
  source/helpers/types.d.ts
  source/helpers/used-storage.ts
  source/options.tsx
  webpack.config.ts
Labels: meta

#7480 Improve support for mobile Firefox
  package-lock.json
  package.json
  source/helpers/feature-utils.ts
Labels: bug, firefox, mobile

#7485 Avoid "Permission needed" bug on Firefox for now
  .github/workflows/release.yml
  build/manifest.js
  package.json
Labels: firefox

#7488 Drop Node 0.4 dependencies
  package-lock.json
  package.json
Labels: meta

#7489 Add "Options…" context menu to Firefox and Safari
  package-lock.json
  package.json
  source/background.ts
Labels: enhancement, firefox, safari

#7487 `show-whitespace` - Restore feature on Firefox and Safari
  source/features/show-whitespace.tsx
Labels: firefox, safari

#7492 `visit-tag` - Work around GitHub tag picker icon bug
  source/features/visit-tag.tsx
Labels: bug

#7495 `tags-on-commits-list` - Restore feature
  source/features/tags-on-commits-list.tsx
Labels: bug

#7497 Fix broken link in readme
  readme.md
Labels: meta

#7490 `shorten-links` - Improve shortener
  package-lock.json
  package.json
Labels: enhancement

#7494 Larger text size in the options
  source/options.css
Labels: enhancement

#7499 `rgh-netiquette` - Keep on screen
  source/features/rgh-netiquette.tsx
Labels: meta

#7501 Meta: Move guides to Wiki
  collaborators.md
  contributing.md
Labels: meta

#7500 Upload source to Mozilla Addons
  .github/workflows/release.yml
  build/AMO_BUILD_INSTRUCTIONS
Labels: meta

#7498 `closing-remarks` - Add link to more details
  source/features/closing-remarks.tsx
Labels: enhancement

#7508 `list-prs-for-file` - Prevent symbols panel overlapping
  source/features/list-prs-for-file.tsx
  source/github-helpers/index.ts
  source/refined-github.css
Labels: bug

#7507 `list-prs-for-file` - Style improvements
  source/features/list-prs-for-file.tsx
Labels: enhancement

#7511 Prevent options checkbox position change
  source/options.css
  source/options.tsx
Labels: bug

#7512 `clean-footer` - Restore feature
  source/features/clean-footer.css
Labels: bug

#7517 `netiquette` - Fix spacing on small screen
  source/features/netiquette.tsx
Labels: bug, mobile

#7516 `netiquette` - Support review comments
  source/features/netiquette.tsx
Labels: enhancement
