Repository refined-github/refined-github, pull requests merged in 2025-04, with the labels that each got.

#8373 `quick-mention` - Restore feature on issues
  source/features/quick-mention.tsx
Labels: bug

#8374 `warn-pr-from-master` - Avoid duplicate error banner
  source/features/warn-pr-from-master.tsx
Labels: bug

#8369 `github-actions-indicators` - Open dropdown on icon click
  source/features/esc-to-deselect-line.tsx
  source/features/github-actions-indicators.tsx
  source/helpers/history.ts
Labels: enhancement

#8368 `closing-remarks` - Clarify message
  source/features/closing-remarks.tsx
Labels: enhancement

#8371 `update-pr-from-base-branch` - Try harder to avoid duplication
  package-lock.json
  package.json
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#8358 Fix URL parsing and detection across multiple features
  package-lock.json
  package.json
  source/github-helpers/github-file-url.test.ts
  source/github-helpers/github-file-url.ts
Labels: bug

#8359 `closing-remarks` - Show "Create release" only to collaborators
  source/features/closing-remarks.tsx
  source/github-helpers/banner.tsx
Labels: bug

#8389 `small-user-avatar` - Support clipped mentions in hovercards
  source/features/small-user-avatars.tsx
  source/github-helpers/get-user-avatar.ts
Labels: bug

#8394 `no-modals` - Support global issues page
  source/features/no-modals.tsx
Labels: enhancement

#8401 Drop support for GHE on Safari due to Safari 18.4 bug
  build/prepare-safari-release.sh
Labels: change request, safari

#8407 Style fill stared icon and code in commit title
  source/features/github-bugs.css
  source/refined-github.css
Labels: enhancement

#8421 `repo-header-info` - Restore feature
  source/features/repo-header-info.tsx
Labels: bug
