Repository refined-github/refined-github, pull requests merged in 2025-07, with the labels that each got.

#8509 `readable-title-change-events` - Support new issue view
  source/features/readable-title-change-events.css
Labels: bug

#8507 `linkify-user-location` - Use Open Street Map instead of Google Maps
  source/features/linkify-user-location.tsx
Labels: change request

#8511 `clear-pr-merge-commit-message` - Restore feature
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#8525 `table-input` - Fix colors
  source/features/table-input.css
Labels: bug

#8523 `show-names` - Fix spacing
  source/features/show-names.tsx
Labels: bug

#8536 Meta: Fix sponsor logos in readme
  media/sponsor-frappe-dark.png
  media/sponsor-frappe-light.png
  media/sponsor-prisma-dark.svg
  media/sponsor-prisma-light.svg
  readme.md
Labels: meta

#8542 `sticky-notifications-actions` - Improve performance
  source/features/sticky-notifications-actions.css
Labels: bug

#8533 `quick-file-edit` - Fix icon alignment
  source/features/quick-file-edit.css
Labels: bug

#8560 `bugs-tab` - Support `category:bug`
  source/github-helpers/bugs-label.ts
Labels: enhancement

#8551 `pr-jump-to-first-non-viewed-file` - Support new PR Files view
  source/features/pr-jump-to-first-non-viewed-file.tsx
Labels: bug

#8567 `no-modals` - Restore feature
  source/features/no-modals.tsx
Labels: bug

#8566 `netiquette` - Fix banner margins
  source/features/netiquette.tsx
Labels: bug

#8562 `new-or-deleted-files`: Support new PR files view
  source/features/new-or-deleted-file.tsx
Labels: bug

#8570 `restore-file` - Ask for commit title
  source/features/restore-file.tsx
Labels: enhancement

#8527 `align-issue-labels` - Support new issue lists
  build/__snapshots__/features-meta.json
  build/features.test.ts
  readme.md
  source/features/align-issue-labels.css
  source/features/align-issue-labels.tsx
Labels: bug

#8578 `bugs-tab` - Stop counting bugs twice when using issue types
  source/features/bugs-tab.tsx
Labels: bug
