Repository refined-github/refined-github, pull requests merged in 2025-09, with the labels that each got.

#8660 `unread-anywhere` - Restore on notifications page
  source/features/unread-anywhere.tsx
Labels: bug

#8666 `show-names` - Strip emojis
  package-lock.json
  package.json
  source/features/show-names.tsx
Labels: enhancement

#8669 Drop "more extensions" link from readme
  readme.md
Labels: meta

#8668 `conflict-marker` - Remove feature for repo issue list
  source/github-helpers/selectors.ts
Labels: bug

#8673 `readable-title-change-events` - Restore line through
  source/features/readable-title-change-events.css
Labels: github bug
