Repository refined-github/refined-github, pull requests merged in 2025-03, with the labels that each got.

#8314 `small-user-avatars` - Fix own avatar size
  source/features/small-user-avatars.css
Labels: bug

#8303 Drop `embed-gist-via-iframe` feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  readme.md
  source/features/embed-gist-via-iframe.tsx
  source/refined-github.ts
Labels: change request

#8326 `netiquette` - Switch write/preview tabs cause multiple banner
  source/features/netiquette.tsx
Labels: bug

#8327 `clear-pr-merge-commit-message` - Support new merge box view
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#8334 `clean-repo-filelist-actions` - Restore feature
  build/__snapshots__/features-meta.json
  source/features/clean-repo-filelist-actions.css
  source/features/clean-repo-filelist-actions.tsx
Labels: bug

#8338 `emphasize-draft-pr-label` - Support in notifications
  source/features/emphasize-draft-pr-label.css
Labels: enhancement

#8329 Ensure disabled CSS features stay disabled after navigation
  source/feature-manager.tsx
Labels: bug

#8348 `clear-pr-merge-commit-message` - Restore feature in new merge box
  source/features/clear-pr-merge-commit-message.tsx
Labels: bug

#8357 `small-user-avatar` - Restore feature
  source/features/small-user-avatars.tsx
Labels: bug

#8363 `rgh-improve-new-issue-form` - Restore feature
  package-lock.json
  package.json
  source/features/rgh-improve-new-issue-form.tsx
  source/helpers/dom-utils.ts
Labels: bug

#8366 `no-target-blank` - New feature
  build/__snapshots__/features-meta.json
  build/__snapshots__/imported-features.json
  build/features.test.ts
  eslint.config.js
  readme.md
  source/features/no-target-blank.tsx
  source/refined-github.ts
Labels: enhancement
