Repository refined-github/refined-github, pull requests merged in 2025-02, with the labels that each got.

#8265 `pr-approvals-count` - Highlight "Review Required" in yellow
  source/features/pr-approvals-count.css
  source/refined-github.css
Labels: enhancement

#8276 `clean-rich-text-editor` - Restore feature on the first comment
  source/features/clean-rich-text-editor.css
Labels: bug

#8274 `embed-gist-inline` - Restore feature on the first comment
  source/github-helpers/selectors.ts
Labels: bug

#8277 Restore 3 features on the first comment of issues
  source/features/comments-time-machine-links.tsx
  source/features/shorten-links.tsx
  source/github-helpers/get-comment-author.ts
Labels: bug

#8284 Meta: Fix typos discovered by codespell
  .github/workflows/test.yml
  source/features/default-branch-button.css
  source/features/github-bugs.css
  source/features/global-conversation-list-filters.tsx
Labels: meta

#8279 `repo-wide-file-finder` - Fix conflict with native shortcut
  source/features/repo-wide-file-finder.tsx
Labels: bug

#8285 `action-used-by-link` - Restore feature
  source/features/action-used-by-link.tsx
Labels: bug

#8290 `tags-on-commits-list` - Improve support for multiple tags
  source/features/tags-on-commits-list.tsx
Labels: bug

#8292 Options page: Don't disable all features when pressing `enter`
  source/options.html
Labels: bug, meta

#8297 `conventional-commits` - Fix grouping on commits with parens
  source/helpers/conventional-commits.test.ts
  source/helpers/conventional-commits.ts
Labels: bug

#8300 `small-user-avatars` - Don't quote avatar into comment field
  build/__snapshots__/features-meta.json
  source/features/small-user-avatars.css
  source/features/small-user-avatars.tsx
Labels: enhancement

#8282 `conflict-marker` - Add support for new issue view
  source/features/conflict-marker.tsx
  source/github-helpers/selectors.ts
Labels: bug
