Repository refined-github/refined-github, pull requests merged in 2025-01, with the labels that each got.

#8187 `quick-review` - More native look
  source/features/quick-review.tsx
Labels: enhancement

#8171 Update `webext-options-sync-per-domain`
  package-lock.json
  package.json
  source/options.tsx
  source/options/token-validation.tsx
Labels: help wanted, meta

#8197 `sticky-sidebar` - Support discussions
  source/features/sticky-sidebar.css
  source/features/sticky-sidebar.tsx
Labels: enhancement

#8190 `esc-to-deselect-line` - Restore feature
  source/features/esc-to-deselect-line.tsx
Labels: bug

#8192 `linkify-user-location` - Support organization profile
  source/features/linkify-user-location.tsx
Labels: enhancement

#8188 `conversation-activity-filter` - Fix position and color
  source/features/conversation-activity-filter.tsx
Labels: bug

#8194 `show-names` - Add support for RTL names
  build/__snapshots__/features-meta.json
  source/features/show-names.css
  source/features/show-names.tsx
  source/github-helpers/index.test.ts
  source/github-helpers/index.ts
Labels: bug

#8208 GitHub bug fix: remove bad spacing in notifications header
  source/features/github-bugs.css
Labels: enhancement

#8220 Update token creation link /2
  source/options.html
  source/welcome.svelte
Labels: meta

#8225 `quick-mention` - Support new issue view
  source/features/quick-mention.css
  source/features/quick-mention.tsx
Labels: bug

#8193 `update-pr-from-base-branch` - Support new view
  source/features/update-pr-from-base-branch.tsx
Labels: bug

#8189 `easy-toggle-files` - Support new commit view
  source/features/easy-toggle-files.tsx
Labels: bug

#8233 Meta: Cleanup dependencies
  package-lock.json
  package.json
  source/background.ts
  source/helpers/dom-utils.ts
  source/helpers/target-blank-polyfill.ts
  source/options.tsx
  source/options/reload-without.ts
  source/welcome.svelte
Labels: meta

#8238 Restore 4 features on commit lists
  source/features/rgh-dim-commits.tsx
  source/features/tags-on-commits-list.tsx
  source/github-helpers/selectors.ts
Labels: bug
